#!/usr/bin/env node
// Build an "iPhone 17 Pro style" product promo as a HyperFrames composition from a plan file.
//
// Usage: node build-promo.mjs <project-dir> [--plan ip-plan.json] [--force]
//
// Writes <project>/index.html, the runtime kit in <project>/ip/ (including a three.js bundle),
// trimmed audio in <project>/ip/audio/, and DESIGN.md (regenerated on every build unless the
// project has a hand-written one, which is archived under <project>/archive/ instead).
// Everything is local: plan files must live inside the project, and nothing is fetched.
// Timings default to the values measured from the reference; see ../references/.

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, renameSync, cpSync, openSync, readSync, closeSync, statSync } from "node:fs";
import { join, resolve, dirname, relative, extname, isAbsolute, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";

const SKILL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT_ROOT = resolve(SKILL, "../../..");
const require = createRequire(join(KIT_ROOT, "package.json"));
const GENERATED = "<!-- generated by ip-17-pro-style/build-promo.mjs -->";

const args = process.argv.slice(2);
if (!args.length || args.includes("--help")) {
  console.log("Usage: node build-promo.mjs <project-dir> [--plan ip-plan.json] [--force]");
  process.exit(args.length ? 0 : 1);
}
const project = resolve(args[0]);
const planArg = args.includes("--plan") ? args[args.indexOf("--plan") + 1] : "ip-plan.json";
if (!planArg || planArg.startsWith("--")) { console.error("--plan needs a file name (relative to the project)."); process.exit(1); }
const planPath = resolve(project, planArg);
const force = args.includes("--force");

const errors = [];
const warnings = [];
const fail = m => errors.push(m);
const warn = m => warnings.push(m);
function done() {
  for (const w of warnings.splice(0)) console.warn(`warning: ${w}`);
  if (errors.length) { for (const e of errors) console.error(`error: ${e}`); process.exit(1); }
}

if (!existsSync(planPath)) {
  console.error(`No plan at ${relative(process.cwd(), planPath)}. Start from templates/ip-plan.example.json.`);
  process.exit(1);
}
const plan = JSON.parse(readFileSync(planPath, "utf8"));

// ---------------------------------------------------------------- local files only
// Everything renders offline, so every file the plan names must be a relative path to a file
// inside the project (the preview and render servers only serve the project folder), and no
// text that reaches the page may point at the network.
const KINDS = {
  model: [".glb", ".gltf"],
  image: [".png", ".jpg", ".jpeg", ".webp", ".svg"],
  audio: [".wav", ".mp3", ".m4a", ".aac", ".flac", ".ogg"],
};
function localPath(p, where, kind) {
  if (typeof p !== "string" || !p) { fail(`${where} must be a file path.`); return null; }
  if (/^[a-z][a-z0-9+.-]*:/i.test(p) || p.startsWith("//")) { fail(`${where} is a URL (${p}); put the file in the project and use a relative path.`); return null; }
  if (isAbsolute(p)) { fail(`${where} is absolute (${p}); use a path relative to the project.`); return null; }
  const file = resolve(project, p);
  if (file !== project && !file.startsWith(project + sep)) { fail(`${where} points outside the project (${p}).`); return null; }
  if (!existsSync(file) || !statSync(file).isFile()) { fail(`${where}: no file at ${p}`); return null; }
  if (kind && !KINDS[kind].includes(extname(file).toLowerCase())) { fail(`${where}: ${p} is not a ${KINDS[kind].join("/")} file.`); return null; }
  return file;
}
// Decode CSS escapes (\68ttp), line continuations, HTML entities (&#x68; &quot;), and treat a
// backslash as the slash browsers read it as, before looking for URLs, so encoded schemes and
// hosts cannot slip through. The page's Content-Security-Policy blocks remote loads anyway;
// these checks turn them into clear build errors instead of silent refusals.
const decodeCss = t => String(t).replace(/\\\r?\n/g, "").replace(/\\\\/g, "\u0000")
  .replace(/\\([0-9a-f]{1,6})\s?/gi, (_, h) => String.fromCodePoint(parseInt(h, 16))).replace(/\\(.)/g, "$1").replace(/\u0000/g, "\\");
const NAMED = { quot: '"', apos: "'", amp: "&", lt: "<", gt: ">", colon: ":", sol: "/", bsol: "\\", lpar: "(", rpar: ")", period: "." };
const decodeHtml = t => String(t).replace(/&#x([0-9a-f]+);?/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
  .replace(/&#(\d+);?/g, (_, d) => String.fromCodePoint(Number(d))).replace(/&([a-z]+);/gi, (m, n) => NAMED[n.toLowerCase()] ?? m);
const stripComments = t => String(t).replace(/\/\*[\s\S]*?\*\//g, "");
const normalize = t => decodeCss(decodeHtml(stripComments(t))).replace(/\\/g, "/");
// Anything that names a scheme://, a scheme: with no slashes inside a resource string, a
// protocol-relative //host, or @import is remote. data: URIs are fine.
const REMOTE = /[a-z][a-z0-9+.-]*:\/\/|(["'(\s=,]|^)\/\/[^\/\s]|@import/i;
const hasRemote = t => REMOTE.test(normalize(t).replace(/data:[^"')]*/gi, ""));
// Every resource reference in CSS: url(...) arguments and the strings inside image-set().
function cssRefs(css) {
  const t = normalize(css), refs = [];
  for (const m of t.matchAll(/url\(\s*(['"]?)([^'")]*)\1\s*\)/gi)) refs.push(m[2].trim());
  for (const m of t.matchAll(/image-set\(([^)]*(\([^)]*\)[^)]*)*)\)/gi)) for (const q of m[1].matchAll(/(['"])(.*?)\1/g)) refs.push(q[2].trim());
  return refs;
}
const isLocalRef = r => !r || r.startsWith("#") || /^data:/i.test(r);
// Font families: HyperFrames fetches any family that has no @font-face from Google Fonts, so
// every named family must be generic or declared.
const GENERIC = new Set(["serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace",
  "ui-rounded", "math", "emoji", "fangsong", "inherit", "initial", "unset", "revert", "revert-layer"]);
const declaredFamilies = new Set(["ip montserrat", "ip inter"]);
for (const m of normalize(plan.css || "").matchAll(/@font-face\s*{[^}]*font-family\s*:\s*(['"]?)([^;'"}]+)\1/gi)) declaredFamilies.add(m[2].trim().toLowerCase());
// Custom properties declared in plan.css, so font-family: var(--brand) resolves like HyperFrames does.
const customProps = {};
for (const m of normalize(plan.css || "").matchAll(/(--[\w-]+)\s*:\s*([^;}]+)/g)) customProps[m[1]] = m[2].trim();
const resolveVars = (v, depth = 0) => depth > 5 ? v : v.replace(/var\(\s*(--[\w-]+)\s*(?:,\s*([^)]*))?\)/g, (_, n, fb) => resolveVars(customProps[n] ?? fb ?? "", depth + 1));
function undeclaredFamilies(text) {
  const own = {};
  for (const m of normalize(text).matchAll(/(--[\w-]+)\s*:\s*([^;}"'>]+)/g)) own[m[1]] = m[2].trim();
  const saved = { ...customProps };
  Object.assign(customProps, own);
  const t = resolveVars(normalize(text)), bad = [];
  for (const k of Object.keys(own)) if (k in saved) customProps[k] = saved[k]; else delete customProps[k];
  const lists = [...t.matchAll(/font-family\s*[:=]\s*(["']?)([^;}>]+?)\1\s*(?:[;}>/]|$|\s[\w:-]+=)/gim)].map(m => m[2]);
  for (const list of lists) for (const f of list.split(",")) {
    const name = f.trim().replace(/^['"]|['"]$/g, "").trim();
    if (name && !GENERIC.has(name.toLowerCase()) && !declaredFamilies.has(name.toLowerCase())) bad.push(name);
  }
  return [...new Set(bad)];
}
// Colours reach inline styles and three.js, so they must be real colour values: hex of 3, 4, 6,
// or 8 digits, rgb()/hsl(), or a CSS colour name. A typo would otherwise render silently wrong.
const COLOR_NAMES = new Set("aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen transparent currentcolor".split(" "));
const COLOR = { test: v => /^#([0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i.test(v) ||
  /^(rgb|rgba|hsl|hsla)\(\s*[\d.%\s,/-]+\)$/i.test(v) || COLOR_NAMES.has(String(v).toLowerCase()) };

const files = [];
(plan.products || []).forEach((p, i) => p && p.src != null && files.push([p.src, `plan.products[${i}].src`, "model"]));
if (plan.gift && plan.gift.src != null) files.push([plan.gift.src, "plan.gift.src", "model"]);
if (plan.gift && plan.gift.image != null) files.push([plan.gift.image, "plan.gift.image", "image"]);
if (plan.lockup && plan.lockup.mark != null) files.push([plan.lockup.mark, "plan.lockup.mark", "image"]);
if (plan.audio?.music != null) files.push([plan.audio.music, "plan.audio.music", "audio"]);
if (plan.audio?.stinger != null) files.push([plan.audio.stinger, "plan.audio.stinger", "audio"]);
(plan.audio?.sfx || []).forEach((x, i) => x && x.src != null && files.push([x.src, `plan.audio.sfx[${i}].src`, "audio"]));
for (const [p, where, kind] of files) localPath(p, where, kind);

// glTF files can reference external buffers and textures; they must be embedded or local too.
function gltfJson(file) {
  const b = readFileSync(file);
  if (b.toString("ascii", 0, 4) !== "glTF") return JSON.parse(b.toString("utf8"));
  const len = b.readUInt32LE(12);
  return JSON.parse(b.toString("utf8", 20, 20 + len));
}
for (const [p, where, kind] of files) {
  if (kind !== "model") continue;
  const file = resolve(project, p);
  if (!existsSync(file)) continue;
  let j;
  try { j = gltfJson(file); } catch { fail(`${where}: ${p} is not a readable glTF/GLB file.`); continue; }
  for (const r of [...(j.buffers || []), ...(j.images || [])]) {
    if (!r.uri || r.uri.startsWith("data:")) continue;
    if (/^[a-z][a-z0-9+.-]*:|^[\\/]{2}/i.test(r.uri)) { fail(`${where}: ${p} references a remote resource (${r.uri}); embed it or keep it next to the model.`); continue; }
    let rel;
    try { rel = decodeURIComponent(r.uri); } catch { fail(`${where}: ${p} has a malformed resource URI (${r.uri}).`); continue; }
    localPath(join(dirname(p), rel), `${where} -> ${r.uri}`);
  }
  // three's GLTFLoader needs a decoder for these even when they are only "used", and the kit ships none.
  const need = [...(j.extensionsRequired || []).filter(e => /draco|meshopt|basisu|ktx2/i.test(e)),
    ...(j.extensionsUsed || []).filter(e => /draco/i.test(e))];
  if (need.length) fail(`${where}: ${p} uses ${[...new Set(need)].join(", ")}, which needs a decoder this offline kit does not ship. Export it without mesh or texture compression.`);
}

if (plan.css != null) {
  if (typeof plan.css !== "string") fail("plan.css must be a string of CSS.");
  // The CSS sits inside a <style> element: no markup, so it can never close the element.
  else if (/</.test(plan.css)) fail("plan.css may not contain '<'.");
  else {
    if (hasRemote(plan.css)) fail("plan.css references a remote resource (a URL, //host, or @import); use fonts and images inside the project.");
    for (const r of cssRefs(plan.css)) {
      if (isLocalRef(r)) continue;
      let rel = r.split(/[?#]/)[0];
      try { rel = decodeURIComponent(rel); } catch {}
      localPath(rel, `plan.css reference ${r}`);
    }
    const bad = undeclaredFamilies(plan.css);
    if (bad.length) fail(`plan.css names font families with no @font-face in plan.css (${bad.join(", ")}). HyperFrames would fetch them from Google Fonts; declare them with a local file or use "IP Montserrat" / "IP Inter".`);
  }
}
done();

// ---------------------------------------------------------------- helpers
const r2 = n => Math.round(n * 100) / 100;
const r3 = n => Math.round(n * 1000) / 1000;
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const key = (t, v, e) => (e ? { t: r3(t), v: r3(v), e } : { t: r3(t), v: r3(v) });
const num = v => typeof v === "number" && Number.isFinite(v);
// Project-relative file paths as URLs: '#', '?', and spaces in names must not break the request.
const href = p => String(p).split("/").map(encodeURIComponent).join("/");

function probeAudio(file) {
  const r = spawnSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file], { encoding: "utf8" });
  const d = r.status === 0 ? Number(r.stdout.trim()) : NaN;
  if (!(d > 0)) { fail(`${relative(project, file)} has no playable audio (ffprobe reports no duration).`); done(); }
  return d;
}
function pngSize(file) {
  const fd = openSync(file, "r"), b = Buffer.alloc(24);
  readSync(fd, b, 0, 24, 0);
  closeSync(fd);
  if (b.toString("ascii", 12, 16) !== "IHDR") return null;
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

// Text measurement with the bundled fonts (fontkit ships with HyperFrames). Falls back to an
// average advance of 0.6 em when fontkit is unavailable.
let fontkit = null;
try { fontkit = require("fontkit"); } catch { warn("fontkit not found; line widths are estimated."); }
const FONTS = {
  montserrat: join(SKILL, "assets/fonts/Montserrat-Latin-VF.ttf"),
  inter: join(SKILL, "assets/fonts/Inter-Latin-VF.ttf"),
};
const fontCache = {};
function font(name) {
  if (!fontkit) return null;
  return (fontCache[name] ||= fontkit.openSync(FONTS[name]));
}
function measure(text, size, weight, name = "montserrat", tracking = 0) {
  const f = font(name);
  if (!f) return { width: String(text).length * size * 0.6, ascent: 0.968, descent: 0.251 };
  const v = f.getVariation({ wght: weight });
  const run = v.layout(String(text));
  const width = (run.advanceWidth / f.unitsPerEm) * size + tracking * size * Math.max(0, String(text).length - 1);
  return { width, ascent: f.ascent / f.unitsPerEm, descent: -f.descent / f.unitsPerEm };
}

// ---------------------------------------------------------------- format and timing
const FORMATS = { landscape: [1920, 1080], portrait: [1080, 1920] };
const format = plan.format || "landscape";
if (!FORMATS[format]) fail(`format must be one of ${Object.keys(FORMATS).join(", ")}.`);
const fps = plan.fps ?? 60;
if (!Number.isInteger(fps) || fps < 1 || fps > 240) fail("fps must be a whole number from 1 to 240 (HyperFrames renders integer frame rates).");
done();
const [W, H] = FORMATS[format];

// Reference values (60 fps, 1920x1080 After Effects comp). See references/reference-breakdown.md.
// The hold is 1.333 s so the mirror lands on the reference's 5.70 s.
const T = {
  products: { at: 0, duration: 1.667, ease: [0.34, 0, 0.03, 1], spin: 360, stagger: 0 },
  copy: { at: -0.196, duration: 1.667, ease: [0.69, 0, 0.1, 1], stagger: 0.0833, fadeDelay: 0.033, fadeDuration: 0.333 },
  pill: { at: 1.074, duration: 0.491, ease: [0.31, 0, 0.68, 1] },
  card: { at: 1.1, peak: 1.149, up: 0.5, down: 0.5, upEase: [0.33, 0, 0, 1], downEase: [1, 0, 0.66, 1] },
  gift: { delay: 0.0833, spin: 360, spinDuration: 0.8 },
  hold: 1.333,
  lockup: { popLead: 0.337, popDuration: 0.519, bounce: [0.154, 2.08], slideDelay: 0.609, slideDuration: 0.826,
    markEase: [0.33, 0, 0, 1], wordEase: [0.35, 0, 0, 1], tail: 1.2 },
};
function merge(a, b) {
  for (const [k, v] of Object.entries(b || {})) {
    if (Array.isArray(v) && v.length && Array.isArray(a[k]) && v.every(x => x && typeof x === "object" && !Array.isArray(x)))
      // Slot lists merge element by element; preset slots beyond the override stay.
      a[k] = Array.from({ length: Math.max(v.length, a[k].length) }, (_, i) => merge({ ...(a[k][i] || {}) }, v[i] || {}));
    else a[k] = v && typeof v === "object" && !Array.isArray(v) ? merge(a[k] || {}, v) : v;
  }
  return a;
}
merge(T, plan.timing);
if (plan.hold != null) T.hold = plan.hold;
if (!num(T.hold) || T.hold < 0) fail("hold must be a number of seconds, 0 or more.");
// Every timing value must be a finite number (durations positive) and every ease four numbers.
(function checkTiming(o, path) {
  for (const [k, v] of Object.entries(o)) {
    const at = `${path}.${k}`;
    if (/ease$|Ease$/.test(k)) { if (!(Array.isArray(v) && v.length === 4 && v.every(num))) fail(`${at} must be four numbers, like a CSS cubic-bezier.`); }
    else if (k === "bounce") { if (!(Array.isArray(v) && v.length === 2 && v.every(x => num(x) && x > 0))) fail(`${at} must be [restitution, power], two positive numbers.`); }
    else if (v && typeof v === "object") checkTiming(v, at);
    else if (!num(v)) fail(`${at} must be a number.`);
    else if (/duration|Duration|^up$|^down$|^tail$|^peak$/.test(k) && v <= 0) fail(`${at} must be greater than 0.`);
  }
})(T, "timing");
done();

// ---------------------------------------------------------------- palette and finishes
const palette = {
  background: "#ffffff", ink: "#000000", tagline: "#cc7958", highlight: "#67e172", priceInk: "#ffffff",
  card: "rgba(0,0,0,0.25)", mark: "#1d1d1f", word: "#1d1d1f", ...(plan.palette || {}),
};
for (const [k, v] of Object.entries(palette)) if (!COLOR.test(String(v).trim()) || hasRemote(v)) fail(`palette.${k} must be a colour (hex, rgb(), hsl(), or a name), not ${JSON.stringify(v)}.`);
// The audit measures blank frames against the stage colour, so it must be hex or rgb().
if (!/^(#[0-9a-f]{3}|#[0-9a-f]{6}|rgba?\([^)]*\))$/i.test(String(palette.background).trim())) fail("palette.background must be a hex (#fff, #ffffff) or rgb() colour.");
const FINISHES = {
  orange: { body: "#d9601a", plateau: "#e27424", plateauRoughness: 0.36, glass: "#ffc24e", glassRoughness: 0.45, screen: "#ff7a26", ring: "#e67a38" },
  silver: { body: "#b4b4b2", plateau: "#a6a6a5", glass: "#9e9ea0", screen: "#8fa3c4", ring: "#c4c4c2" },
  blue: { body: "#2c3a55", plateau: "#34435f", glass: "#4a5a78", screen: "#4f7ad6", ring: "#3b4a68" },
  graphite: { body: "#3a3a3c", plateau: "#434345", glass: "#505052", screen: "#8a8f99", ring: "#4a4a4c" },
};
function finish(f) {
  if (!f) return FINISHES.orange;
  if (typeof f === "string") {
    if (!FINISHES[f]) { fail(`Unknown finish "${f}". Use ${Object.keys(FINISHES).join(", ")} or an object.`); return FINISHES.orange; }
    return FINISHES[f];
  }
  if (typeof f !== "object") { fail("finish must be a preset name or an object of colours."); return FINISHES.orange; }
  for (const [k, v] of Object.entries(f)) {
    if (/roughness|metalness/i.test(k)) { if (!(num(v) && v >= 0 && v <= 1)) fail(`finish.${k} must be a number from 0 to 1.`); }
    else if (!COLOR.test(String(v).trim())) fail(`finish.${k} must be a colour (hex, rgb(), or a name), not ${JSON.stringify(v)}.`);
  }
  return { ...FINISHES.orange, ...f };
}

// ---------------------------------------------------------------- layout presets
// Landscape reproduces the reference frame: a centred copy stack in the left column, the two
// products on the right. Portrait stacks the copy on top and the products underneath.
const L = format === "landscape"
  ? { scale: 1, cx: 570, stackCenter: 540, maxWidth: 840,
      products: [
        { x: 1221, y: 504, h: 785, z: 0, rx: -3, ry: 30, rz: -1, from: "bottom" },
        { x: 1545, y: 601, h: 770, z: -260, rx: -3, ry: 36, rz: 1, from: "top" },
      ],
      single: { x: 1380, y: 540, h: 820, z: 0, rx: -3, ry: 30, rz: 0, from: "bottom" },
      card: { w: 258, h: 310, radius: 14 } }
  : { scale: 1.2, cx: 540, stackCenter: 560, maxWidth: 940,
      products: [
        { x: 420, y: 1440, h: 760, z: 0, rx: -3, ry: 30, rz: -1, from: "bottom" },
        { x: 700, y: 1500, h: 745, z: -260, rx: -3, ry: 36, rz: 1, from: "top" },
      ],
      single: { x: 540, y: 1460, h: 800, z: 0, rx: -3, ry: 30, rz: 0, from: "bottom" },
      card: { w: 232, h: 270, radius: 14 } };
merge(L, plan.layout);

// Role defaults at the reference size (1080 px tall).
const ROLES = {
  title: { size: 78.3, weight: 700 },
  tagline: { size: 47.6, weight: 500 },
  line: { size: 56.5, weight: 700 },
  price: { size: 56.5, weight: 700 },
};
// Baseline-to-baseline distances measured in the reference, keyed "previous>current".
const ADVANCE = {
  "title>tagline": 72, "tagline>line": 78, "line>price": 67, "price>line": 69, "line>line": 63,
  "title>line": 82, "title>price": 84, "tagline>price": 76, "tagline>tagline": 60, "line>tagline": 68,
  "price>tagline": 68, "price>price": 74,
};

// ---------------------------------------------------------------- copy stack
const copy = (plan.copy || []).map(c => (typeof c === "string" ? { text: c } : { ...c })).map((c, i) => {
  c.role = c.role || (i === 0 ? "title" : "line");
  if (!ROLES[c.role]) { fail(`copy[${i}]: role must be title, tagline, line, or price.`); c.role = "line"; }
  if (typeof c.text !== "string" || !c.text.trim()) fail(`copy[${i}] needs text.`);
  if (c.color != null && (!COLOR.test(String(c.color).trim()) || hasRemote(c.color))) fail(`copy[${i}].color must be a colour value.`);
  if (c.weight != null && !(num(c.weight) && c.weight >= 100 && c.weight <= 900)) fail(`copy[${i}].weight must be a number from 100 to 900.`);
  if (c.size != null && !(num(c.size) && c.size > 0)) fail(`copy[${i}].size must be a positive number.`);
  return c;
});
if (!copy.length) fail("plan.copy needs at least one line (the product name).");
if (copy.filter(c => c.role === "price").length > 1) fail("Only one copy line can be the price.");
done();

let baseline = 0;
copy.forEach((c, i) => {
  const role = ROLES[c.role];
  // `size` is at the 1080p reference and scales with the layout; `advance` is canvas pixels.
  c.size = r2((c.size || role.size) * L.scale);
  c.weight = c.weight || role.weight;
  let m = measure(c.text, c.size, c.weight);
  const limit = c.role === "price" ? L.maxWidth - 2 * 0.9 * c.size : L.maxWidth;
  if (m.width > limit) {
    const s2 = r2(c.size * limit / m.width);
    warn(`"${c.text}" is ${Math.round(m.width)} px wide; shrinking it from ${c.size} to ${s2} px. Shorten it for the reference look.`);
    c.size = s2;
    m = measure(c.text, c.size, c.weight);
  }
  c.width = m.width;
  c.ascent = m.ascent;
  c.descent = m.descent;
  if (i) {
    const prev = copy[i - 1];
    const base = ADVANCE[`${prev.role}>${c.role}`] ?? 1.15 * Math.max(prev.size, c.size) / L.scale;
    baseline += num(c.advance) ? c.advance : base * (c.size / ROLES[c.role].size);
  }
  c.baseline = baseline;
});
const giftSpec = plan.gift === undefined ? { model: "case" } : plan.gift;
if (giftSpec && !giftSpec.image && !giftSpec.src && giftSpec.model !== "case")
  fail(`plan.gift must be { "model": "case" }, { "image": "<png>" }, { "src": "<glb>" }, or null.`);
if (giftSpec && giftSpec.finish != null) finish(giftSpec.finish);
const card = giftSpec ? { ...L.card } : null;
if (card) for (const k of ["w", "h", "radius"]) if (!(num(card[k]) && card[k] >= 0 && (k === "radius" || card[k] > 0))) fail(`layout.card.${k} must be a positive number of pixels.`);
for (const k of ["scale", "cx", "stackCenter", "maxWidth"]) if (!(num(L[k]) && (k === "cx" || k === "stackCenter" || L[k] > 0))) fail(`layout.${k} must be a number.`);
done();
const last = copy[copy.length - 1];
let stackTop = copy[0].baseline - copy[0].size * 0.8;
let stackBottom = card ? last.baseline + 36 * L.scale + card.h : last.baseline + last.size * last.descent;
const shift = L.stackCenter - (stackTop + stackBottom) / 2;
for (const c of copy) c.baseline = r2(c.baseline + shift);
if (card) {
  card.x = L.cx;
  card.top = r2(last.baseline + 36 * L.scale);
  card.y = r2(card.top + card.h / 2);
}
stackTop += shift;
stackBottom += shift;
if (stackTop < 40 || stackBottom > H - 40) warn(`The copy stack spans ${Math.round(stackTop)}-${Math.round(stackBottom)} px; trim lines or lower sizes.`);

// ---------------------------------------------------------------- products
const products = (plan.products || [{ model: "phone", finish: "orange" }, { model: "phone", finish: "silver" }]).map(p => ({ ...p }));
if (products.length < 1 || products.length > 2) fail("plan.products needs one or two products (the reference pairs two).");
done();
products.forEach((p, i) => {
  const slot = products.length === 1 ? L.single : L.products[i];
  Object.assign(p, { ...slot, ...p, ...(p.layout || {}) });
  p.at = r3((p.at ?? T.products.at) + i * T.products.stagger);
  for (const k of ["x", "y", "h"]) if (!num(p[k])) fail(`products[${i}].${k} must be a number (check layout.products).`);
  if (p.from !== "top" && p.from !== "bottom") fail(`products[${i}].from must be "top" or "bottom".`);
  if (!p.src && (p.model || "phone") !== "phone") fail(`products[${i}]: model must be "phone" or use src for a GLB file.`);
});
done();

// ---------------------------------------------------------------- timings
const slides = copy.filter(c => c.role !== "price");
slides.forEach((c, i) => { c.at = r3(T.copy.at + i * T.copy.stagger); });
const maxRight = Math.max(...copy.map(c => L.cx + c.width / 2));
const copyDx = -(maxRight + 0.36 * W);
const giftAt = T.card.at + T.gift.delay;

const entranceEnd = Math.max(
  ...products.map(p => p.at + T.products.duration),
  ...slides.map(c => c.at + T.copy.duration),
  copy.some(c => c.role === "price") ? T.pill.at + T.pill.duration : 0,
  card ? T.card.at + T.card.up + T.card.down : 0,
  card ? giftAt + T.card.up + T.card.down : 0,
  card && (giftSpec.model || giftSpec.src) ? giftAt + T.gift.spinDuration : 0,
);
// The mirror sits on a whole frame so frame n of the exit is exactly frame (mirror - n).
const mirror = plan.exit === false ? null : Math.round((2 * entranceEnd + T.hold) * fps) / fps;
const noLockup = plan.lockup === false || plan.lockup === null;
if (plan.exit === false && plan.lockup != null && !noLockup)
  fail(`"exit": false keeps the layout on screen, so the lockup would pop on top of it. Remove "lockup" (or set it to false).`);
const lockup = noLockup || plan.exit === false ? null : { wordmark: "", ...(plan.lockup || {}) };

// The first moment anything is on screen: a product's leading edge crossing the frame edge. The
// mirrored exit is empty again from mirror - firstInk.
function bezierAt(e, p) {
  const [x1, y1, x2, y2] = e;
  let lo = 0, hi = 1, s = p;
  for (let i = 0; i < 48; i++) {
    const x = 3 * (1 - s) ** 2 * s * x1 + 3 * (1 - s) * s * s * x2 + s ** 3;
    if (x < p) lo = s; else hi = s;
    s = (lo + hi) / 2;
  }
  return 3 * (1 - s) ** 2 * s * y1 + 3 * (1 - s) * s * s * y2 + s ** 3;
}
const firstInk = Math.min(...products.map(p => {
  // The leading edge enters once the eased travel covers the start margin: E(t) >= margin / travel.
  const margin = (p.from === "top" ? 0.206 : 0.161) * H;
  const startY = p.from === "top" ? -(p.h / 2 + margin) : H + p.h / 2 + margin;
  const need = margin / Math.abs(p.y - startY);
  for (let t = 0; t <= T.products.duration; t += 1 / 480)
    if (bezierAt(T.products.ease, t / T.products.duration) >= need) return p.at + t - 0.5 / fps; // motion blur leads by half a frame
  return p.at;
}), ...(card ? [T.card.at, giftAt] : []), ...(copy.some(c => c.role === "price") ? [T.pill.at] : []), ...slides.map(c => {
  // A line shows once its right edge crosses x = 0: E(t) >= 1 - rightEdge / |copyDx|.
  const need = 1 - (L.cx + c.width / 2) / Math.abs(copyDx);
  for (let t = 0; t <= T.copy.duration; t += 1 / 480)
    if (bezierAt(T.copy.ease, t / T.copy.duration) >= need) return c.at + t - 0.5 / fps;
  return c.at + T.copy.duration;
}));
// Two frames of margin for the faint motion-blur tail of the last product leaving.
const exitClear = mirror != null ? r3(mirror - firstInk + 2 / fps) : null;
const popAt = lockup ? r3(mirror - T.lockup.popLead) : null;
const slideAt = lockup ? r3(popAt + T.lockup.slideDelay) : null;
const slideEnd = lockup ? r3(slideAt + T.lockup.slideDuration) : null;
// Every spot ends on at least 0.5 s of stillness: the lockup, the empty stage after the exit, or
// the held layout when there is no exit.
const minDuration = r3(lockup ? slideEnd + 0.5 : mirror != null ? exitClear + 0.5 : entranceEnd + 0.5);
const autoDuration = r3(lockup ? slideEnd + T.lockup.tail : mirror != null ? exitClear + 0.5 : entranceEnd + T.hold);
if (plan.duration == null && autoDuration < minDuration)
  fail(lockup ? `timing.lockup.tail must be at least 0.5 s (the end card holds still).` : `hold must be at least 0.5 s when "exit" is false (the layout holds still at the end).`);
if (!lockup && mirror != null && num(plan.duration) && plan.duration > exitClear + 1.5)
  warn(`duration ${plan.duration}s leaves ${r3(plan.duration - exitClear)}s of empty stage after the exit; the style ends 0.5 s after it.`);
if (plan.duration != null && !(num(plan.duration) && plan.duration >= minDuration))
  fail(`duration ${JSON.stringify(plan.duration)} is too short: ${lockup ? `the lockup slide ends at ${slideEnd}s` : mirror != null ? `the exit clears at ${exitClear}s` : `the layout settles at ${r3(entranceEnd)}s`} and the spot needs 0.5 s of stillness after that (at least ${minDuration}s).`);
done();
// Whole frames, so the render's frame count is exactly duration x fps. HyperFrames renders
// ceil(duration x fps) frames, so the value is written just below the exact quotient.
const frameCount = Math.round((plan.duration ?? autoDuration) * fps);
const duration = Math.floor((frameCount / fps) * 1e4) / 1e4;

// ---------------------------------------------------------------- DOM layers
const layers = [];
const html = [];
const filters = [];
const blurFilter = id => filters.push(`<filter id="${id}-mb" x="-0.4" y="-0.4" width="1.8" height="1.8" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="0 0"/></filter>`);

const boxW = Math.round(L.maxWidth + 200);
copy.forEach((c, i) => {
  const id = `ip-copy-${i + 1}`;
  c.id = id;
  const top = r2(c.baseline - c.size * (0.5 + (c.ascent - c.descent) / 2));
  const left = r2(L.cx - boxW / 2);
  const cls = ["ip-line", c.role];
  if (c.role === "price") {
    // The highlight: a round-capped stroke drawn left to right behind white text.
    const pad = 0.9 * c.size;
    const sw = r2(1.168 * c.size);
    const cy = r2(c.baseline - 0.346 * c.size);
    const x1 = r2(L.cx - c.width / 2 - pad + sw / 2), x2 = r2(L.cx + c.width / 2 + pad - sw / 2);
    html.push(`    <svg class="ip-pill" id="ip-pill" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><path id="ip-pill-path" d="M ${x1} ${cy} L ${x2} ${cy}" stroke-width="${sw}"/></svg>`);
    layers.push({ id: "ip-pill-path", mirror: true, draw: [key(T.pill.at, 0), key(T.pill.at + T.pill.duration, 1, T.pill.ease)] });
    html.push(`    <div class="${cls.join(" ")}" id="${id}" style="left:${left}px;top:${top}px;width:${boxW}px;font-size:${c.size}px;font-weight:${c.weight}">${esc(c.text)}</div>`);
    layers.push({ id, mirror: true, revealBy: { layer: "ip-pill-path", a: r2(x1 - sw / 2 - left), b0: r2(x1 + sw / 2 - left), span: r2(x2 - x1) } });
    return;
  }
  html.push(`    <div class="${cls.join(" ")}" id="${id}" style="left:${left}px;top:${top}px;width:${boxW}px;font-size:${c.size}px;font-weight:${c.weight}${c.color ? `;color:${esc(c.color)}` : ""}">${esc(c.text)}</div>`);
  blurFilter(id);
  layers.push({
    id, mirror: true, blur: { amount: 1 },
    x: [key(c.at, copyDx), key(c.at + T.copy.duration, 0, T.copy.ease)],
    opacity: [key(c.at + T.copy.fadeDelay, 0), key(c.at + T.copy.fadeDelay + T.copy.fadeDuration, 1, [0.33, 0, 0.67, 1])],
  });
});

const cardScale = at => [key(at, 0), key(at + T.card.up, T.card.peak, T.card.upEase), key(at + T.card.up + T.card.down, 1, T.card.downEase)];
let gift3d = null;
if (card) {
  html.push(`    <div class="ip-card" id="ip-card" style="left:${r2(card.x - card.w / 2)}px;top:${r2(card.y - card.h / 2)}px;width:${card.w}px;height:${card.h}px;border-radius:${card.radius}px"></div>`);
  blurFilter("ip-card");
  layers.push({ id: "ip-card", mirror: true, scale: cardScale(T.card.at), blur: { w: card.w, h: card.h } });
  if (giftSpec.image) {
    const gw = r2(card.w * 0.86), gh = r2(card.h * 0.8);
    html.push(`    <img class="ip-gift-img" id="ip-gift" src="${esc(href(giftSpec.image))}" alt="" style="left:${r2(card.x - gw / 2)}px;top:${r2(card.y - gh / 2)}px;width:${gw}px;height:${gh}px">`);
    blurFilter("ip-gift");
    layers.push({ id: "ip-gift", mirror: true, scale: cardScale(giftAt), blur: { w: gw, h: gh } });
  } else {
    const h = r2(card.h * (giftSpec.src ? 0.72 : 0.62));
    gift3d = {
      kind: giftSpec.src ? "model" : "case", src: giftSpec.src && href(giftSpec.src), orient: giftSpec.orient, finish: giftSpec.finish, h,
      x: [key(0, card.x)], y: [key(0, card.y)], z: [key(0, 120)],
      rx: [key(0, giftSpec.rx ?? 16)], rz: [key(0, 0)],
      ry: [key(giftAt, (giftSpec.ry ?? -20) - T.gift.spin), key(giftAt + T.gift.spinDuration, giftSpec.ry ?? -20, T.products.ease)],
      scale: cardScale(giftAt),
    };
  }
}

// Products: screen-space centre (x, y) and height h at rest; they fly in from beyond the top or
// bottom edge while spinning a full turn about their long axis.
const products3d = products.map(p => {
  const margin = (p.from === "top" ? 0.206 : 0.161) * H;
  const startY = p.from === "top" ? -(p.h / 2 + margin) : H + p.h / 2 + margin;
  // Both products spin the same way and arrive with the power-button edge turned toward camera.
  const end = p.at + T.products.duration;
  return {
    kind: "phone", src: p.src && href(p.src), orient: p.orient, finish: finish(p.finish), h: p.h,
    x: [key(0, p.x)], z: [key(0, p.z || 0)], rx: [key(0, p.rx ?? 0)], rz: [key(0, p.rz ?? 0)],
    y: [key(p.at, startY), key(end, p.y, T.products.ease)],
    ry: [key(p.at, (p.ry ?? 0) + (p.spin ?? T.products.spin)), key(end, p.ry ?? 0, T.products.ease)],
  };
});

// ---------------------------------------------------------------- lockup
// The mark is painted after the wordmark so it covers the word while the word slides out from
// behind it; a clip hides the word left of the mark's centre.
const lockupHtml = [];
if (lockup) {
  for (const k of ["markHeight", "wordSize"]) if (lockup[k] != null && !(num(lockup[k]) && lockup[k] > 0)) fail(`lockup.${k} must be a positive number of pixels.`);
  if (typeof lockup.wordmark !== "string") fail("lockup.wordmark must be text (use \"\" for a mark-only end card).");
  let markH = r2(num(lockup.markHeight) ? lockup.markHeight : 137 * (format === "portrait" ? 1.25 : 1));
  const offsetX = lockup.offsetX ?? 0;
  if (!num(offsetX) || Math.abs(offsetX) > 0.3 * W) fail(`lockup.offsetX must be a number of pixels within ±${Math.round(0.3 * W)}.`);
  if (lockup.markAspect != null && !(num(lockup.markAspect) && lockup.markAspect > 0)) fail("lockup.markAspect must be a positive number (width / height).");
  let aspect = 0.86, markHtml;
  if (lockup.mark) {
    const file = resolve(project, lockup.mark);
    const ext = extname(file).toLowerCase();
    if (ext === ".svg") {
      // Inline the SVG only if it is plain vector artwork. Editor metadata is dropped; anything
      // that can load or run something (scripts, handlers, foreignObject, external references,
      // undeclared fonts) is refused with the reason.
      let svg = readFileSync(file, "utf8").replace(/<\?xml[\s\S]*?\?>/gi, "").replace(/<!DOCTYPE[^[>]*(\[[\s\S]*?\])?\s*>/gi, "")
        .replace(/<!--[\s\S]*?-->/g, "").replace(/<metadata\b[\s\S]*?<\/metadata>/gi, "").replace(/<metadata\b[^>]*\/>/gi, "")
        .replace(/<([a-z][\w.-]*):([\w.-]+)\b[^>]*\/>/gi, "").replace(/<([a-z][\w.-]*):([\w.-]+)\b[^>]*>[\s\S]*?<\/\1:\2>/gi, "").trim();
      const SAFE = new Set(["svg", "g", "path", "rect", "circle", "ellipse", "line", "polyline", "polygon", "defs", "lineargradient",
        "radialgradient", "stop", "clippath", "mask", "use", "symbol", "title", "desc", "text", "tspan", "image", "pattern", "style",
        "a", "switch", "filter", "fegaussianblur", "feoffset", "feflood", "fecomposite", "femerge", "femergenode", "fecolormatrix", "feblend"]);
      const tags = [...new Set([...svg.matchAll(/<([a-z][\w:.-]*)/gi)].map(m => m[1].toLowerCase()))];
      const unsafe = tags.filter(t => !SAFE.has(t));
      const reasons = [];
      if (unsafe.length) reasons.push(`elements <${unsafe.join(">, <")}>`);
      if ([svg, decodeHtml(svg)].some(t => /[\s"'\/]on[a-z]+\s*=/i.test(t))) reasons.push("event-handler attributes (on...)");
      if (/javascript:/i.test(normalize(svg))) reasons.push("javascript: URLs");
      // Hyperlinks load nothing; drop their targets. Every other reference must be #id or data:.
      svg = svg.replace(/(<a\b[^>]*?)\s(?:xlink:)?href\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "$1");
      const refs = [...decodeHtml(svg).matchAll(/\s(?:xlink:)?(?:href|src)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi)].map(m => (m[1] ?? m[2] ?? m[3]).trim());
      const bad = [...refs, ...cssRefs(svg)].filter(r => !isLocalRef(r));
      if (bad.length) reasons.push(`references ${[...new Set(bad)].slice(0, 3).join(", ")}`);
      if (hasRemote(svg.replace(/\s(?:xmlns(?::[\w-]+)?|version|baseProfile)\s*=\s*("[^"]*"|'[^']*')/gi, ""))) reasons.push("remote URLs or @import in its styles");
      const fonts = undeclaredFamilies(svg);
      if (fonts.length) reasons.push(`font families with no @font-face (${fonts.join(", ")}); convert text to outlines`);
      if (reasons.length) fail(`lockup.mark ${lockup.mark} is not a plain vector logo: ${reasons.join("; ")}. Export it again as flat SVG artwork.`);
      const open = svg.match(/<svg\b[^>]*>/i)?.[0] || "";
      const vb = open.match(/\sviewBox\s*=\s*["']\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)/i);
      const dim = a => Number((open.match(new RegExp(`\\s${a}\\s*=\\s*["']\\s*([\\d.]+)(px)?\\s*["']`, "i")) || [])[1]);
      if (vb) aspect = Number(vb[1]) / Number(vb[2]);
      else if (dim("width") && dim("height")) {
        aspect = dim("width") / dim("height");
        svg = svg.replace(/<svg\b/i, `<svg viewBox="0 0 ${dim("width")} ${dim("height")}"`);
      } else fail(`lockup.mark ${lockup.mark} has neither a viewBox nor numeric width and height.`);
      if (num(lockup.markAspect)) aspect = lockup.markAspect;
      markHtml = svg;
    } else {
      const size = ext === ".png" ? pngSize(file) : null;
      if (num(lockup.markAspect)) aspect = lockup.markAspect;
      else if (size) aspect = size.w / size.h;
      else fail(`lockup.mark ${lockup.mark}: set "markAspect" (width / height) for non-PNG images.`);
      markHtml = `<img src="${esc(href(lockup.mark))}" alt="">`;
    }
  } else {
    // Placeholder monogram; replace it with the brand's own mark (never a third-party logo).
    const letter = esc((lockup.wordmark || "N").trim()[0] || "N");
    markHtml = `<svg viewBox="0 0 86 100"><rect x="0" y="7" width="86" height="86" rx="24" fill="currentColor"/><text x="43" y="66" text-anchor="middle" font-family="IP Inter, sans-serif" font-weight="700" font-size="52" fill="#fff">${letter}</text></svg>`;
  }
  done();
  // Spacing follows the mark's height, as in the reference (a 34 px gap beside a 137 px mark), so
  // wide logos keep a tight lockup.
  let wordSize = r2(num(lockup.wordSize) ? lockup.wordSize : markH * 0.7);
  const gapOf = h => h * 0.248;
  let markW = markH * aspect;
  let wm = measure(lockup.wordmark, wordSize, 600, "inter", -0.015);
  let total = lockup.wordmark ? markW + gapOf(markH) + wm.width : markW;
  const maxTotal = 0.86 * W - 2 * Math.abs(offsetX);
  if (total > maxTotal) {
    const k = maxTotal / total;
    warn(`The lockup is ${Math.round(total)} px wide; scaling the mark and wordmark by ${k.toFixed(2)} to fit the frame.`);
    markH = r2(markH * k); wordSize = r2(wordSize * k); markW = markH * aspect;
    wm = measure(lockup.wordmark, wordSize, 600, "inter", -0.015);
    total = lockup.wordmark ? markW + gapOf(markH) + wm.width : markW;
  }
  markW = r2(markW);
  const gap = r2(gapOf(markH));
  const cy = r2(H / 2 - 0.012 * H);
  // With a wordmark the mark pops at the frame centre and slides; alone it pops where it rests.
  const markCx0 = lockup.wordmark ? W / 2 : W / 2 + offsetX;
  const markLeft = r2(markCx0 - markW / 2);
  const finalMarkLeft = r2(W / 2 - total / 2 + offsetX);
  const markDx = r2(finalMarkLeft - markLeft);
  const wordLeft = r2(finalMarkLeft + markW + gap);
  const wordTop = r2(cy + 0.354 * markH - wordSize * (0.5 + (wm.ascent - wm.descent) / 2));
  if (lockup.wordmark) {
    // The word is clipped left of the mark's right edge, so it only ever appears beside the mark
    // (hollow and outline logos never show it through). It starts fully behind that edge; the
    // reference word travels its own width plus 0.296 mark heights while the mark moves the
    // other way.
    const clipEdge = r2(markCx0 + markW / 2);
    const wordDx = -r2(Math.max(wm.width + 0.296 * markH, wordLeft + wm.width - clipEdge + 2));
    lockupHtml.push(`    <div class="ip-word" id="ip-word" style="left:${wordLeft}px;top:${wordTop}px;font-size:${wordSize}px">${esc(lockup.wordmark)}</div>`);
    blurFilter("ip-word");
    layers.push({
      id: "ip-word", mirror: false, blur: { amount: 1 }, left: wordLeft,
      x: [key(slideAt, wordDx), key(slideEnd, 0, T.lockup.wordEase)],
      clipTo: { layer: "ip-mark", edge: clipEdge },
    });
  }
  lockupHtml.push(`    <div class="ip-mark" id="ip-mark" style="left:${markLeft}px;top:${r2(cy - markH / 2)}px;width:${markW}px;height:${markH}px">${markHtml}</div>`);
  blurFilter("ip-mark");
  layers.push({
    id: "ip-mark", mirror: false, blur: { w: markW, h: markH },
    scale: [key(popAt, 0), key(popAt + T.lockup.popDuration, 1, { bounce: T.lockup.bounce })],
    ...(lockup.wordmark ? { x: [key(slideAt, 0), key(slideEnd, markDx, T.lockup.markEase)] } : {}),
  });
}

// ---------------------------------------------------------------- audio
const audio = [];
const audioDir = join(project, "ip/audio");
// Trimmed, faded copies in ip/audio/: `start` skips into the file (an intro, or silence before
// a hit), `length` keeps that many seconds, and `fade` ramps the end out. `loudness` then sets
// one static gain toward `I` LUFS and runs a lookahead limiter whose ceiling is `ceiling` dBFS.
// Downloaded masters are often brick-walled near 0 dBFS, and HyperFrames' 188 kbps AAC encode
// overshoots such transients by up to 4 dB; a sub-bass high-pass and a ceiling well below full
// scale keep the delivered true peak under -1 dBTP. The limiter only touches isolated peaks.
function loudnessOf(file) {
  const r = spawnSync("ffmpeg", ["-hide_banner", "-nostats", "-i", file, "-af", "ebur128=peak=true", "-f", "null", "-"], { encoding: "utf8" });
  const I = Number((r.stderr.match(/I:\s+(-?[\d.]+) LUFS/g) || []).pop()?.match(/-?[\d.]+/)[0]);
  const TP = Number((r.stderr.match(/Peak:\s+(-?[\d.]+) dBFS/g) || []).pop()?.match(/-?[\d.]+/)[0]);
  return { I, TP };
}
function prepAudio(src, name, { start = 0, length = null, fade = 0, loudness = null } = {}) {
  const file = resolve(project, src);
  mkdirSync(audioDir, { recursive: true });
  const out = join(audioDir, name);
  const af = [`atrim=start=${start}${length != null ? `:end=${r3(start + length)}` : ""}`, "asetpts=PTS-STARTPTS"];
  if (length != null && fade > 0) af.push(`afade=t=out:st=${r3(Math.max(0, length - fade))}:d=${fade}`);
  const r = spawnSync("ffmpeg", ["-v", "error", "-y", "-i", file, "-af", af.join(","), "-ar", "48000", "-ac", "2", "-c:a", "pcm_f32le", out], { encoding: "utf8" });
  if (r.status !== 0) { fail(`ffmpeg could not prepare ${src}: ${r.stderr}`); return null; }
  let gain = 0;
  if (loudness) {
    const limit = (10 ** (loudness.ceiling / 20)).toFixed(4);
    const tmp = out.replace(/\.wav$/, ".tmp.wav");
    const level = g => spawnSync("ffmpeg", ["-v", "error", "-y", "-i", out, "-af",
      `highpass=f=25,volume=${g}dB,alimiter=limit=${limit}:attack=5:release=60:level=disabled`, "-c:a", "pcm_s24le", tmp], { encoding: "utf8" });
    const m = loudnessOf(out);
    // Clips too short for a loudness reading (under 0.4 s) and sound effects (no target) still
    // get the ceiling; make-up gain is capped at +12 dB so a quiet tail is never pumped up.
    if (loudness.I != null && Number.isFinite(m.I) && m.I > -70) {
      gain = r2(loudness.I - m.I);
      if (gain > 12) { warn(`${src} is very quiet from its start point (${m.I.toFixed(1)} LUFS); check the start time. Boost capped at +12 dB.`); gain = 12; }
    }
    let g = level(gain);
    // The limiter costs a little loudness on dense masters; one correction pass wins it back,
    // capped at 2 dB so the limiter never squashes the track.
    if (g.status === 0 && loudness.I != null && Number.isFinite(m.I) && m.I > -70 && gain < 12) {
      const after = loudnessOf(tmp).I;
      const extra = Number.isFinite(after) ? Math.max(0, Math.min(2, loudness.I - after, 12 - gain)) : 0;
      if (extra > 0.2) { gain = r2(gain + extra); g = level(gain); }
    }
    if (g.status !== 0) { fail(`ffmpeg could not level ${src}: ${g.stderr}`); return null; }
    renameSync(tmp, out);
  }
  return { src: relative(project, out), length: probeAudio(out), gain };
}
function addAudio(id, prepared, at, volume) {
  const dur = r3(Math.min(prepared.length, duration - at));
  if (at >= duration || dur <= 0) { fail(`${id} would start at ${at}s, at or after the end (${duration}s).`); return; }
  audio.push({ id, src: prepared.src, at, dur, volume, gain: prepared.gain });
}
const A = plan.audio || {};
for (const k of ["musicStart", "stingerStart", "musicOut", "musicFade", "musicVolume", "stingerAt", "stingerVolume"])
  if (A[k] != null && !(num(A[k]) && A[k] >= 0)) fail(`audio.${k} must be a number, 0 or more.`);
for (const k of ["musicVolume", "stingerVolume"]) if (num(A[k]) && A[k] > 1) fail(`audio.${k} must be from 0 to 1 (HyperFrames clamps higher values).`);
if (num(A.musicFade) && A.musicFade > 2) fail("audio.musicFade must be at most 2 seconds.");
if (A.musicOut != null && !(A.musicOut > 0)) fail("audio.musicOut must be greater than 0.");
done();
let musicCut = null, musicEnd = null, stingerAt = null;
if (A.music) {
  // The reference bed plays under the products and stops dead as the mark pops. Without a
  // lockup it runs to the end with a short fade. musicStart skips the track's intro so the beat
  // is already playing when the products fly in (music-cue.mjs suggests a value).
  const cut = r3(A.musicOut ?? (lockup ? popAt + 0.04 : duration));
  musicCut = cut;
  const start = A.musicStart ?? 0;
  const srcLen = probeAudio(resolve(project, A.music));
  if (start >= srcLen) fail(`audio.musicStart ${start}s is past the end of ${A.music} (${srcLen.toFixed(2)}s).`);
  done();
  const avail = srcLen - start;
  if (avail < cut - 0.01) warn(`${A.music} has ${avail.toFixed(2)}s after musicStart ${start}s, but the bed should run to ${cut}s; it will stop early. Use an earlier musicStart or a longer track.`);
  const p = prepAudio(A.music, "music.wav", { start, length: Math.min(cut, avail), fade: A.musicFade ?? (lockup ? 0.06 : 0.25), loudness: { I: -14, ceiling: -4.5 } });
  if (p) { addAudio("ip-music", p, 0, A.musicVolume ?? 1); musicEnd = audio.find(a => a.id === "ip-music")?.dur ?? null; }
}
if (A.stinger) {
  if (!lockup && A.stingerAt == null) warn("audio.stinger is skipped: it lands on the lockup slide and this plan has no lockup (set stingerAt to place it).");
  else {
    // A hit that outlasts the spot fades over its last 0.3 s instead of stopping dead.
    const at = r3(A.stingerAt ?? slideAt + 0.08);
    const start = A.stingerStart ?? 0;
    const srcLen = probeAudio(resolve(project, A.stinger));
    if (start >= srcLen) fail(`audio.stingerStart ${start}s is past the end of ${A.stinger} (${srcLen.toFixed(2)}s).`);
    done();
    const room = duration - at;
    const trim = srcLen - start > room ? { start, length: room, fade: Math.min(0.3, room) } : { start };
    const p = prepAudio(A.stinger, "stinger.wav", { ...trim, loudness: { I: -16, ceiling: -4.5 } });
    if (p) { addAudio("ip-stinger", p, at, A.stingerVolume ?? 1); stingerAt = at; }
  }
}
const ANCHORS = { products: T.products.at, card: T.card.at, exit: mirror != null ? mirror - entranceEnd : null, pop: popAt, slide: slideAt };
(A.sfx || []).forEach((s, i) => {
  if (!s || typeof s.src !== "string") { fail(`audio.sfx[${i}] needs a src.`); return; }
  const at = typeof s.at === "number" ? s.at : ANCHORS[s.at];
  if (!num(at)) { fail(`audio.sfx[${i}].at must be seconds or one of ${Object.keys(ANCHORS).filter(k => num(ANCHORS[k])).join(", ")}.`); return; }
  if (s.start != null && !(num(s.start) && s.start >= 0)) { fail(`audio.sfx[${i}].start must be a number, 0 or more.`); return; }
  if (s.volume != null && !(num(s.volume) && s.volume >= 0 && s.volume <= 1)) { fail(`audio.sfx[${i}].volume must be a number from 0 to 1.`); return; }
  if (at < 0) { fail(`audio.sfx[${i}].at is before the start; use "start" to skip into the file instead.`); return; }
  const len = probeAudio(resolve(project, s.src));
  if ((s.start ?? 0) >= len) { fail(`audio.sfx[${i}].start ${s.start}s is past the end of ${s.src} (${len.toFixed(2)}s).`); return; }
  const p = prepAudio(s.src, `sfx-${i + 1}.wav`, { start: s.start ?? 0, loudness: { I: null, ceiling: -4.5 } });
  if (p) addAudio(`ip-sfx-${i + 1}`, p, r3(at), s.volume ?? 0.5);
});
done();
// Sound-effect windows for the audit, recorded before any pre-mix merges the clips.
const sfxWindows = audio.filter(a => a.id.startsWith("ip-sfx-")).map(a => [a.at, r3(a.at + a.dur)]);
// Clips that overlap would add their peaks past the ceiling, so any overlap is pre-mixed into one
// track behind the same limiter. Separate clips stay separate (easier to adjust in Studio).
const overlaps = audio.some(a => audio.some(b => a !== b && a.at < b.at + b.dur && b.at < a.at + a.dur));
if (overlaps) {
  const out = join(audioDir, "mix.wav");
  const inputs = audio.flatMap(a => ["-i", join(project, a.src)]);
  const chains = audio.map((a, i) => `[${i}:a]atrim=0:${a.dur},adelay=${Math.round(a.at * 1000)}:all=1,volume=${a.volume}[a${i}]`);
  const graph = `${chains.join(";")};${audio.map((_, i) => `[a${i}]`).join("")}amix=inputs=${audio.length}:normalize=0:duration=longest,` +
    `alimiter=limit=${(10 ** (-4.5 / 20)).toFixed(4)}:attack=5:release=60:level=disabled,atrim=0:${duration}[m]`;
  const r = spawnSync("ffmpeg", ["-v", "error", "-y", ...inputs, "-filter_complex", graph, "-map", "[m]", "-ar", "48000", "-ac", "2", "-c:a", "pcm_s24le", out], { encoding: "utf8" });
  if (r.status !== 0) { fail(`ffmpeg could not pre-mix the overlapping audio: ${r.stderr}`); done(); }
  const mixed = audio.map(a => a.id).join(", ");
  audio.splice(0, audio.length, { id: "ip-mix", src: relative(project, out), at: 0, dur: r3(Math.min(probeAudio(out), duration)), volume: 1, gain: 0, mixed });
  warn(`${mixed} overlap, so they were pre-mixed into ip/audio/mix.wav behind the -4.5 dBFS ceiling (one track in Studio).`);
}

// ---------------------------------------------------------------- config and page
const mbSamples = plan.motionBlur?.samples ?? 10, shutter = plan.motionBlur?.shutter ?? 0.5;
if (!(Number.isInteger(mbSamples) && mbSamples >= 1 && mbSamples <= 64)) fail("motionBlur.samples must be a whole number from 1 to 64.");
if (!(num(shutter) && shutter >= 0 && shutter <= 1)) fail("motionBlur.shutter must be from 0 to 1 (a fraction of one frame).");
if (plan.camera?.fov != null && !(num(plan.camera.fov) && plan.camera.fov > 1 && plan.camera.fov < 120)) fail("camera.fov must be degrees between 1 and 120.");
done();
const config = {
  width: W, height: H, fps, duration, mirror, background: palette.background,
  // Landmarks for promo-audit.mjs and anyone scripting against the page.
  markers: {
    entranceEnd: r3(entranceEnd), exitStart: mirror != null ? r3(mirror - entranceEnd) : null, exitClear: exitClear != null ? r3(exitClear) : null,
    popAt, slideAt, slideEnd,
    // musicOut is where the bed should stop; musicEnd is where the prepared file actually ends.
    musicOut: musicCut, musicEnd: musicEnd,
    stingerAt: stingerAt,
    sfx: sfxWindows,
  },
  shutter,
  motionBlur: { samples: mbSamples },
  camera: { fov: plan.camera?.fov ?? 20 },
  look: { exposure: 1.0, envIntensity: 1.0, envRotation: 0, key: 0.6, rim: 0.4, ambient: 0.1, ...(plan.look || {}) },
  layers,
  products: products3d,
  gift3d,
};

const cssVars = [
  `--ip-bg:${palette.background}`, `--ip-ink:${palette.ink}`, `--ip-tagline:${palette.tagline}`,
  `--ip-highlight:${palette.highlight}`, `--ip-price-ink:${palette.priceInk}`, `--ip-card:${palette.card}`,
  `--ip-mark:${palette.mark}`, `--ip-word:${palette.word}`,
].join(";");

const page = [
  `<!doctype html>`,
  GENERATED,
  `<html lang="en"><head><meta charset="utf-8">`,
  // Offline by construction: the browser may load only this project's own files, data: and
  // blob: URLs. Whatever a plan value smuggles in, Chrome refuses it before any network access.
  `<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; ` +
    `style-src 'self' 'unsafe-inline' data:; img-src 'self' data: blob:; font-src 'self' data: blob:; media-src 'self' data: blob:; ` +
    `connect-src 'self' data: blob:; worker-src 'self' blob: data:; frame-src 'self' data: blob:; object-src 'none'; base-uri 'self'; form-action 'none'">`,
  `<meta name="viewport" content="width=${W}, height=${H}">`,
  `<title>${esc(plan.title || "Product promo")}</title>`,
  `<link rel="stylesheet" href="ip/ip-kit.css">`,
  `<style>`,
  // Declared inline (not only in ip-kit.css) so HyperFrames' font checks see them and never go
  // looking for these families on Google Fonts.
  `@font-face{font-family:"IP Montserrat";src:url("ip/fonts/Montserrat-Latin-VF.ttf") format("truetype");font-weight:400 800;font-display:block}`,
  `@font-face{font-family:"IP Inter";src:url("ip/fonts/Inter-Latin-VF.ttf") format("truetype");font-weight:400 700;font-display:block}`,
  `html,body{margin:0;padding:0;background:${palette.background}}`,
  `#main{position:relative;width:${W}px;height:${H}px;overflow:hidden;${cssVars}}`,
  // Comments removed (the HyperFrames compiler downloads URLs even from comments) and every
  // declaration closed with ';' (its @font-face reader needs "font-family: ...;").
  stripComments(plan.css || "").replace(/([^;{}\s])(\s*)}/g, "$1;$2}"),
  `</style></head><body>`,
  `<div id="main" data-composition-id="main" data-start="0" data-duration="${duration}" data-fps="${fps}" data-width="${W}" data-height="${H}">`,
  `  <div class="ip-stage" id="ip-stage">`,
  ...html,
  `    <canvas id="ip-gl" width="${W}" height="${H}"></canvas>`,
  ...lockupHtml,
  `    <svg class="ip-defs" aria-hidden="true"><defs>`,
  ...filters.map(f => `      ${f}`),
  `    </defs></svg>`,
  `  </div>`,
  ...audio.map((a, i) => `  <audio id="${a.id}" src="${esc(a.src)}" data-start="${a.at}" data-duration="${a.dur}" data-track-index="${i + 1}" data-volume="${a.volume}"></audio>`),
  `  <script src="assets/gsap.min.js"></script>`,
  `  <script src="ip/ip-kit.js"></script>`,
  `  <script src="ip/ip-3d.js"></script>`,
  `  <script>`,
  // Escaped so no plan string can close the <script> element.
  `    window.IP_CONFIG = ${JSON.stringify(config).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029")};`,
  `    (function () {`,
  `      var cfg = window.IP_CONFIG;`,
  `      IP.mount(cfg);`,
  `      var ready = IP3.init(cfg);`,
  `      function draw(t) { IP.render(t); IP3.render(t); }`,
  `      // Seek-driven renders arrive as hf-seek events; the GSAP clock drives Studio playback.`,
  `      window.addEventListener("hf-seek", function (e) {`,
  `        var t = e.detail.time;`,
  `        IP.render(t);`,
  `        if (IP3.ready) IP3.render(t);`,
  `        else e.detail.waitUntil(ready.then(function () { IP3.render(t); }));`,
  `      });`,
  `      var clock = { t: 0 };`,
  `      var tl = gsap.timeline({ paused: true });`,
  `      tl.to(clock, { t: ${duration}, duration: ${duration}, ease: "none", onUpdate: function () { draw(clock.t); } }, 0);`,
  `      ready.then(function () { draw(clock.t); });`,
  `      IP.render(0);`,
  `      window.__timelines = window.__timelines || {};`,
  `      window.__timelines["main"] = tl;`,
  `    })();`,
  `  </script>`,
  `</div>`,
  `</body></html>`,
].join("\n") + "\n";

// The finished page may not point anywhere remote: HyperFrames' compiler fetches url(http...)
// and @import wherever they appear in the HTML, before the page's CSP applies.
{
  const scan = page.replace(/<meta http-equiv="Content-Security-Policy"[^>]*>/, "");
  const hit = [...scan.matchAll(/url\(\s*['"]?\s*(?:[a-z][a-z0-9+.-]*:|\/\/)[^)]{0,80}|@import[^;]{0,80}/gi)]
    .map(m => m[0]).find(h => !/^url\(\s*['"]?\s*(data|blob):/i.test(h));
  if (hit) { fail(`the generated page references a remote resource (${hit}); find it in the plan and use a local file.`); done(); }
}

// ---------------------------------------------------------------- DESIGN.md
function designMd() {
  const f = n => Number(n.toFixed(3));
  const edges = [...new Set(products.map(p => p.from))];
  const blur = config.shutter > 0;
  const spins = [...new Set(products.map(p => p.spin ?? T.products.spin))];
  const spin = spins.some(x => x) ? `, spinning ${spins.join(" and ")} degrees about the long axis,` : "";
  const prompt = [
    `An Apple-style product spot on a ${palette.background === "#ffffff" ? "pure white" : palette.background} stage.`,
    `${products.length === 2 ? "Two photoreal products fly" : "A photoreal product flies"} in from beyond the ${edges.join(" and ")} edge${edges.length > 1 ? "s" : ""}${spin} and settle${products.length === 2 ? " side by side" : "s"} with a slight lean.`,
    `The offer copy slides in from the left as a centred stack, one line every ${f(T.copy.stagger)} s${copy.some(c => c.role === "price") ? "; a round-capped highlight draws on behind the price" : ""}${card ? "; a card pops in with the gift" : ""}.`,
    mirror != null ? `Everything holds perfectly still for ${f(T.hold)} s, then plays exactly backwards${lockup ? "" : " and the spot ends on the empty stage"}.` : `The layout holds to the end.`,
    lockup ? `A brand mark bounces in at centre${lockup.wordmark ? " and slides left as the wordmark emerges from behind it" : ""}.` : "",
    blur ? "Motion blur on everything, no other effects." : "No motion blur (shutter 0), no other effects.",
  ].filter(Boolean).join(" ");
  return `# DESIGN: iPhone 17 Pro style promo\n${GENERATED}\n<!-- Regenerated on every build from ip-plan.json; edit the plan, not this file. -->\n\n` +
    `## Style Prompt\n${prompt}\n\n` +
    `## Colors\n- Stage ${palette.background}; ink ${palette.ink}; tagline ${palette.tagline}\n- Highlight ${palette.highlight} behind price text ${palette.priceInk}\n` +
    `- Gift card ${palette.card}\n- Mark ${palette.mark}; wordmark ${palette.word}\n\n` +
    `## Typography\n- Copy: Montserrat (bundled as "IP Montserrat"); ${copy.map(c => `${c.role} ${c.size} px/${c.weight}`).join(", ")}\n- Wordmark: Inter 600 (bundled as "IP Inter"), tight tracking\n\n` +
    `## Motion\n- ${format} ${W}x${H} at ${fps} fps, ${f(duration)} s\n- Products: ${f(T.products.duration)} s from ${products.map(p => `${p.at} s`).join(" / ")}, cubic-bezier(${T.products.ease}), ${spins.join("/")}-degree spin, from ${edges.join("/")}\n` +
    `- Copy: ${f(T.copy.duration)} s from ${Math.round(-copyDx)} px left, cubic-bezier(${T.copy.ease}), ${f(T.copy.stagger)} s stagger\n` +
    `- Highlight: ${f(T.pill.duration)} s draw; card: 0 -> ${T.card.peak} -> 1 in ${T.card.up} s + ${T.card.down} s\n` +
    `- Settles at ${f(entranceEnd)} s; ${mirror != null ? `hold ${f(T.hold)} s, mirror ${f(mirror)} s (exact reverse)` : "no exit"}` +
    `${lockup ? `; mark pop ${popAt} s, slide ${slideAt}-${slideEnd} s` : ""}\n` +
    `- ${blur ? `Motion blur: shutter ${config.shutter} frame, ${config.motionBlur.samples} sub-frame${config.motionBlur.samples === 1 ? "" : "s"} on the 3D layer, directional blur on type and cards` : "Motion blur off (shutter 0)"}\n\n` +
    `## What NOT to Do\n- No gradients, shadows under the copy, textures, or extra decoration\n- No per-word animation, no exit other than the mirrored reverse\n` +
    `- No third-party logos or product marks unless the brand owner supplies them\n- No remote files or undeclared font families: everything renders offline\n`;
}

// ---------------------------------------------------------------- write
function archive(file) {
  const dir = join(project, "archive");
  mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const dest = join(dir, `${stamp}-${file.split("/").pop()}`);
  renameSync(file, dest);
  return relative(project, dest);
}

mkdirSync(join(project, "ip"), { recursive: true });
copyFileSync(join(SKILL, "assets/ip-kit.js"), join(project, "ip/ip-kit.js"));
copyFileSync(join(SKILL, "assets/ip-kit.css"), join(project, "ip/ip-kit.css"));
cpSync(join(SKILL, "assets/fonts"), join(project, "ip/fonts"), { recursive: true });

let esbuild;
try { esbuild = require("esbuild"); } catch { console.error("esbuild is missing; run npm ci in the kit root."); process.exit(1); }
let threeDir;
try { threeDir = resolve(dirname(require.resolve("three")), ".."); } catch { console.error("three is missing; run npm ci in the kit root."); process.exit(1); }
esbuild.buildSync({
  entryPoints: [join(SKILL, "assets/ip-3d.mjs")], bundle: true, format: "iife", minify: true,
  outfile: join(project, "ip/ip-3d.js"), nodePaths: [join(KIT_ROOT, "node_modules")], logLevel: "error",
  legalComments: "eof",
});
// The bundle keeps three.js's copyright header; ship its full MIT license beside it.
copyFileSync(join(threeDir, "LICENSE"), join(project, "ip/THREE-LICENSE.txt"));

const gsapLocal = join(project, "assets/gsap.min.js");
if (!existsSync(gsapLocal)) {
  const g = join(KIT_ROOT, "node_modules/gsap/dist/gsap.min.js");
  if (!existsSync(g)) { console.error("Run npm ci in the kit root first (GSAP is copied locally)."); process.exit(1); }
  mkdirSync(dirname(gsapLocal), { recursive: true });
  copyFileSync(g, gsapLocal);
}
const rootFile = join(project, "index.html");
if (existsSync(rootFile) && !readFileSync(rootFile, "utf8").includes(GENERATED)) {
  const moved = archive(rootFile);
  if (!force) console.log(`Archived previous index.html -> ${moved}`);
}
writeFileSync(rootFile, page);
const design = join(project, "DESIGN.md");
if (existsSync(design) && !readFileSync(design, "utf8").includes(GENERATED)) console.log(`Archived previous DESIGN.md -> ${archive(design)}`);
writeFileSync(design, designMd());

console.log(`Built ${relative(process.cwd(), project) || "."}: ${format} ${W}x${H} @ ${fps} fps, ${r3(duration)}s (${frameCount} frames)`);
console.log(`  products ${products.map(p => `${p.at}-${r3(p.at + T.products.duration)}s`).join(", ")}, copy ${slides.length} lines, entrance settles ${r3(entranceEnd)}s`);
console.log(`  ${mirror != null ? `hold ${r3(entranceEnd)}-${r3(mirror - entranceEnd)}s, mirror ${r3(mirror)}s` : "no exit"}${lockup ? `, mark pop ${popAt}s, slide ${slideAt}-${slideEnd}s` : ", no lockup"}`);
if (audio.length) console.log(`  audio: ${audio.map(a => `${a.id}@${a.at}s${a.gain ? ` (${a.gain > 0 ? "+" : ""}${a.gain} dB)` : ""}`).join(", ")}`);
if (musicCut != null) console.log(`  bed cut ${musicCut}s (pass it to music-cue.mjs --cut)`);
console.log(`Render (offline-guarded) from the project folder: see "Gates before delivery" in the skill's SKILL.md.`);
done();
