#!/usr/bin/env node
// Build a White Minimal reel (talking head + captions + posterized minimal-animation scenes)
// as HyperFrames compositions from a plan file.
//
// Usage: node build-reel.mjs <project-dir> [--plan wm-plan.json] [--force]
//
// Writes <project>/index.html, <project>/compositions/wm-<scene>.html, <project>/wm/ (kit),
// and DESIGN.md when the project has none for this style. A previous non-generated index.html
// or DESIGN.md is archived under <project>/archive/ instead of being overwritten.
// See ../SKILL.md and ../references/plan-format.md.

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, renameSync, cpSync } from "node:fs";
import { join, resolve, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const SKILL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT_ROOT = resolve(SKILL, "../../..");
const GENERATED = "<!-- generated by white-minimal-reel/build-reel.mjs -->";
const W = 1080, H = 1920;

const args = process.argv.slice(2);
if (!args.length || args.includes("--help")) {
  console.log("Usage: node build-reel.mjs <project-dir> [--plan wm-plan.json] [--force]");
  process.exit(args.length ? 0 : 1);
}
const project = resolve(args[0]);
const planPath = resolve(project, args.includes("--plan") ? args[args.indexOf("--plan") + 1] : "wm-plan.json");
const force = args.includes("--force");

const errors = [];
const warnings = [];
const fail = m => errors.push(m);
const warn = m => warnings.push(m);

if (!existsSync(planPath)) {
  console.error(`No plan at ${relative(process.cwd(), planPath)}. Start from templates/wm-plan.example.json.`);
  process.exit(1);
}
const plan = JSON.parse(readFileSync(planPath, "utf8"));
const style = { posterizeFps: 12, grain: 0.13, vignette: 0.42, edgeBlur: 9, ...(plan.style || {}) };

// ---------------------------------------------------------------- helpers
const r2 = n => Math.round(n * 100) / 100;
const r3 = n => Math.round(n * 1000) / 1000;
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const norm = s => String(s).toLowerCase().replace(/[’‘`]/g, "'").replace(/[^a-z0-9']+/g, "");
const slug = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function pngSize(file) {
  const b = readFileSync(file);
  if (b.toString("ascii", 12, 16) !== "IHDR") throw new Error(`Not a PNG: ${file}`);
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}
function probe(file) {
  const r = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries",
    "stream=width,height:format=duration", "-of", "json", file], { encoding: "utf8" });
  if (r.status !== 0) throw new Error(`ffprobe failed for ${file}`);
  const j = JSON.parse(r.stdout);
  return { w: j.streams?.[0]?.width, h: j.streams?.[0]?.height, duration: Number(j.format?.duration) };
}
function loadWords(file) {
  const t = JSON.parse(readFileSync(file, "utf8"));
  let words = Array.isArray(t) ? t : t.words;
  if (!words && Array.isArray(t.segments)) words = t.segments.flatMap(s => s.words || []);
  if (!Array.isArray(words)) throw new Error("Transcript needs a words array (see docs/TOOLS-AND-API-KEYS.md).");
  return {
    duration: Number(t.audio_duration_secs) || null,
    words: words
      .filter(w => (w.type ?? "word") === "word")
      .map(w => ({ text: String(w.text ?? w.word ?? "").trim(), start: Number(w.start), end: Number(w.end) }))
      .filter(w => w.text && Number.isFinite(w.start) && Number.isFinite(w.end)),
  };
}

// ---------------------------------------------------------------- inputs
const src = plan.source || {};
if (!src.video) fail("plan.source.video is required (the clean, cut talking-head video).");
if (!src.transcript) fail("plan.source.transcript is required (word timings on that same cut).");
if (errors.length) done();
const videoPath = resolve(project, src.video);
const transcriptPath = resolve(project, src.transcript);
for (const p of [videoPath, transcriptPath]) if (!existsSync(p)) fail(`Missing ${relative(project, p)}`);
if (errors.length) done();

const media = probe(videoPath);
// Sparse keyframes make frame-accurate seeking stall and freeze footage in renders.
const keys = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-skip_frame", "nokey", "-show_entries",
  "frame=pts_time", "-of", "csv=p=0", videoPath], { encoding: "utf8" });
const keyTimes = (keys.stdout || "").split("\n").map(Number).filter(Number.isFinite);
const maxGap = keyTimes.reduce((m, t, i) => (i ? Math.max(m, t - keyTimes[i - 1]) : m), 0);
if (maxGap > 1.05) warn(`${src.video} has keyframes up to ${maxGap.toFixed(1)}s apart; re-encode with ` +
  `ffmpeg -i <in> -c:v libx264 -r 30 -g 30 -keyint_min 30 -crf 16 -c:a aac <out> before rendering.`);
const { words, duration: tDur } = loadWords(transcriptPath);
const D = r3(plan.duration || media.duration || tDur);
if (!D) fail("Could not determine the reel duration.");

// ---------------------------------------------------------------- scenes
const scenes = (plan.scenes || []).map((s, i) => ({ ...s, id: slug(s.id || `scene-${i + 1}`), index: i }));
scenes.sort((a, b) => a.start - b.start);
scenes.forEach((s, i) => {
  if (!(s.end > s.start)) fail(`Scene ${s.id}: end must be after start.`);
  if (s.start < 0 || s.end > D + 0.001) fail(`Scene ${s.id}: outside 0..${D}s.`);
  if (i && s.start < scenes[i - 1].end - 0.001) fail(`Scene ${s.id} overlaps ${scenes[i - 1].id}.`);
  s.start = r3(s.start); s.end = r3(s.end); s.dur = r3(s.end - s.start);
  if (s.dur < 1.2) warn(`Scene ${s.id} is ${s.dur}s; the settle alone needs ~0.9s.`);
  const prev = scenes[i - 1], next = scenes[i + 1];
  s.enter = s.enter || (prev && Math.abs(prev.end - s.start) < 0.001 && prev.exit === "push" ? "push" : "zoom");
  s.exit = s.exit || "cut";
  if (s.exit === "push" && !(next && Math.abs(next.start - s.end) < 0.001))
    warn(`Scene ${s.id} exits with a push but no scene starts at ${s.end}s; the push will blur into footage.`);
});

// Resolve each word's reveal time: explicit `at` (reel seconds) or the onset of `match`.
function findPhrase(phrase, from, until) {
  const tokens = String(phrase).split(/\s+/).map(norm).filter(Boolean);
  for (let i = 0; i < words.length; i++) {
    if (words[i].start < from - 0.05 || words[i].start > until) continue;
    let ok = true;
    for (let k = 0; k < tokens.length; k++) if (!words[i + k] || norm(words[i + k].text) !== tokens[k]) { ok = false; break; }
    if (ok) return words[i];
  }
  return null;
}
for (const s of scenes) {
  let cursor = s.start - 0.6;
  s.words = (s.words || []).map((w, k) => {
    const out = { ...w, key: `${s.id}-w${k + 1}` };
    let at = typeof w.at === "number" ? w.at : null;
    if (at == null) {
      // Prefer the next occurrence after the previous word (repeated words), else anywhere in the scene.
      const hit = findPhrase(w.match || w.text, cursor, s.end) || findPhrase(w.match || w.text, s.start - 0.6, s.end);
      if (hit) { at = hit.start; cursor = hit.start; }
      else { warn(`Scene ${s.id}: "${w.match || w.text}" not found in the transcript window; revealing it with the scene.`); at = s.start; }
    }
    // Two-frame anticipation, but never before the settle has started.
    out.local = r3(Math.min(Math.max(at - s.start - 0.06, 0.12), s.dur - 0.35));
    return out;
  });
}

// ---------------------------------------------------------------- captions over footage
const cap = { enabled: true, maxWords: 3, maxDuration: 1.5, gap: 0.3, hookEnd: 0, ...(plan.captions || {}) };
const inScene = t => scenes.some(s => t >= s.start - 0.02 && t < s.end);
const sceneStartAfter = t => Math.min(D, ...scenes.filter(s => s.start >= t).map(s => s.start));
const visible = cap.enabled ? words.filter(w => !inScene((w.start + w.end) / 2)) : [];

const hookWords = visible.filter(w => w.start < cap.hookEnd);
const lineWords = visible.filter(w => w.start >= cap.hookEnd);
const groups = [];
for (const w of lineWords) {
  const g = groups[groups.length - 1];
  const breakHere = !g || g.words.length >= cap.maxWords || w.start - g.words.at(-1).end > cap.gap ||
    w.end - g.words[0].start > cap.maxDuration || /[.,!?;:]$/.test(g.words.at(-1).text) ||
    sceneStartAfter(g.words.at(-1).end) < w.start;
  if (breakHere) groups.push({ words: [w] }); else g.words.push(w);
}
groups.forEach((g, i) => {
  g.start = r3(Math.max(0, g.words[0].start - 0.04));
  const next = groups[i + 1];
  let end = g.words.at(-1).end + 0.35;
  if (next && next.words[0].start - 0.04 - g.words.at(-1).end < 0.6) end = next.words[0].start - 0.04;
  g.end = r3(Math.min(end, sceneStartAfter(g.words[0].start), D));
  g.text = g.words.map(w => w.text).join(" ");
});

// Hook: the opening phrase accumulates in a stacked, mixed-scale layout.
const SMALL = new Set(["a", "an", "the", "to", "of", "and", "or", "i", "i'm", "i've", "im", "ive", "it", "is", "in", "on", "at", "my", "me", "we", "you", "so", "but", "for", "with", "that", "this", "be", "are", "was", "when", "what", "just", "they", "them", "their"]);
const hook = [];
if (hookWords.length) {
  const items = hookWords.map((w, i) => {
    const big = !SMALL.has(norm(w.text)) && norm(w.text).length > 2;
    const size = big ? 104 : 62;
    return { ...w, key: `hw-${i + 1}`, size, width: w.text.length * size * 0.5 };
  });
  const rows = [];
  for (const it of items) {
    const row = rows[rows.length - 1];
    if (row && row.items.length < 2 && row.width + it.width < 700 && !(row.items[0].size > 90 && it.size > 90)) {
      row.items.push(it); row.width += it.width + 18;
    } else rows.push({ items: [it], width: it.width });
  }
  const offsets = [40, -70, 80, -40, 60, -60];
  let y = 0;
  rows.forEach((row, r) => {
    const h = Math.max(...row.items.map(i => i.size)) * 0.86;
    let x = W / 2 - row.width / 2 + offsets[r % offsets.length];
    for (const it of row.items) {
      hook.push({ ...it, x: r2(Math.max(70, Math.min(W - 70 - it.width, x))), y: r2(y + h - it.size * 0.86) });
      x += it.width + 18;
    }
    y += h;
  });
  hook.start = r3(Math.max(0, hookWords[0].start - 0.04));
  hook.end = r3(Math.min(sceneStartAfter(hookWords[0].start), groups[0]?.start ?? D, hookWords.at(-1).end + 0.5, D));
  hook.top = r2(1640 - y);
}

// ---------------------------------------------------------------- talking-head framing
const th = { hookBlurIn: 0.6, returnSettle: 0.28, focusX: 0.5, focusY: 0.38, punchIn: 1.16, ...(plan.talkingHead || {}) };
const cover = Math.max(W / media.w, H / media.h);
const vw = r2(media.w * cover), vh = r2(media.h * cover);
const vx = r2(Math.min(0, Math.max(W - vw, W / 2 - th.focusX * vw)));
const vy = r2(Math.min(0, Math.max(H - vh, H / 2 - th.focusY * vh)));
const originY = r2(vy + th.focusY * vh);
// Segments of footage between scenes; alternate punch-in framing on each return.
const segments = [];
let t0 = 0, k = 0;
for (const s of [...scenes, { start: D, end: D }]) {
  if (s.start - t0 > 0.05) segments.push({ start: r3(t0), end: r3(s.start), scale: th.framing?.[k]?.scale ?? (k % 2 ? th.punchIn : 1), first: t0 === 0 });
  if (s.start - t0 > 0.05) k++;
  t0 = Math.max(t0, s.end);
}

// ---------------------------------------------------------------- emit root composition
function rootHtml() {
  const lines = [];
  lines.push(`<!doctype html>`, `<html lang="en"><head><meta charset="utf-8"><title>${esc(plan.title || "White minimal reel")}</title>`, GENERATED);
  lines.push(`<link rel="stylesheet" href="wm/wm-kit.css">`, `<script src="assets/gsap.min.js"></script>`);
  lines.push(`<style>`,
    `html,body{margin:0;width:${W}px;height:${H}px;overflow:hidden;background:#000}`,
    `#main{position:relative;width:${W}px;height:${H}px;overflow:hidden;background:#000}`,
    `#th-wrap{transform-origin:${W / 2}px ${originY}px}`,
    `#th-video{left:${vx}px;top:${vy}px;width:${vw}px;height:${vh}px}`,
    `.wm-cap-host{position:absolute;inset:0;z-index:5}`,
    `.wm-scene-host{position:absolute;inset:0;z-index:10}`,
    plan.css || "",
    `</style></head><body>`);
  lines.push(`<div id="main" data-composition-id="main" data-start="0" data-duration="${D}" data-width="${W}" data-height="${H}">`);
  lines.push(`  <div id="th-wrap" class="wm-th">`,
    `    <video id="th-video" src="${esc(src.video)}" data-start="0" data-duration="${D}" data-track-index="0" muted playsinline></video>`,
    `  </div>`,
    `  <audio id="th-audio" src="${esc(src.video)}" data-start="0" data-duration="${D}" data-track-index="1" data-volume="${plan.voiceVolume ?? 1}"></audio>`);
  if (plan.music?.src) lines.push(`  <audio id="music" src="${esc(plan.music.src)}" data-start="0" data-duration="${D}" data-track-index="2" data-volume="${plan.music.volume ?? 0.12}"></audio>`);
  if (hook.length || groups.length)
    lines.push(`  <div id="captions" class="wm-cap-host" data-composition-id="wm-captions" data-composition-src="compositions/wm-captions.html" data-start="0" data-duration="${D}" data-track-index="3" data-width="${W}" data-height="${H}"></div>`);
  for (const s of scenes)
    lines.push(`  <div id="s-${s.id}" class="wm-scene-host" data-composition-id="wm-${s.id}" data-composition-src="compositions/wm-${s.id}.html" data-start="${s.start}" data-duration="${s.dur}" data-track-index="5" data-width="${W}" data-height="${H}"></div>`);

  const js = [];
  js.push(`const tl = gsap.timeline({ paused: true });`, `const wrap = document.getElementById("th-wrap");`);
  for (const seg of segments) {
    if (seg.first && th.hookBlurIn)
      js.push(`tl.fromTo(wrap, { scale: ${r3(seg.scale * 1.08)}, filter: "blur(7px)" }, { scale: ${seg.scale}, filter: "blur(0px)", duration: ${th.hookBlurIn}, ease: "power3.out" }, ${seg.start});`);
    else if (!seg.first && th.returnSettle)
      js.push(`tl.fromTo(wrap, { scale: ${r3(seg.scale * 1.03)}, filter: "blur(5px)" }, { scale: ${seg.scale}, filter: "blur(0px)", duration: ${th.returnSettle}, ease: "power2.out" }, ${seg.start});`);
    else js.push(`tl.set(wrap, { scale: ${seg.scale}, filter: "blur(0px)" }, ${seg.start});`);
  }
  js.push(`window.__timelines = window.__timelines || {};`, `window.__timelines["main"] = tl;`);
  lines.push(`  <script>`, ...js.map(l => `    ${l}`), `  </script>`, `</div>`, `</body></html>`);
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------- emit captions composition
function captionsHtml() {
  const body = [];
  const js = [`var tl = gsap.timeline({ paused: true });`];
  if (hook.length) {
    body.push(`    <div id="hook" class="clip wm-hook" style="top:${hook.top}px" data-start="${hook.start}" data-duration="${r3(hook.end - hook.start)}" data-track-index="1">`);
    for (const h of hook) {
      body.push(`      <span class="hw" id="${h.key}" style="left:${h.x}px;top:${h.y}px;font-size:${h.size}px">${esc(h.text)}</span>`);
      js.push(`tl.fromTo("#${h.key}", { opacity: 0, y: 22, filter: "blur(8px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.32, ease: "power3.out" }, ${r3(Math.max(hook.start, h.start - 0.04))});`);
    }
    body.push(`    </div>`);
  }
  groups.forEach((g, i) => {
    if (g.end - g.start < 0.08) return;
    g.id = `cap-${i + 1}`;
    body.push(`    <div id="${g.id}" class="clip wm-cap" data-start="${g.start}" data-duration="${r3(g.end - g.start)}" data-track-index="0">${esc(g.text)}</div>`);
    js.push(`tl.fromTo("#${g.id}", { opacity: 0, y: 24, filter: "blur(6px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.3, ease: "power3.out" }, ${g.start});`);
  });
  js.push(`window.__timelines = window.__timelines || {};`, `window.__timelines["wm-captions"] = tl;`);
  return [
    `<template id="wm-captions-template">`,
    `  <div data-composition-id="wm-captions" data-width="${W}" data-height="${H}" style="position:absolute;inset:0">`,
    ...body,
    `    <script src="assets/gsap.min.js"></script>`,
    `    <script>`,
    `      (function () {`,
    ...js.map(l => `        ${l}`),
    `      })();`,
    `    </script>`,
    `  </div>`,
    `</template>`,
  ].join("\n") + "\n";
}

// ---------------------------------------------------------------- emit scene compositions
function wordHtml(s, w) {
  const role = w.role || "small";
  const size = w.size || { hero: 220, ghost: 300, small: 56, script: 150 }[role] || 60;
  const anchor = w.anchor || "center";
  const width = w.width || (anchor === "center" ? 1000 : 900);
  const cls = ["wm-word", `wm-${role}`, anchor, ...(w.classes || [])].join(" ");
  const z = w.layer === "back" ? 4 : 7;
  const style = `--x:${w.x ?? 540}px;--y:${w.y ?? 960}px;--w:${width}px;font-size:${size}px;z-index:${z}` +
    (w.rotate ? `;rotate:${w.rotate}deg` : "") + (w.opacity != null ? `;opacity:${w.opacity}` : "");
  return `      <div class="${cls}" id="${w.key}" data-fit="${width}" style="${style}">${esc(w.text)}</div>`;
}

function objectHtml(s, o, idSuffix, z) {
  const file = resolve(project, o.src);
  if (!existsSync(file)) { fail(`Scene ${s.id}: missing ${o.src}`); return ""; }
  const { w: pw, h: ph } = pngSize(file);
  const w = o.w || 620, h = r2(w * ph / pw);
  const left = r2((o.x ?? 540) - w / 2), top = r2((o.y ?? 980) - h / 2);
  const light = o.light || {};
  const shadow = o.shadow || {};
  const data = `data-light-x="${light.x || "125%"}" data-light-y="${light.y || "-30%"}" data-shadow-reach="${shadow.reach ?? 0.2}" data-shadow-strength="${shadow.strength ?? 0.2}" data-tone-angle="${o.toneAngle || "165deg"}"`;
  const look = `grayscale(${o.desat ?? 0.85}) brightness(${o.brightness ?? 0.9}) contrast(${o.contrast ?? 1.08}) url(#wm-${s.id}-inner)`;
  return [
    `      <div class="wm-obj" id="wm-${s.id}-${idSuffix}" ${data} style="left:${left}px;top:${top}px;width:${w}px;height:${h}px;z-index:${z}">`,
    `        <div class="wm-obj-rot" style="rotate:${o.rotate || 0}deg">`,
    `          <div class="wm-obj-shadow" style="opacity:${shadow.opacity ?? 0.65}"></div>`,
    `          <div class="wm-obj-body"><img class="wm-obj-img" src="${esc(o.src)}" alt="" style="filter:${look}"><div class="wm-obj-tone" style="opacity:${o.tone ?? 0.38}"></div></div>`,
    `        </div>`,
    `      </div>`,
  ].join("\n");
}

function depthHtml(s, d, i) {
  const file = resolve(project, d.src);
  if (!existsSync(file)) { fail(`Scene ${s.id}: missing ${d.src}`); return ""; }
  const { w: pw, h: ph } = pngSize(file);
  const w = d.w || 480, h = r2(w * ph / pw);
  const look = `grayscale(${d.desat ?? 0.85}) brightness(${d.brightness ?? 0.8}) drop-shadow(18px 26px 22px rgba(0,0,0,0.45)) blur(${d.blur ?? 9}px)`;
  return `      <div class="wm-depth" id="wm-${s.id}-d${i + 1}" style="left:${r2((d.x ?? 0) - w / 2)}px;top:${r2((d.y ?? 0) - h / 2)}px;width:${w}px;height:${h}px;z-index:2"><div style="rotate:${d.rotate || 0}deg;width:100%;height:100%"><img src="${esc(d.src)}" alt="" style="filter:${look}"></div></div>`;
}

function sceneHtml(s, seed) {
  const id = s.id;
  const body = [];
  (s.depth || []).forEach((d, i) => body.push(depthHtml(s, d, i)));
  (s.panels || (s.panel ? [s.panel] : [])).forEach((p, i) =>
    body.push(`      <div class="wm-panel" id="wm-${id}-p${i + 1}" style="left:${p.x ?? 110}px;top:${p.y ?? 760}px;width:${p.w ?? 860}px;height:${p.h ?? 1260}px;z-index:3${p.rotate ? `;rotate:${p.rotate}deg` : ""}"></div>`));
  for (const w of s.words.filter(w => w.layer === "back")) body.push(wordHtml(s, w));
  if (s.stroke) {
    const k = s.stroke;
    const type = k.type || "sweep";
    const width = k.width ?? (type === "sweep" ? 240 : type === "zigzag" ? 90 : 16);
    body.push(`      <svg class="wm-stroke ${type}" viewBox="0 0 ${W} ${H}" style="z-index:${k.layer === "front" ? 8 : 5}"><defs><linearGradient id="wm-${id}-sg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#000"/><stop offset="1" stop-color="${type === "line" ? "#2b2b2b" : "#3a3a3a"}"/></linearGradient></defs><path id="wm-${id}-stroke" d="${esc(k.d)}" fill="none" stroke="url(#wm-${id}-sg)" stroke-width="${width}" stroke-linecap="round" stroke-linejoin="round"/></svg>`);
  }
  if (s.object) body.push(objectHtml(s, s.object, "obj", 6));
  (s.objects || []).forEach((o, i) => body.push(objectHtml(s, o, `obj${i + 2}`, 6)));
  for (const w of s.words.filter(w => w.layer !== "back")) body.push(wordHtml(s, w));

  const inner = s.object?.inner || {};
  const js = [];
  js.push(`var root = document.getElementById("wm-${id}-root");`, `WM.prepare(root);`, `var tl = gsap.timeline({ paused: true });`,
    `var cam = document.getElementById("wm-${id}-cam");`);
  if (s.enter === "push") js.push(`WM.camPushIn(tl, cam, 0, ${JSON.stringify(s.camera || {})});`);
  else js.push(`WM.camIntro(tl, cam, 0, ${JSON.stringify(s.camera || {})});`);
  const allObjects = [s.object ? { o: s.object, el: "obj" } : null, ...(s.objects || []).map((o, i) => ({ o, el: `obj${i + 2}` }))].filter(Boolean);
  for (const { o, el } of allObjects) {
    const motion = o.motion || "settle";
    const opts = { motion, ...(o.motionOptions || {}) };
    opts.duration = opts.duration ?? r3(Math.max(1.2, s.dur - (o.at ?? 0)));
    js.push(`WM.objectIn(tl, document.getElementById("wm-${id}-${el}"), ${o.at ?? 0}, ${JSON.stringify(opts)});`);
  }
  (s.depth || []).forEach((d, i) => js.push(`WM.drift(tl, document.getElementById("wm-${id}-d${i + 1}"), 0, ${s.dur}, ${JSON.stringify({ dx: d.dx ?? 0, dy: d.dy ?? 0, dr: d.dr ?? 0 })});`));
  (s.panels || (s.panel ? [s.panel] : [])).forEach((p, i) => js.push(`WM.panelIn(tl, document.getElementById("wm-${id}-p${i + 1}"), ${p.at ?? 0.05}, ${JSON.stringify({ dy: p.from === "top" ? -(p.travel ?? 500) : (p.travel ?? 700), duration: r3(Math.max(1.2, s.dur - (p.at ?? 0.05))) })});`));
  if (s.stroke) js.push(`WM.draw(tl, document.getElementById("wm-${id}-stroke"), ${s.stroke.at ?? 0.3}, ${JSON.stringify({ duration: s.stroke.duration ?? 0.9, ease: s.stroke.ease || (s.stroke.type === "zigzag" ? "sine.inOut" : "power3.out") })});`);
  for (const w of s.words) js.push(`WM.pop(tl, document.getElementById("${w.key}"), ${w.local});`);
  js.push(`WM.grain(tl, document.getElementById("wm-${id}-grain"), ${s.dur}, ${seed}, ${style.posterizeFps});`);
  if (s.exit === "push") js.push(`WM.camPushOut(tl, cam, ${r3(s.dur - (s.pushOut ?? 0.5))}, { duration: ${s.pushOut ?? 0.5} });`);
  js.push(`window.__timelines = window.__timelines || {};`,
    style.posterizeFps ? `window.__timelines["wm-${id}"] = WM.posterize(tl, ${s.dur}, ${style.posterizeFps});` : `window.__timelines["wm-${id}"] = tl;`);

  const blinds = s.blindAngle ?? [-9, -14, -6, -11, -16][s.index % 5];
  return [
    `<template id="wm-${id}-template">`,
    `  <div data-composition-id="wm-${id}" data-width="${W}" data-height="${H}" class="wm-scene" id="wm-${id}-root" style="--wm-blind-angle:${blinds}deg;--wm-vignette:${style.vignette};--wm-edge-blur:${style.edgeBlur}px;--wm-grain:${style.grain}">`,
    `    <div class="wm-cam" id="wm-${id}-cam">`,
    `      <div class="wm-bg"><div class="wm-bg-grad"></div><div class="wm-bg-rough"></div><div class="wm-bg-blinds"></div></div>`,
    ...body,
    `    </div>`,
    `    <div class="wm-post"><div class="wm-vignette"></div><div class="wm-edgeblur"></div><div class="wm-grain" id="wm-${id}-grain"></div></div>`,
    `    <svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>`,
    `      <filter id="wm-${id}-inner" x="-5%" y="-5%" width="110%" height="110%" color-interpolation-filters="sRGB">`,
    `        <feComponentTransfer in="SourceAlpha" result="inverse"><feFuncA type="table" tableValues="1 0"/></feComponentTransfer>`,
    `        <feGaussianBlur in="inverse" stdDeviation="${inner.size ?? 16}" result="spread"/>`,
    `        <feComposite in="spread" in2="SourceAlpha" operator="in" result="edge"/>`,
    `        <feFlood flood-color="#000" flood-opacity="${inner.opacity ?? 0.55}"/>`,
    `        <feComposite in2="edge" operator="in" result="shade"/>`,
    `        <feMerge><feMergeNode in="SourceGraphic"/><feMergeNode in="shade"/></feMerge>`,
    `      </filter>`,
    `    </defs></svg>`,
    s.css ? `    <style>${s.css}</style>` : "",
    `    <script src="assets/gsap.min.js"></script>`,
    `    <script src="wm/wm-kit.js"></script>`,
    `    <script>`,
    `      (function () {`,
    ...js.map(l => `        ${l}`),
    `      })();`,
    `    </script>`,
    `  </div>`,
    `</template>`,
  ].filter(Boolean).join("\n") + "\n";
}

// ---------------------------------------------------------------- DESIGN.md
function designMd() {
  return `# DESIGN: White minimal reel\n${GENERATED}\n\n## Style Prompt\nA 9:16 talking-head reel that cuts to warm paper-white minimal scenes: one desaturated\nphotographed object with a streaked cast shadow and halftone grain, the spoken words set\naround it in a heavy compressed gold-to-brown display face, a compact grotesk, and a formal\nscript, soft edge objects out of focus, and a 12 fps posterized, lightly grained finish.\n\n## Colors\n- Paper base #c4b9ad, light #e2d9ce, shade #958a80 (scene backgrounds)\n- Gold gradient #957838 -> #2b2210 (hero words)\n- Ink gradient #5a544e -> #161412 (small lines, script)\n- Caption off-white #efe9e2 over footage\n\n## Typography\n- Hero: Anton (stand-in for a heavy compressed grotesk)\n- Text and captions: Familjen Grotesk 600\n- Accent: Pinyon Script (formal script, 40-50% opacity unless it is the key word)\n\n## Motion\n- Scene in: hard cut, camera 140% -> 110% with blur -> sharp, fast then slow (~0.9 s)\n- Words: rise 27 px + fade + defocus -> sharp, each on its spoken onset\n- Scene to scene: blur push right (out: slow -> fast; in: from left, fast -> slow)\n- Scenes run posterized at 12 fps; footage and captions run at full frame rate\n\n## What NOT to Do\n- No saturated color, no neon, no drop-shadowed UI cards\n- No more than one main object per scene; edge objects stay blurred\n- Never animate a word before it is spoken; never add exit fades inside a scene\n- No captions on top of an animation scene; the scene text replaces them\n`;
}

// ---------------------------------------------------------------- write
function archive(file) {
  const dir = join(project, "archive");
  mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const dest = join(dir, `${stamp}-${file.split("/").pop()}`);
  renameSync(file, dest);
  return relative(project, dest);
}
function done() {
  for (const w of warnings) console.warn(`warning: ${w}`);
  if (errors.length) { for (const e of errors) console.error(`error: ${e}`); process.exit(1); }
}

const rootFile = join(project, "index.html");
const html = rootHtml();
const sceneFiles = scenes.map((s, i) => [join(project, "compositions", `wm-${s.id}.html`), sceneHtml(s, 101 + i * 17)]);
done();

mkdirSync(join(project, "compositions"), { recursive: true });
mkdirSync(join(project, "wm"), { recursive: true });
copyFileSync(join(SKILL, "assets/wm-kit.js"), join(project, "wm/wm-kit.js"));
copyFileSync(join(SKILL, "assets/wm-kit.css"), join(project, "wm/wm-kit.css"));
cpSync(join(SKILL, "assets/fonts"), join(project, "wm/fonts"), { recursive: true });
const gsapLocal = join(project, "assets/gsap.min.js");
if (!existsSync(gsapLocal)) {
  const g = join(KIT_ROOT, "node_modules/gsap/dist/gsap.min.js");
  if (!existsSync(g)) { console.error("Run npm ci in the kit root first (GSAP is copied locally)."); process.exit(1); }
  mkdirSync(dirname(gsapLocal), { recursive: true });
  copyFileSync(g, gsapLocal);
}
if (existsSync(rootFile) && !readFileSync(rootFile, "utf8").includes(GENERATED)) {
  if (!force) console.log(`Archived previous index.html -> ${archive(rootFile)}`);
  else archive(rootFile);
}
writeFileSync(rootFile, html);
for (const [file, content] of sceneFiles) writeFileSync(file, content);
if (hook.length || groups.length) writeFileSync(join(project, "compositions", "wm-captions.html"), captionsHtml());
const design = join(project, "DESIGN.md");
if (!existsSync(design) || !readFileSync(design, "utf8").includes(GENERATED)) {
  if (existsSync(design)) console.log(`Archived previous DESIGN.md -> ${archive(design)}`);
  writeFileSync(design, designMd());
}

console.log(`Built ${relative(process.cwd(), project) || "."}: ${D}s, ${scenes.length} scenes, ${groups.filter(g => g.id).length} caption groups${hook.length ? `, ${hook.length}-word hook stack` : ""}.`);
for (const s of scenes) console.log(`  ${s.id.padEnd(16)} ${s.start.toFixed(2)}-${s.end.toFixed(2)}s  in:${s.enter} out:${s.exit}  words:${s.words.map(w => `${w.text}@${(s.start + w.local).toFixed(2)}`).join(" ")}`);
done();
