#!/usr/bin/env node
// Build a "cutout strobe" edit as a HyperFrames composition from a plan file.
//
// Usage: node .claude/skills/cutout-strobe/scripts/build-cutout.mjs <project-dir>
//          [--plan cs-plan.json] [--no-audio] [--no-matte] [--probe]
//
// The film is a chain of shots. In a "wall" the shot's subject is cut out and holds on top while a
// window cut into the shot behind it strobes through a montage of the other shots, one picture a
// frame. A "step" brings the next shot in over the current one as white shapes: a bar, a column, a
// disc, the next subject's silhouette. A flash is one white frame and thirteen frames of decay.
// Walls sit where the track's bass is in, steps where it rests, flashes on the backbeat.
//
// Writes <project>/index.html, the kit in <project>/cs/, graded proxies, mattes, montage stills,
// and whip stills in <project>/cs/media/, the premixed soundtrack in <project>/cs/audio/mix.wav
// (with stems), the cue sheet <project>/cs/cues.json, and DESIGN.md. A hand-written index.html or
// DESIGN.md is archived under <project>/archive/ first. Media work is cached in cs/cache/.
// --probe writes cs/probe/<clip>.png (three frames with a 10% grid) and, for every wall's clip,
// cs/probe/<clip>-cutout.png (the subject as the matte model sees it), then stops.
// See ../SKILL.md and ../references/plan-format.md.

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, renameSync, statSync, readdirSync, rmSync, linkSync } from "node:fs";
import { join, resolve, dirname, relative, isAbsolute, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { analyze, nearestOnset } from "./lib-bass.mjs";

const SKILL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT_ROOT = resolve(SKILL, "../../..");
const GENERATED = "<!-- generated by cutout-strobe/build-cutout.mjs -->";

const args = process.argv.slice(2);
if (!args.length || args.includes("--help")) {
  console.log("Usage: node build-cutout.mjs <project-dir> [--plan cs-plan.json] [--no-audio] [--no-matte] [--probe]");
  process.exit(args.length ? 0 : 1);
}
const project = resolve(args[0]);
const planPath = resolve(project, args.includes("--plan") ? args[args.indexOf("--plan") + 1] : "cs-plan.json");
const noAudio = args.includes("--no-audio");
const noMatte = args.includes("--no-matte");
const probe = args.includes("--probe");

const errors = [], warnings = [];
const fail = m => errors.push(m);
const warn = m => warnings.push(m);
function done() {
  for (const w of warnings.splice(0)) console.warn(`warn: ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`error: ${e}`);
    process.exit(1);
  }
}
if (!existsSync(planPath)) {
  console.error(`No plan at ${relative(process.cwd(), planPath)}. Start from .claude/skills/cutout-strobe/templates/cs-plan.example.json.`);
  process.exit(1);
}
let plan;
try { plan = JSON.parse(readFileSync(planPath, "utf8")); } catch (e) { console.error(`${planPath}: ${e.message}`); process.exit(1); }

// ---------------------------------------------------------------- helpers
const r1 = n => Math.round(n * 10) / 10;
const r3 = n => Math.round(n * 1000) / 1000;
const r6 = n => Math.round(n * 1e6) / 1e6;
const esc = s => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const isInt = n => Number.isInteger(n);
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const pad = n => String(n).padStart(2, "0");
const hash = (...parts) => createHash("sha1").update(parts.map(p => typeof p === "string" ? p : JSON.stringify(p)).join("|")).digest("hex").slice(0, 12);
function projectFile(p, where) {
  if (typeof p !== "string" || !p) { fail(`${where}: expected a file path inside the project.`); return null; }
  if (/^[a-z]+:/i.test(p)) { fail(`${where}: ${p} is a URL; download it into the project first.`); return null; }
  const abs = resolve(project, p);
  if (relative(project, abs).startsWith("..") || isAbsolute(relative(project, abs))) { fail(`${where}: ${p} is outside the project; copy or link it into assets/.`); return null; }
  if (!existsSync(abs)) { fail(`${where}: missing ${p}.`); return null; }
  return abs;
}
function run(cmd, argv, what, opts = {}) {
  const r = spawnSync(cmd, argv, { encoding: "utf8", maxBuffer: 1 << 28, ...opts });
  if (r.status !== 0) {
    fail(`${what} failed: ${(r.stderr || r.stdout || String(r.error || "")).slice(-900)}`);
    done();
  }
  return r;
}
const probeDur = f => Number(spawnSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f], { encoding: "utf8" }).stdout.trim()) || 0;
// A seeded PRNG (mulberry32): every "random" order is fixed by the plan's seed.
function prng(seed) {
  let a = seed >>> 0;
  return () => { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
}

// ---------------------------------------------------------------- canvas and look
const FPS = Number(plan.fps) || 30;
if (![24, 25, 30].includes(FPS)) fail(`fps must be 24, 25, or 30 (got ${plan.fps}). The style is measured at 30.`);
const FORMATS = { landscape: [1920, 1080], portrait: [1080, 1920], square: [1080, 1080] };
const format = plan.format || "landscape";
if (!FORMATS[format]) fail(`format must be one of ${Object.keys(FORMATS).join(", ")}.`);
const [W, H] = FORMATS[format] || FORMATS.landscape;
const MK = 1280 / Math.max(W, H);                       // mattes run on a copy 1280 px on the long side
const MW = Math.round(W * MK / 2) * 2, MH = Math.round(H * MK / 2) * 2;
const SW = W / 2, SH = H / 2;                           // stills (montage, whips) are half size: they are blurred
const sec = fr => r6(fr / FPS);
// Clip timing for media: the start rounds down and the end rounds up to the microsecond, so a clip
// always covers its first and last frame.
const clipTime = (fr, frames) => {
  const start = Math.floor((fr / FPS) * 1e6) / 1e6;
  const dur = Math.ceil(((fr + frames) / FPS - start) * 1e6) / 1e6;
  return `data-start="${start}" data-duration="${dur}"`;
};
const look = plan.look || {};
// Grades are ffmpeg filters baked into the proxies and stills. "steel" is the reference: cool,
// blue-leaning shadows, crushed blacks, a little more contrast and colour. "neon" pushes the
// colour for a run of shots in the breakdown. "none" leaves graded footage alone.
const GRADES = {
  steel: "eq=contrast=1.14:saturation=1.18:gamma=0.96,colorbalance=rs=-0.08:bs=0.10:rm=-0.03:bm=0.04:rh=0.02:bh=-0.03,curves=all='0/0 0.07/0.03 0.5/0.5 0.92/0.96 1/1'",
  neon: "eq=contrast=1.2:saturation=1.5:gamma=0.97,colorbalance=rs=-0.06:bs=0.12:rh=0.08:bh=-0.08,curves=all='0/0 0.08/0.03 0.5/0.52 0.9/0.96 1/1'",
  soft: "eq=contrast=1.06:saturation=1.08,curves=all='0/0 0.06/0.03 0.5/0.5 1/1'",
  none: "",
};
const gradeOf = (v, where) => {
  if (v == null) return null;
  if (typeof v === "object" && v.filter) return String(v.filter);
  if (!(v in GRADES)) { fail(`${where}: grade must be one of ${Object.keys(GRADES).join(", ")} or { "filter": "<ffmpeg filter>" }.`); return ""; }
  return GRADES[v];
};
const gradeName = typeof look.grade === "string" ? look.grade : look.grade?.filter ? "custom" : "steel";
const GRADE = gradeOf(look.grade ?? "steel", "look.grade");
const HEX = /^#[0-9a-fA-F]{6}$/;
const glowColor = look.glow === false ? null : (look.glow ?? "#ffffff");
if (glowColor && !HEX.test(glowColor)) fail(`look.glow must be #rrggbb or false (got ${JSON.stringify(look.glow)}).`);
const rgb = h => [1, 3, 5].map(i => parseInt(h.slice(i, i + 2), 16)).join(",");
const U = H / 1080;
// The halo: two soft shadows, 16 px and 44 px on a 1080 px frame.
const glowCss = c => c ? `drop-shadow(0 0 ${r1(16 * U)}px rgba(${rgb(c)},0.6)) drop-shadow(0 0 ${r1(44 * U)}px rgba(${rgb(c)},0.38))` : "none";
const WHITE = "brightness(0) invert(1)";
const SEED = Number(plan.seed ?? 11);

// The flash: one white frame, then this decay, measured in the reference at 30 fps (the white's
// opacity over the picture on each following frame). Other frame rates read it by time.
const DECAY30 = [1, 0.69, 0.56, 0.47, 0.4, 0.35, 0.29, 0.25, 0.21, 0.17, 0.13, 0.09, 0.04, 0];
const decayAt = k => {
  const x = (k * 30) / FPS, i = Math.floor(x), f = x - i;
  if (i >= DECAY30.length - 1) return 0;
  return k === 0 ? 1 : r3(DECAY30[i] * (1 - f) + DECAY30[i + 1] * f);
};
const DECAY_FRAMES = Math.ceil((13 * FPS) / 30);

// ---------------------------------------------------------------- clips
const clips = {};
if (!plan.clips || typeof plan.clips !== "object" || !Object.keys(plan.clips).length) fail("clips must name at least one source.");
for (const [name, c] of Object.entries(plan.clips || {})) {
  const where = `clips.${name}`;
  const spec = typeof c === "string" ? { src: c } : c;
  let crop = null;
  if (spec.crop != null) {
    crop = spec.crop;
    if (!Array.isArray(crop) || crop.length !== 4 || crop.some(n => !(Number(n) >= 0 && Number(n) <= 1)) || crop[0] + crop[2] > 1.0001 || crop[1] + crop[3] > 1.0001) fail(`${where}.crop must be [x, y, w, h] fractions of the source frame.`);
  }
  clips[name] = { name, where, src: spec.src, abs: projectFile(spec.src, `${where}.src`), in: Number(spec.in) || 0, crop, grade: spec.grade !== undefined ? gradeOf(spec.grade, `${where}.grade`) : GRADE, gamma: Number(spec.exposure) || 1 };
}
done();

// ---------------------------------------------------------------- timeline (all in frames)
const SHAPES = ["slit", "blinds", "circle", "cross", "quad", "full", "none"];
const STEPS = ["bars", "top", "columns", "circle", "hero"];
const WHIPS = ["zoom", "spin", "v", "h"];
const EASES = {
  linear: t => t,
  // The reference's slit: fast at first, then slower, fitted to its measured height on 33 frames.
  expo: t => 1 - (Math.exp(-2 * t) - Math.exp(-2)) / (1 - Math.exp(-2)),
  out: t => 1 - Math.pow(1 - t, 3),
  in: t => t * t * t,
};
if (!Array.isArray(plan.timeline) || !plan.timeline.length) fail("timeline must be a non-empty array.");
done();

const items = [];
let cursor = 0;
plan.timeline.forEach((it, i) => {
  const where = `timeline[${i}]`;
  const type = it.wall != null ? "wall" : it.shot != null ? "shot" : it.step != null ? "step" : null;
  if (!type) { fail(`${where}: an item is { "wall": "<clip>" }, { "shot": "<clip>" }, or { "step": "<shape>" }.`); return; }
  let frames = it.frames;
  if (it.until != null) {
    if (!isInt(it.until) || it.until <= cursor) { fail(`${where}.until (${it.until}) must be a whole frame after the item's start (${cursor}).`); return; }
    frames = it.until - cursor;
  }
  if (!isInt(frames) || frames < 1) { fail(`${where}: give "frames" or "until" as whole frames at ${FPS} fps.`); return; }
  const o = { i, where, type, a: cursor, b: cursor + frames, frames, label: it.label ?? null, src: it };
  if (type === "step") {
    o.shape = it.step;
    if (!STEPS.includes(o.shape)) fail(`${where}.step must be one of ${STEPS.join(", ")}.`);
    o.each = Number(it.each ?? 3);
    if (!isInt(o.each) || o.each < 2) fail(`${where}.each must be 2 frames or more: one white frame, then the picture.`);
  } else {
    const name = it[type];
    o.clip = clips[name];
    if (!o.clip) { fail(`${where}.${type}: no clip named ${JSON.stringify(name)} (have: ${Object.keys(clips).join(", ")}).`); return; }
    o.in = it.in != null ? Number(it.in) : o.clip.in;
    o.enter = it.enter ?? null;
    if (o.enter && !["cut", "whip", "flash"].includes(o.enter)) fail(`${where}.enter must be "cut", "whip", or "flash".`);
    o.whip = it.whip ?? null;
    if (o.whip && !WHIPS.includes(o.whip)) fail(`${where}.whip must be one of ${WHIPS.join(", ")}.`);
    o.flash = (it.flash === true ? [0] : Array.isArray(it.flash) ? it.flash : it.flash != null ? [it.flash] : []).map(Number);
    if (o.flash.some(f => !isInt(f) || f < 0 || f >= frames)) fail(`${where}.flash: offsets are whole frames inside the item (0-${frames - 1}).`);
    o.mono = it.base === "mono";
    if (it.base && !["mono", "color"].includes(it.base)) fail(`${where}.base must be "color" or "mono".`);
    if (type === "wall") {
      const w = it.window === undefined ? { shape: "full" } : it.window === null || it.window === false ? { shape: "none" } : typeof it.window === "string" ? { shape: it.window } : it.window;
      if (!SHAPES.includes(w.shape)) fail(`${where}.window.shape must be one of ${SHAPES.join(", ")}.`);
      if (w.ease && !EASES[w.ease]) fail(`${where}.window.ease must be one of ${Object.keys(EASES).join(", ")}.`);
      if (w.off != null && (!isInt(Number(w.off)) || w.off < 1)) fail(`${where}.window.off: the frame inside the wall where the window closes, 1 or more.`);
      o.window = w;
      o.blink = (Array.isArray(it.blink) ? it.blink : it.blink != null ? [it.blink] : []).map(Number);
      if (o.blink.some(f => !isInt(f) || f < 0 || f >= frames)) fail(`${where}.blink: offsets are whole frames inside the item.`);
      o.glow = it.glow === undefined ? glowColor : it.glow === false ? null : it.glow === true ? glowColor ?? "#ffffff" : it.glow;
      if (o.glow && !HEX.test(o.glow)) fail(`${where}.glow must be #rrggbb, true, or false.`);
      o.each = it.each ?? look.montage?.each ?? 1;
      const pat = Array.isArray(o.each) ? o.each : [o.each];
      if (pat.some(n => !isInt(Number(n)) || n < 1)) fail(`${where}.each: frames per montage picture, a whole number or a list of them.`);
      o.pattern = pat.map(Number);
      o.pool = it.montage ?? look.montage?.pool ?? Object.keys(clips).filter(n => n !== name);
      if (w.shape !== "none" && (!Array.isArray(o.pool) || !o.pool.length)) fail(`${where}.montage: the window needs other clips to show. Name at least two.`);
      for (const p of o.pool || []) if (!clips[typeof p === "string" ? p : p.clip]) fail(`${where}.montage: no clip named ${JSON.stringify(typeof p === "string" ? p : p.clip)}.`);
    }
  }
  cursor = o.b;
  items.push(o);
});
done();
const TOTAL = cursor;
const D = sec(TOTAL);
const sections = items.filter(o => o.type !== "step");
items.forEach((o, k) => {
  if (o.type !== "step") return;
  const prev = items[k - 1], next = items[k + 1];
  if (!prev || prev.type === "step" || !next || next.type === "step") { fail(`${o.where}: a step sits between two shots. It brings the next one in over the one before.`); return; }
  if (o.shape === "hero" && next.type !== "wall") fail(`${o.where}: a "hero" step needs a wall next; a plain shot has no cutout.`);
  o.prev = prev; o.next = next;
  prev.ext = o.frames; next.lead = o.frames; next.stepIn = o;
});
sections.forEach((s, n) => {
  s.n = n + 1; s.id = `s${n + 1}`;
  s.lead ||= 0; s.ext ||= 0;
  // After a step the shot lands through a whip unless the plan says otherwise.
  if (!s.enter) s.enter = s.stepIn ? "whip" : "cut";
  if (s.enter === "whip" && s.a === 0) { warn(`${s.where}: the first item cannot enter through a whip; it cuts.`); s.enter = "cut"; }
  if (s.enter === "flash" && !s.flash.includes(0)) s.flash.unshift(0);
  if (!s.whip) s.whip = s.stepIn ? "zoom" : "v";
  if (s.in - s.lead / FPS < 0) { warn(`${s.where}: the step before it needs ${s.lead} frames of this clip before its in point; in moved from ${s.in} s to ${r3(s.lead / FPS)} s.`); s.in = s.lead / FPS; }
});
done();

// ---------------------------------------------------------------- media prep
const csDir = join(project, "cs");
const mediaDir = join(csDir, "media");
const cacheDir = join(csDir, "cache");
mkdirSync(mediaDir, { recursive: true });
mkdirSync(join(cacheDir, "stills"), { recursive: true });
const manifestPath = join(cacheDir, "manifest.json");
const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, "utf8")) : {};
const used = new Set();
const saveManifest = () => writeFileSync(manifestPath, JSON.stringify(manifest, null, 1) + "\n");
const stamp = f => { const st = statSync(f); return `${st.size}:${Math.round(st.mtimeMs)}`; };
const rel = f => relative(project, f);
const cached = (key, out) => { used.add(rel(out)); return manifest[rel(out)] === key && existsSync(out); };
const remember = (key, out) => { manifest[rel(out)] = key; saveManifest(); };
const src = f => rel(f).split("\\").join("/");

const cropVf = c => c ? `crop=w=iw*${c[2]}:h=ih*${c[3]}:x=iw*${c[0]}:y=ih*${c[1]}` : null;
const cover = (w, h) => `scale=${w}:${h}:force_original_aspect_ratio=increase:flags=lanczos,crop=${w}:${h}`;
const tone = c => [c.gamma !== 1 ? `eq=gamma=${c.gamma}` : null, c.grade || null].filter(Boolean);
const fpsCache = {};
function srcFps(abs) {
  if (fpsCache[abs]) return fpsCache[abs];
  const r = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=r_frame_rate", "-of", "csv=p=0", abs], { encoding: "utf8" }).stdout.trim();
  const [a, b] = r.split("/").map(Number);
  return (fpsCache[abs] = a && b ? a / b : FPS);
}
// In points snap to whole source frames, and a seek lands a quarter frame early, so the wanted
// frame is the first one decoded.
const snap = (abs, t) => { const f = srcFps(abs); return Math.round(t * f) / f; };
const seekAt = (abs, t) => Math.max(0, t - 0.25 / srcFps(abs));

// A proxy is the section's span of its source (from the step that previews it to the step that
// takes it out), graded, at the plan's frame rate, with a keyframe every half second.
function makeProxy(s) {
  const c = s.clip, abs = c.abs;
  const inSec = snap(abs, s.in - s.lead / FPS);
  const srcDur = probeDur(abs);
  if (!srcDur) { fail(`cannot read ${rel(abs)}`); done(); }
  const pre = Math.min(12, Math.floor(inSec * FPS));
  const from = inSec - pre / FPS;
  const frames = s.lead + s.frames + s.ext;
  const len = Math.min((pre + frames + 12) / FPS, srcDur - from);
  if (inSec + frames / FPS > srcDur + 0.01) fail(`${s.where}: ${rel(abs)} is ${r3(srcDur)} s; ${frames} frames from ${r3(inSec)} s run past its end. Move "in" earlier.`);
  const vf = [`fps=${FPS}`, cropVf(c.crop), cover(W, H), ...tone(c), "format=yuv420p"].filter(Boolean).join(",");
  const out = join(mediaDir, `${s.id}.mp4`);
  const key = hash(abs, stamp(abs), r6(from), r6(len), vf, "p1");
  if (!cached(key, out)) {
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(abs, from))), "-t", String(r6(len)), "-i", abs, "-vf", vf, "-an",
      "-c:v", "libx264", "-preset", "medium", "-crf", "16", "-g", String(Math.round(FPS / 2)), "-keyint_min", String(Math.round(FPS / 2)),
      "-sc_threshold", "0", "-movflags", "+faststart", out], `proxy ${s.id}`);
    remember(key, out);
  }
  return { file: out, pre, key };
}
// Blur recipes for stills, as ffmpeg filter graphs from [0:v] to [out]. Spin and zoom are the
// mean of several rotated or scaled copies; the streaks are a one-axis gaussian.
function blurGraph(kind, amount, pre) {
  const N = 9;
  if (kind === "spin") {
    const big = [Math.round(SW * 1.4 / 2) * 2, Math.round(SH * 1.4 / 2) * 2];
    const parts = [`[0:v]${pre},${cover(big[0], big[1])},split=${N}${Array.from({ length: N }, (_, i) => `[r${i}]`).join("")}`];
    for (let i = 0; i < N; i++) parts.push(`[r${i}]rotate=${r6(((i / (N - 1)) * 2 - 1) * amount)}:c=black[q${i}]`);
    parts.push(`${Array.from({ length: N }, (_, i) => `[q${i}]`).join("")}mix=inputs=${N},crop=${SW}:${SH}[out]`);
    return parts.join(";");
  }
  if (kind === "zoom") {
    const parts = [`[0:v]${pre},${cover(SW, SH)},split=${N}${Array.from({ length: N }, (_, i) => `[r${i}]`).join("")}`];
    for (let i = 0; i < N; i++) { const z = 1 + (i / (N - 1)) * amount * 2.4; parts.push(`[r${i}]scale=${Math.round(SW * z / 2) * 2}:${Math.round(SH * z / 2) * 2}:flags=bilinear,crop=${SW}:${SH}[q${i}]`); }
    parts.push(`${Array.from({ length: N }, (_, i) => `[q${i}]`).join("")}mix=inputs=${N}[out]`);
    return parts.join(";");
  }
  if (kind === "v") return `[0:v]${pre},${cover(SW, SH)},gblur=sigma=2:sigmaV=${Math.round(900 * amount * (SH / 540))}[out]`;
  if (kind === "h") return `[0:v]${pre},${cover(SW, SH)},gblur=sigma=${Math.round(900 * amount * (SW / 960))}:sigmaV=2[out]`;
  return `[0:v]${pre},${cover(SW, SH)}[out]`;
}
// A montage still: one frame of a clip, graded, usually pulled down to near grey, and blurred into
// texture. Its range is stretched and its mid-tones levelled with a gamma, so every still lands
// near the same mean brightness with its contrast kept, whatever the footage: dark night shots
// are lifted, bright day shots are pulled down, and the subject in front stays the brightest
// sharp thing on screen.
const LEVEL = { dark: Number(look.montage?.level ?? 0.2), color: Number(look.montage?.level ?? 0.2) + 0.06 };
function montageStill(c, t, toneKind, blur, amount, name) {
  t = snap(c.abs, clamp(t, 0, Math.max(0, probeDur(c.abs) - 0.1)));
  const base = [cropVf(c.crop), ...tone(c), toneKind === "dark" ? "hue=s=0.22,colorbalance=bs=0.04:bm=0.03" : null, "normalize=smoothing=0:strength=0.75"].filter(Boolean).join(",");
  const out = join(cacheDir, "stills", `${name}.jpg`);
  // Baked once into the cache; each wall that uses it gets its own link in media/ (below), so no
  // two elements on the page share a source.
  const key = hash(c.abs, stamp(c.abs), r6(t), base, blur, r6(amount), LEVEL[toneKind], SW, SH, "m3");
  if (!cached(key, out)) {
    const m = spawnSync("ffmpeg", ["-v", "error", "-ss", String(r6(seekAt(c.abs, t))), "-i", c.abs, "-frames:v", "1", "-vf", `${base},scale=64:36,format=gray`, "-f", "rawvideo", "-"], { maxBuffer: 1 << 20 });
    const b = m.stdout || Buffer.alloc(0);
    let mean = LEVEL[toneKind];
    if (b.length) { let sum = 0; for (const v of b) sum += v; mean = Math.max(0.02, sum / b.length / 255); }
    const gamma = r3(clamp(Math.log(mean) / Math.log(LEVEL[toneKind]), 0.55, 1.9));
    const graph = blurGraph(blur, amount, `${base}${Math.abs(gamma - 1) > 0.04 ? `,eq=gamma=${gamma}` : ""}`);
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, t))), "-i", c.abs, "-frames:v", "1", "-filter_complex", graph, "-map", "[out]", "-q:v", "3", out], `montage still ${name}`);
    remember(key, out);
  }
  return out;
}
// A whip still: one exact frame of a proxy, smeared.
function whipStill(px, frameIdx, kind, name) {
  const graph = blurGraph(kind, kind === "v" || kind === "h" ? 0.09 : kind === "spin" ? 0.13 : 0.12, `select=eq(n\\,${frameIdx})`);
  const out = join(mediaDir, `${name}.jpg`);
  const key = hash(px.key, frameIdx, graph, "w1");
  if (!cached(key, out)) {
    run("ffmpeg", ["-v", "error", "-y", "-i", px.file, "-filter_complex", graph, "-map", "[out]", "-frames:v", "1", "-q:v", "3", out], `whip still ${name}`);
    remember(key, out);
  }
  return out;
}
const hfEnv = { env: { ...process.env, HYPERFRAMES_NO_TELEMETRY: "1" } };

console.log(`cutout strobe: ${sections.length} shots (${sections.filter(s => s.type === "wall").length} walls), ${items.filter(o => o.type === "step").length} steps, ${TOTAL} frames = ${r3(D)} s at ${FPS} fps, ${W}x${H}. Preparing media...`);

// Probe sheets: three frames of every clip with a 10% grid, and the cutout of every wall's clip.
if (probe) {
  const pdir = join(csDir, "probe");
  mkdirSync(pdir, { recursive: true });
  const heroes = new Set(sections.filter(s => s.type === "wall").map(s => s.clip.name));
  for (const c of Object.values(clips)) {
    const out = join(pdir, `${c.name}.png`);
    const vf = [cropVf(c.crop), cover(W / 3, H / 3), ...tone(c), `drawgrid=w=${W / 30}:h=${H / 30}:t=1:c=white@0.5`, `drawgrid=w=${W / 6}:h=${H / 6}:t=2:c=red@0.8`, "format=rgb24"].filter(Boolean).join(",");
    const dur = probeDur(c.abs);
    const shots = [0, 0.6, 1.2].map(d => Math.min(dur - 0.1, c.in + d));
    const tmp = shots.map((t, k) => { const f = join(cacheDir, `probe-${c.name}-${k}.png`); run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, snap(c.abs, t)))), "-i", c.abs, "-frames:v", "1", "-vf", vf, f], `probe ${c.name}`); return f; });
    run("ffmpeg", ["-v", "error", "-y", ...tmp.flatMap(f => ["-i", f]), "-filter_complex", `hstack=inputs=${tmp.length}`, "-frames:v", "1", out], `probe sheet ${c.name}`);
    tmp.forEach(f => rmSync(f, { force: true }));
    console.log(`probe: ${rel(out)} (in, +0.6 s, +1.2 s; grid lines every 10%, red at 50%)`);
    if (heroes.has(c.name)) {
      const still = join(cacheDir, `probe-${c.name}-still.png`), cut = join(cacheDir, `probe-${c.name}-cut.png`), sheet = join(pdir, `${c.name}-cutout.png`);
      run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, snap(c.abs, c.in)))), "-i", c.abs, "-frames:v", "1", "-vf", [cropVf(c.crop), cover(MW, MH), ...tone(c)].filter(Boolean).join(","), still], `probe still ${c.name}`);
      run("npx", ["--prefix", KIT_ROOT, "hyperframes", "remove-background", still, "-o", cut], `remove-background for ${c.name}`, hfEnv);
      run("ffmpeg", ["-v", "error", "-y", "-f", "lavfi", "-i", `color=c=0xff00ff:s=${MW}x${MH}`, "-i", cut, "-filter_complex", "[0][1]overlay=format=auto", "-frames:v", "1", sheet], `cutout sheet ${c.name}`);
      rmSync(still, { force: true }); rmSync(cut, { force: true });
      console.log(`probe: ${rel(sheet)} (the subject over magenta: what holds in front of the window)`);
    }
  }
  process.exit(0);
}

for (const s of sections) s.px = makeProxy(s);
done();
if (noMatte && sections.some(x => x.type === "wall")) warn("--no-matte: no subject is cut out in this build, so the windows cover the subjects and the silhouettes are missing. For timing checks only.");

// Mattes: the subject of every wall, as a video with alpha, from the same proxy (so it sits on
// the shot pixel for pixel and frame for frame).
for (const s of sections.filter(x => x.type === "wall")) {
  if (noMatte) continue;
  const out = join(mediaDir, `${s.id}-matte.webm`);
  const key = hash(s.px.key, "matte", MW, MH);
  if (!cached(key, out)) {
    console.log(`matte: cutting out the subject of ${s.id} (${s.clip.name}, ${s.lead + s.frames + s.ext} frames; local model)...`);
    const small = join(cacheDir, `matte-in-${s.id}.mp4`);
    run("ffmpeg", ["-v", "error", "-y", "-i", s.px.file, "-vf", `scale=${MW}:${MH}:flags=lanczos`, "-c:v", "libx264", "-crf", "14", "-preset", "fast", small], `matte input for ${s.id}`);
    run("npx", ["--prefix", KIT_ROOT, "hyperframes", "remove-background", small, "-o", out, "--quality", "best"], `remove-background for ${s.id}`, hfEnv);
    rmSync(small, { force: true });
    remember(key, out);
  }
  // How much of the frame the subject covers, on its first own frame, in the middle, and at the end.
  const covKey = `${rel(out)}#cover`;
  if (manifest[covKey]?.key !== key) {
    const idx = [s.px.pre + s.lead, s.px.pre + s.lead + Math.floor(s.frames / 2), s.px.pre + s.lead + s.frames - 1];
    const r = spawnSync("ffmpeg", ["-v", "error", "-c:v", "libvpx-vp9", "-i", out, "-vf", `select='${idx.map(k => `eq(n\\,${k})`).join("+")}',alphaextract,scale=64:36,format=gray`, "-fps_mode", "passthrough", "-f", "rawvideo", "-"], { maxBuffer: 1 << 26 });
    const b = r.stdout || Buffer.alloc(0);
    const v = [];
    for (let k = 0; k * 2304 < b.length; k++) { let t = 0; for (let i = 0; i < 2304; i++) t += b[k * 2304 + i]; v.push(r3(t / 2304 / 255)); }
    manifest[covKey] = { key, v };
    saveManifest();
  }
  used.add(covKey);
  s.cover = manifest[covKey].v;
  s.matte = out;
  const lo = Math.min(...s.cover), hi = Math.max(...s.cover);
  if (!s.cover.length || lo < 0.015) warn(`${s.where}: the matte model found almost no subject in ${s.clip.name} (${Math.round(lo * 100)}% of the frame). The wall would be a window with nobody in front. Pick a frame with a clear figure, or use "shot".`);
  else if (hi > 0.7) warn(`${s.where}: the subject of ${s.clip.name} covers ${Math.round(hi * 100)}% of the frame, so the window barely shows. Use a wider shot for a wall.`);
}

// ---------------------------------------------------------------- compile the edit
// State changes are collected per element and property, then reduced: on each frame the last
// write wins, and a write that does not change the value is dropped.
const writes = [];
let order = 0;
const put = (fr, sel, props) => { for (const [k, v] of Object.entries(props)) writes.push({ fr: Math.max(0, fr), sel, k, v, o: order++ }); };
const cues = [];
const cue = (fr, kind, why, extra = {}) => { if (fr >= 0 && fr < TOTAL) cues.push({ frame: fr, at: sec(fr), kind, why, ...extra }); };
const nodes = [];            // section html, in order
const overlays = [];         // whip stills
const flash = new Float64Array(TOTAL);
const addFlash = fr => { for (let k = 0; k <= DECAY_FRAMES && fr + k < TOTAL; k++) flash[fr + k] = Math.max(flash[fr + k], decayAt(k)); };
const NONE = "none";

// Window outlines, as clip-path values in px.
const rect = (x0, y0, x1, y1) => `M${r1(x0)} ${r1(y0)}H${r1(x1)}V${r1(y1)}H${r1(x0)}Z`;
const path = d => `path("${d}")`;
function outline(w, v) {
  const cx = (w.cx ?? 0.5) * W, cy = (w.cy ?? w.y ?? 0.5) * H;
  switch (w.shape) {
    case "full": return NONE;
    case "slit": {
      if (v >= 0.999) return NONE;
      const h = v * H;
      return h < 1 ? null : path(rect(0, clamp(cy - h / 2, 0, H), W, clamp(cy + h / 2, 0, H)));
    }
    case "blinds": {
      // Slats close one after another from the top; v is how much of the stack is still open.
      const n = Number(w.count) || 5, fill = Number(w.fill) || 0.62, pitch = H / n;
      const d = [];
      for (let k = 0; k < n; k++) {
        const open = clamp(v * n - (n - 1 - k), 0, 1);
        const h = pitch * fill * open;
        if (h >= 1) { const mid = pitch * (k + 0.5); d.push(rect(0, mid - h / 2, W, mid + h / 2)); }
      }
      return d.length ? path(d.join("")) : null;
    }
    case "circle": {
      const r = v * H;
      return r < 1 ? null : `circle(${r1(r)}px at ${r1(cx)}px ${r1(cy)}px)`;
    }
    case "cross": {
      // Two bands through one point, at +v and -v degrees: an X that shuts like scissors to a bar.
      const half = ((Number(w.width) || 0.22) * H) / 2, L = W + H;
      const band = deg => {
        const a = (deg * Math.PI) / 180, c = Math.cos(a), s = Math.sin(a);
        const p = [[-L, -half], [L, -half], [L, half], [-L, half]].map(([x, y]) => `${r1(cx + x * c - y * s)} ${r1(cy + x * s + y * c)}`);
        return `M${p[0]}L${p[1]}L${p[2]}L${p[3]}Z`;
      };
      return path(band(v) + band(-v));
    }
    case "quad": {
      // A panel in one corner that grows to the whole frame.
      if (v >= 0.999) return NONE;
      const pw = W * (0.5 + 0.5 * v), ph = H * (0.3 + 0.7 * v), c = w.corner || "tr";
      const x0 = c.includes("r") ? W - pw : 0, y0 = c.includes("b") ? H - ph : 0;
      return path(rect(x0, y0, x0 + pw, y0 + ph));
    }
    default: return null;
  }
}
// The window's value on each of its frames: keys [[frame, value], ...], or from and to with an ease.
const DEFAULTS = { slit: [1, 0.05, "expo"], blinds: [1, 0, "linear"], circle: [0.06, 1.05, "linear"], cross: [50, 0, "linear"], quad: [0, 1, "in"], full: [1, 1, "linear"] };
function windowValues(w, frames) {
  if (w.shape === "none") return null;
  const d = DEFAULTS[w.shape];
  let keys = w.keys;
  if (!keys) {
    const from = Number(w.from ?? d[0]), to = Number(w.to ?? d[1]), over = Math.max(1, Math.min(frames - 1, Number(w.over) || frames - 1)), ease = EASES[w.ease || d[2]];
    return Array.from({ length: frames }, (_, f) => from + (to - from) * ease(Math.min(1, f / over)));
  }
  keys = keys.map(k => [Number(k[0]), Number(k[1])]).sort((a, b) => a[0] - b[0]);
  return Array.from({ length: frames }, (_, f) => {
    if (f <= keys[0][0]) return keys[0][1];
    for (let k = 1; k < keys.length; k++) if (f <= keys[k][0]) { const t = (f - keys[k - 1][0]) / (keys[k][0] - keys[k - 1][0]); return keys[k - 1][1] + (keys[k][1] - keys[k - 1][1]) * t; }
    return keys[keys.length - 1][1];
  });
}

let vTrack = 0;
sections.forEach((s, n) => {
  const vStart = s.a - s.lead, vFrames = s.lead + s.frames + s.ext;
  const tag = `${s.id} (${s.clip.name})`;
  const base = `#${s.id}-base`, win = `#${s.id}-win`, hero = `#${s.id}-hero`, wrap = `#${s.id}`;
  const track = 1 + (vTrack++ % 2);
  const kids = [`<div id="${s.id}-base" class="cs-base${s.mono ? " mono" : ""}"><video id="v-${s.id}" src="${src(s.px.file)}" ${clipTime(vStart, vFrames)} data-media-start="${sec(s.px.pre)}" data-track-index="${track}" muted playsinline></video></div>`];
  const GLOW = s.type === "wall" ? glowCss(s.glow) : NONE;

  // The section is hidden until the step that previews it starts drawing, or until its own start.
  put(0, wrap, { opacity: 0 });
  put(s.a, wrap, { opacity: 1 });
  put(s.a, base, { clipPath: NONE });
  put(s.b + s.ext, wrap, { opacity: 0 });

  if (s.type === "wall") {
    // Montage: the pool's stills in a seeded order, never the same clip twice in a row.
    const vals = windowValues(s.window, s.frames);
    const rnd = prng(SEED + s.n * 977);
    let imgs = [];
    if (vals) {
      const mm = { per: 3, gap: 0.45, blur: "mix", tone: "mix", ...(look.montage || {}), ...(s.src.montageLook || {}) };
      const stills = [];
      s.pool.forEach((p, pi) => {
        const spec = typeof p === "string" ? { clip: p } : p;
        const c = clips[spec.clip];
        for (let j = 0; j < (spec.per ?? mm.per); j++) {
          const t = (spec.in ?? c.in) + 0.25 + j * (spec.gap ?? mm.gap);
          const tk = spec.tone ?? mm.tone, bk = spec.blur ?? mm.blur;
          // "mix": seven stills in ten go dark and grey, the rest keep their colour; spin and
          // zoom alternate two to one. The choice depends only on the clip and the still.
          const pick = prng(SEED * 31 + c.name.split("").reduce((a, ch) => a * 33 + ch.charCodeAt(0), 7) + j * 131);
          const toneKind = tk === "mix" ? (pick() < 0.7 ? "dark" : "color") : tk;
          const blur = bk === "mix" ? (pick() < 0.68 ? "spin" : "zoom") : bk;
          const amount = blur === "spin" ? 0.07 + pick() * 0.08 : 0.1 + pick() * 0.06;
          stills.push({ clip: c.name, file: montageStill(c, t, toneKind, blur, amount, `m-${c.name}-${hash(r6(t), toneKind, blur, r6(amount)).slice(0, 6)}`) });
        }
      });
      // Schedule: which still is up on each frame.
      // The montage keeps running through the step that takes the shot out.
      const run = s.frames + s.ext;
      const off = s.window.off != null ? Number(s.window.off) : Infinity;
      const sched = [];
      let last = null, bag = [], pi = 0;
      for (let f = 0; f < run;) {
        if (!bag.length) bag = stills.map((st, k) => ({ k, v: rnd() })).sort((x, y) => x.v - y.v).map(o => o.k);
        let at = bag.findIndex(k => last == null || stills[k].clip !== stills[last].clip);
        if (at < 0) at = 0;
        const k = bag.splice(at, 1)[0];
        const len = s.pattern[pi++ % s.pattern.length];
        for (let q = 0; q < len && f < run; q++, f++) sched.push(k);
        last = k;
      }
      imgs = stills.map((st, k) => {
        const own = join(mediaDir, `${s.id}-m${k + 1}.jpg`);
        const key = hash(manifest[rel(st.file)], "link");
        if (!cached(key, own)) {
          rmSync(own, { force: true });
          try { linkSync(st.file, own); } catch { copyFileSync(st.file, own); }
          remember(key, own);
        }
        return `<img id="${s.id}-m${k + 1}" src="${src(own)}" alt="">`;
      });
      stills.forEach((_, k) => put(0, `#${s.id}-m${k + 1}`, { opacity: 0 }));
      put(0, win, { opacity: 0, clipPath: NONE });
      let up = null, shown = null;
      for (let f = 0; f < run; f++) {
        // "off" closes the window for good (the reference drops it on the flash in some walls).
        const cp = f >= off ? null : outline(s.window, vals[Math.min(f, s.frames - 1)]);
        if (cp == null) { if (shown !== false) { put(s.a + f, win, { opacity: 0 }); shown = false; } continue; }
        if (shown !== true) { put(s.a + f, win, { opacity: 1 }); shown = true; }
        put(s.a + f, win, { clipPath: cp });
        if (sched[f] !== up) {
          if (up != null) put(s.a + f, `#${s.id}-m${up + 1}`, { opacity: 0 });
          put(s.a + f, `#${s.id}-m${sched[f] + 1}`, { opacity: 1 });
          up = sched[f];
        }
      }
      const live = sched.slice(0, Math.min(run, off));
      s.pictures = new Set(live).size;
      s.changes = live.filter((k, f) => f && k !== live[f - 1]).length;
    } else put(0, win, { opacity: 0, clipPath: NONE });
    kids.push(`<div id="${s.id}-win" class="cs-win">${imgs.join("")}</div>`);
    if (s.matte) {
      kids.push(`<div id="${s.id}-hero" class="cs-hero"><video id="v-${s.id}-hero" src="${src(s.matte)}" ${clipTime(vStart, vFrames)} data-media-start="${sec(s.px.pre)}" data-track-index="${track + 2}" muted playsinline></video></div>`);
      put(0, hero, { opacity: 0, filter: GLOW });
      put(s.a, hero, { opacity: 1, filter: GLOW });
      // A blink: the subject goes white for one frame inside its own wall.
      for (const f of s.blink) { put(s.a + f, hero, { filter: `${WHITE} ${GLOW === NONE ? "" : GLOW}`.trim() }); put(s.a + f + 1, hero, { filter: GLOW }); cue(s.a + f, "tick", `${tag} blink`); }
    }
  }
  for (const f of s.flash) {
    addFlash(s.a + f);
    cue(s.a + f, "hit", `${tag} flash${f ? ` ${f} frames in` : ""}`);
    const tail = s.a + f + DECAY_FRAMES - s.b;
    if (s.ext && tail > 3) warn(`${s.where}: the flash on frame ${s.a + f} is still fading for ${tail} frames into the step after it, and the step's white shapes go grey under it. Flash earlier, or leave this wall without one (a wall wants ${DECAY_FRAMES + 3} frames after its flash).`);
  }

  // The step that brings this shot in, drawn with this section's own layers over the one before.
  const st = s.stepIn;
  if (st) {
    const whipOut = s.enter === "whip" ? 1 : 0;
    const count = Math.max(1, Math.min(Number(st.src.count) || 99, Math.floor((st.frames - whipOut) / st.each)));
    const lead = st.frames - whipOut - count * st.each;
    const hasHero = s.type === "wall" && !!s.matte;
    const heroFrom = st.shape === "hero" ? 0 : !hasHero || st.src.hero === false ? Infinity : Number(st.src.heroFrom ?? (st.shape === "circle" ? 1 : st.shape === "columns" || st.shape === "top" ? Infinity : 2));
    const cy = (st.src.y ?? 0.5) * H;
    const sizes = st.src.sizes;
    const geo = k => {
      if (st.shape === "hero") return [null, null];
      if (st.shape === "bars") { const h = H * (sizes?.[Math.min(k, sizes.length - 1)] ?? Math.min(0.36, 0.24 + 0.12 * k)); const d = path(rect(0, cy - h / 2, W, cy + h / 2)); return [d, d]; }
      if (st.shape === "top") { const h = H * (sizes?.[Math.min(k, sizes.length - 1)] ?? Math.min(0.92, (k + 1) / (count + 0.35))); const d = path(rect(0, 0, W, h)); return [d, d]; }
      if (st.shape === "columns") { const cw = W / count; return [path(rect(0, 0, cw * (k + 1), H)), path(rect(cw * k, 0, cw * (k + 1), H))]; }
      if (st.shape === "circle") { const r = H * (sizes?.[Math.min(k, sizes.length - 1)] ?? Number(st.src.r ?? 0.17)); const d = `circle(${r1(r)}px at ${r1((st.src.cx ?? 0.5) * W)}px ${r1((st.src.cy ?? 0.5) * H)}px)`; return [d, d]; }
      return [null, null];
    };
    st.count = count; st.lead = lead; st.hits = [];
    put(st.a + lead, wrap, { opacity: 1 });
    if (st.shape === "hero") put(st.a + lead, base, { clipPath: "inset(50%)" });
    for (let k = 0; k < count; k++) {
      const f0 = st.a + lead + k * st.each;
      const [show, white] = geo(k);
      const heroOn = k >= heroFrom;
      if (show) put(f0, base, { clipPath: show });
      if (heroOn) {
        // The white frame is the subject's silhouette; the window already shows the shot.
        put(f0, hero, { opacity: 1, filter: WHITE });
        put(f0 + 1, hero, { filter: GLOW });
        cue(f0, "tick", `step into ${tag}: silhouette ${k + 1}`, { gain: 1.25 });
      } else {
        put(f0, "#cs-white", { opacity: 1, clipPath: white });
        put(f0 + 1, "#cs-white", { opacity: 0 });
        cue(f0, "tick", `step into ${tag}: ${st.shape} ${k + 1}`);
      }
      st.hits.push(f0);
    }
    if (hasHero && heroFrom === Infinity) put(st.a, hero, { opacity: 0 });
  }
  // The whip: the outgoing picture smeared on the frame before the cut, the incoming one smeared
  // on the cut itself, sharp from the next frame.
  if (s.enter === "whip") {
    const prev = sections[n - 1];
    const outStill = whipStill(prev.px, prev.px.pre + prev.lead + (s.a - 1 - prev.a), s.whip, `whip-${s.id}-out`);
    const inStill = whipStill(s.px, s.px.pre + s.lead, s.whip, `whip-${s.id}-in`);
    [[outStill, s.a - 1, "out"], [inStill, s.a, "in"]].forEach(([file, fr, side]) => {
      const id = `wh-${s.id}-${side}`;
      overlays.push(`<img id="${id}" class="cs-whip" src="${src(file)}" alt="">`);
      put(0, `#${id}`, { opacity: 0 });
      put(fr, `#${id}`, { opacity: 1 });
      put(fr + 1, `#${id}`, { opacity: 0 });
    });
    cue(s.a, "whip", `whip into ${tag}`, { align: "peak" });
  }
  if (s.src.rise) cue(s.a, "rise", `riser into ${tag}`, { align: "end", span: Number(s.src.rise) > 0 && s.src.rise !== true ? Number(s.src.rise) : 2.4 });
  nodes.push(`<div id="${s.id}" class="cs-sec" data-z="${10 + n}">${kids.join("")}</div>`);
});
put(0, "#cs-white", { opacity: 0, clipPath: NONE });
put(0, "#cs-flash", { opacity: 0 });
for (let f = 0; f < TOTAL; f++) put(f, "#cs-flash", { opacity: flash[f] });
done();

// Reduce the writes to sets.
const byKey = new Map();
for (const w of writes) {
  if (w.fr >= TOTAL) continue;
  const key = `${w.sel}|${w.k}`;
  if (!byKey.has(key)) byKey.set(key, new Map());
  const m = byKey.get(key), had = m.get(w.fr);
  if (!had || had.o < w.o) m.set(w.fr, w);
}
const inline = {}, setMap = new Map();
for (const [, m] of byKey) {
  const list = [...m.values()].sort((a, b) => a.fr - b.fr);
  let cur;
  for (const w of list) {
    if (w.fr === 0) { (inline[w.sel] ||= {})[w.k] = w.v; cur = w.v; continue; }
    if (cur !== undefined && String(cur) === String(w.v)) continue;
    cur = w.v;
    const k = `${w.fr}|${w.sel}`;
    if (!setMap.has(k)) setMap.set(k, [w.fr, w.sel, {}]);
    setMap.get(k)[2][w.k] = w.v;
  }
}
const sets = [...setMap.values()].sort((a, b) => a[0] - b[0]);

// ---------------------------------------------------------------- the track's bass against the plan
const music = plan.music || {};
const musicAbs = music.file ? projectFile(music.file, "music.file") : null;
done();
const report = [];
let an = null;
const gates = [];
if (musicAbs) {
  an = analyze(musicAbs, { from: Number(music.start) || 0, len: D + 0.5 });
  if (!an) warn(`could not analyse ${music.file}; the plan is not checked against the track.`);
}
const bassShare = (a, b) => { if (!an) return null; let n = 0, on = 0; for (let f = a; f < b; f++) { n++; if (an.stateAt((f + 0.5) / FPS)) on++; } return n ? on / n : 0; };
for (const o of items) {
  const share = bassShare(o.a, o.b);
  const row = { o, share, notes: [] };
  if (o.type === "step") {
    const gate = o.src.gate ?? music.gate ?? false;
    if (an && share > 0.35) {
      if (gate) { gates.push([o.a, o.b]); row.notes.push("bass gated out"); }
      else warn(`${o.where}: the bass is in for ${Math.round(share * 100)}% of this step (frames ${o.a}-${o.b}). A step belongs in a rest. Move it (see bass-map.mjs), or set "gate": true to cut the low end under it.`);
    } else if (gate === "always") { gates.push([o.a, o.b]); row.notes.push("bass gated out"); }
  } else {
    if (an && o.enter === "whip") {
      // The landing should sit where the bass comes back.
      const edges = an.spans.filter(sp => sp.kind !== "gap").map(sp => sp.a);
      const d = edges.length ? edges.map(t => t * FPS - o.a).reduce((m, x) => (Math.abs(x) < Math.abs(m) ? x : m), 1e9) : null;
      if (d != null && Math.abs(d) <= FPS / 2) { row.notes.push(`lands ${r1(Math.abs(d))} f ${d < 0 ? "after" : "before"} the bass`); if (Math.abs(d) > 1.5) warn(`${o.where}: the shot lands on frame ${o.a}, ${r1(Math.abs(d))} frames ${d < 0 ? "after" : "before"} the bass comes in (frame ${r1(o.a + d)}). Move the cut onto it.`); }
    }
    for (const f of o.flash) {
      if (!an) break;
      const near = nearestOnset(an, (o.a + f) / FPS, 0.2);
      const d = near ? near.d * FPS : null;
      row.notes.push(d == null ? `flash@${o.a + f}: no attack near` : `flash@${o.a + f}: attack ${d >= 0 ? "+" : ""}${r1(d)} f`);
      if (d == null || Math.abs(d) > 1.5) warn(`${o.where}: the flash on frame ${o.a + f} has ${d == null ? "no attack within 6 frames" : `its nearest attack ${r1(Math.abs(d))} frames ${d > 0 ? "later" : "earlier"} (frame ${r1(o.a + f + d)})`}. A flash with no hit under it reads as a glitch.`);
    }
  }
  report.push(row);
}

// ---------------------------------------------------------------- audio
// Effect levels are set against the bed: an effect's loudest 10 ms sits this many dB under the
// bed's loudest 10 ms, so a click and a thud are placed by how loud they are, not by their peaks.
const SFX = { hit: -7, tick: -13, whip: -10, rise: -15 };
let audioTag = "", mixInfo = "silent (no music or sfx in the plan)";
const audioDir = join(csDir, "audio");
mkdirSync(join(audioDir, "stems"), { recursive: true });
const measure = f => {
  const e = spawnSync("ffmpeg", ["-hide_banner", "-nostats", "-i", f, "-af", "ebur128=peak=true", "-f", "null", "-"], { encoding: "utf8" }).stderr;
  const num = re => Number(((e.match(re) || []).pop() || "").match(/-?[\d.]+/)?.[0]);
  return { I: num(/I:\s+-?[\d.]+ LUFS/g), TP: num(/Peak:\s+-?[\d.]+ dBFS/g) };
};
function envelope(file, from, len) {
  const r = spawnSync("ffmpeg", ["-v", "error", ...(from ? ["-ss", String(from)] : []), ...(len ? ["-t", String(len)] : []), "-i", file, "-ac", "1", "-ar", "22050", "-f", "f32le", "-"], { maxBuffer: 1 << 29 });
  if (r.status !== 0) { fail(`ffmpeg could not decode ${rel(file)}`); return null; }
  const b = r.stdout, x = new Float32Array(b.buffer.slice(b.byteOffset, b.byteOffset + b.length - (b.length % 4)));
  const hop = 220, n = Math.floor(x.length / hop), e = new Float64Array(n);
  for (let i = 0; i < n; i++) { let s = 0; for (let j = 0; j < hop; j++) { const v = x[i * hop + j]; s += v * v; } e[i] = Math.sqrt(s / hop); }
  let pk = 0; for (let i = 1; i < n; i++) if (e[i] > e[pk]) pk = i;
  let on = 0; while (on < pk && e[on] < e[pk] * 0.1) on++;
  return { len: x.length / 22050, peak: pk / 100, onset: on / 100, loud: 20 * Math.log10((e[pk] || 1e-6)) };
}
const placed = [];
if (!noAudio && (musicAbs || plan.sfx)) {
  const files = {};
  for (const [k, v] of Object.entries(plan.sfx || {})) {
    if (!(k in SFX)) { warn(`sfx.${k} is not a cue kind (${Object.keys(SFX).join(", ")}); ignored.`); continue; }
    const spec = typeof v === "string" ? { file: v } : v;
    const abs = projectFile(spec.file, `sfx.${k}`);
    if (!abs) continue;
    const a = envelope(abs);
    if (!a) continue;
    files[k] = { abs, db: spec.db ?? SFX[k], trim: Number(spec.trim) || 0, cut: spec.len != null ? Number(spec.len) : null, ...a };
  }
  done();
  const missing = [...new Set(cues.map(c => c.kind))].filter(k => !files[k]);
  if (missing.length) warn(`No sfx for ${missing.join(", ")}; those cues are silent. Add them to plan.sfx (see references/sound-design.md).`);
  const mg = Number(music.gain ?? 1);
  const bed = musicAbs ? envelope(musicAbs, Number(music.start) || 0, D) : null;
  const bedLoud = bed ? bed.loud + 20 * Math.log10(mg) : -12;
  const inputs = [], chains = [], sfxL = [], bedL = [];
  const add = f => { inputs.push("-i", f); return inputs.length / 2 - 1; };
  cues.sort((a, b) => a.frame - b.frame).forEach((c, i) => {
    const f = files[c.kind];
    if (!f) return;
    let from, start, len;
    if (c.align === "end") {
      // The last `span` seconds of the file end exactly on the cue (a riser into a landing).
      const span = Math.min(c.span ?? f.len, f.len - f.trim);
      from = Math.max(f.trim, Math.min(f.len - span, f.peak + 0.05 - span));
      len = span; start = c.at - len;
      if (start < 0) { from -= start; len += start; start = 0; }
    } else if (c.align === "peak") {
      // The file's loudest moment lands on the cue: a whoosh peaks on the cut, not after it.
      from = Math.max(f.trim, f.peak - Math.min(f.peak, 0.25));
      start = Math.max(0, c.at - (f.peak - from));
      len = Math.min(f.cut ?? Infinity, f.len - from);
    } else {
      // The file's onset lands on the cue's frame: the sound starts with the picture change.
      from = Math.max(f.trim, f.onset - 0.004);
      start = Math.max(0, c.at - (f.onset - from));
      len = Math.min(f.cut ?? Infinity, f.len - from);
    }
    len = Math.max(0.02, Math.min(len, D - start));
    const fade = c.align === "end" ? 0.012 : Math.min(0.12, len * 0.4);
    const g = Math.pow(10, (bedLoud + f.db - f.loud) / 20) * (c.gain ?? 1);
    const k = add(f.abs);
    const fin = c.align === "end" ? `,afade=t=in:d=${r3(Math.min(0.4, len / 2))}` : "";
    chains.push(`[${k}:a]atrim=start=${r3(from)}:duration=${r3(len)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${g.toFixed(4)}${fin},afade=t=out:st=${r3(Math.max(0, len - fade))}:d=${r3(fade)},adelay=${Math.round(start * 1000)}:all=1[c${i}]`);
    sfxL.push(`[c${i}]`);
    placed.push({ ...c, start: r3(start), from: r3(from), len: r3(len), file: rel(f.abs) });
  });
  if (musicAbs) {
    // The bed plays from music.start. Under a gated step its low end is cut out, so the bass
    // rests where the picture breaks up. The joins crossfade over 8 ms.
    const start = Number(music.start) || 0, mDur = probeDur(musicAbs);
    if (start + D > mDur + 0.01) fail(`music: ${r3(D)} s from ${start} s runs past the end of the track (${r3(mDur)} s).`);
    const fadeOut = r3(Math.min((Number(music.fade ?? 8)) / FPS, D / 4));
    const cutsAt = [...new Set([0, D, ...gates.flatMap(([a, b]) => [sec(a), sec(b)])])].sort((a, b) => a - b);
    const X = 0.008;
    for (let i = 0; i + 1 < cutsAt.length; i++) {
      const a = cutsAt[i], b = cutsAt[i + 1];
      if (b - a < 0.001) continue;
      const gated = gates.some(([ga, gb]) => sec(ga) <= a + 1e-6 && sec(gb) >= b - 1e-6);
      const first = i === 0, last = b >= D - 1e-6;
      const a2 = first ? a : a - X / 2, b2 = last ? b : b + X / 2;
      const k = add(musicAbs), tagN = `m${i + 1}`;
      const fx = gated ? `,highpass=f=${Number(music.gateHz) || 220}:p=2,volume=0.85` : "";
      const fin = first ? 0.02 : X, fout = last ? fadeOut : X;
      chains.push(`[${k}:a]atrim=start=${r6(start + a2)}:duration=${r6(b2 - a2)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${mg.toFixed(3)}${fx},afade=t=in:d=${fin}${fout ? `,afade=t=out:st=${r6(Math.max(0, b2 - a2 - fout))}:d=${fout}` : ""},adelay=${Math.round(a2 * 1000)}:all=1[${tagN}]`);
      bedL.push(`[${tagN}]`);
    }
    placed.push({ kind: "music", file: rel(musicAbs), start: 0, from: start, gates: gates.map(([a, b]) => ({ a: sec(a), b: sec(b) })), fadeOut });
  }
  done();
  if (sfxL.length || bedL.length) {
    const raw = join(audioDir, "mix-raw.wav"), out = join(audioDir, "mix.wav");
    const bus = (ls, tagN) => `${ls.join("")}amix=inputs=${ls.length}:normalize=0:duration=longest,apad=whole_dur=${D},atrim=0:${D}[${tagN}]`;
    const graph = [...chains], layers = [];
    if (bedL.length) { graph.push(bus(bedL, "bedbus")); layers.push("bed"); }
    if (sfxL.length) { graph.push(bus(sfxL, "sfxbus")); layers.push("sfx"); }
    layers.forEach(L => graph.push(`[${L}bus]asplit=2[${L}m][${L}]`));
    graph.push(`${layers.map(L => `[${L}m]`).join("")}amix=inputs=${layers.length}:normalize=0:duration=longest,atrim=0:${D}[mix]`);
    const stemMaps = layers.flatMap(L => ["-map", `[${L}]`, "-ar", "48000", "-c:a", "pcm_s16le", join(audioDir, "stems", `${L}.wav`)]);
    run("ffmpeg", ["-v", "error", "-y", ...inputs, "-filter_complex", graph.join(";"), "-map", "[mix]", "-ar", "48000", "-c:a", "pcm_s16le", raw, ...stemMaps], "ffmpeg mix");
    // -14 LUFS through a limiter at 4x the sample rate (catches inter-sample peaks), ceiling
    // -5 dBFS so the renderer's AAC encode stays under -1 dBTP. Repeated until within 0.25 LU.
    const m0 = measure(raw);
    let gainDb = Number.isFinite(m0.I) ? -14 - m0.I : 0, got = null;
    for (let pass = 0; pass < 3; pass++) {
      const af = `volume=${gainDb.toFixed(2)}dB,aresample=192000,alimiter=limit=0.56:attack=1:release=50:level=false,aresample=48000`;
      run("ffmpeg", ["-v", "error", "-y", "-i", raw, "-af", af, "-ar", "48000", "-c:a", "pcm_s16le", out], "loudness pass");
      got = measure(out);
      if (!Number.isFinite(got.I) || Math.abs(got.I + 14) < 0.25) break;
      gainDb += -14 - got.I;
    }
    if (got && got.TP > -4) warn(`mix.wav peaks at ${got.TP} dBTP; after the AAC encode it may pass -1 dBTP.`);
    if (layers.length === 2) {
      const sb = measure(join(audioDir, "stems", "bed.wav")).I, ss = measure(join(audioDir, "stems", "sfx.wav")).I;
      if (Number.isFinite(sb) && Number.isFinite(ss) && sb - ss < 6) warn(`the effects stem sits ${r1(sb - ss)} LU under the bed (want 6 or more). The track should carry the film; lower the sfx "db" values.`);
    }
    audioTag = `<audio id="cs-mix" src="cs/audio/mix.wav" data-start="0" data-duration="${D}" data-track-index="0" data-volume="1"></audio>`;
    mixInfo = `cs/audio/mix.wav (${placed.filter(p => p.kind !== "music").length} sfx cues${musicAbs ? " + music" : ""}${gates.length ? `, ${gates.length} gated steps` : ""}, ${m0.I} LUFS -> ${got?.I} LUFS, ${got?.TP} dBTP)`;
  }
}
const flashFrames = sections.flatMap(s => s.flash.map(f => s.a + f));
writeFileSync(join(csDir, "cues.json"), JSON.stringify({
  fps: FPS, frames: TOTAL, duration: D, width: W, height: H,
  items: items.map(o => ({ type: o.type, a: o.a, b: o.b, ...(o.type === "step" ? { shape: o.shape, each: o.each, count: o.count, hits: o.hits } : { clip: o.clip.name, enter: o.enter, ...(o.type === "wall" ? { window: o.window.shape, hero: !!o.matte } : {}) }), label: o.label })),
  flashes: flashFrames, whips: sections.filter(s => s.enter === "whip").map(s => s.a),
  whites: items.filter(o => o.type === "step").flatMap(o => o.hits || []),
  cues: placed.length ? placed : cues,
}, null, 2) + "\n");

// ---------------------------------------------------------------- kit and gsap
copyFileSync(join(SKILL, "assets", "cs-kit.css"), join(csDir, "cs-kit.css"));
copyFileSync(join(SKILL, "assets", "cs-kit.js"), join(csDir, "cs-kit.js"));
const gsapLocal = join(project, "assets", "gsap.min.js");
if (!existsSync(gsapLocal)) {
  const g = join(KIT_ROOT, "node_modules/gsap/dist/gsap.min.js");
  if (!existsSync(g)) { fail("assets/gsap.min.js is missing and node_modules/gsap is not installed (run npm ci in the kit root)."); done(); }
  mkdirSync(dirname(gsapLocal), { recursive: true });
  copyFileSync(g, gsapLocal);
}
// Drop generated media the plan no longer uses.
for (const f of readdirSync(mediaDir)) {
  const p = join(mediaDir, f);
  if (!used.has(rel(p))) { rmSync(p, { recursive: true, force: true }); delete manifest[rel(p)]; }
}
saveManifest();

// ---------------------------------------------------------------- index.html
const stampNow = new Date().toISOString().replace(/[:.]/g, "-");
function archive(file) {
  const p = join(project, file);
  if (!existsSync(p)) return;
  const text = readFileSync(p, "utf8");
  if (text.includes("generated by cutout-strobe")) return;
  mkdirSync(join(project, "archive"), { recursive: true });
  renameSync(p, join(project, "archive", `${stampNow}-${file}`));
  console.log(`Archived the previous ${file} to archive/${stampNow}-${file}`);
}
archive("index.html");
archive("DESIGN.md");

const kebab = k => k.replace(/[A-Z]/g, c => "-" + c.toLowerCase());
const styleOf = sel => Object.entries(inline[sel] || {}).map(([k, v]) => `${kebab(k)}:${v}`).join(";");
// Frame 0 states go inline on each element, so the page is right before any script runs.
const withInline = html => html.replace(/<(div|img)\b([^>]*?)\bid="([^"]+)"([^>]*)>/g, (m, tagN, pre, id, post) => {
  const extra = styleOf(`#${id}`);
  return extra ? `<${tagN}${pre}id="${id}"${post} style="${extra.replace(/"/g, "'")}">` : m;
});
const body = withInline([...nodes, ...overlays.map(h => h.replace("<img ", `<img data-z="800" `)), `<div id="cs-white" class="cs-white" data-z="850"></div>`, `<div id="cs-flash" class="cs-flash" data-z="900"></div>`].join("\n"));
const zs = [...new Set([...sections.map((_, n) => 10 + n), 800, 850, 900])];
const zStyle = zs.map(z => `.cs-frame [data-z="${z}"]{z-index:${z}}`).join("");
const cfg = { fps: FPS, duration: D, root: "main", sets };
const html = `<!doctype html>
${GENERATED}
<html lang="en"><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' data:; img-src 'self' data: blob:; font-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self' data: blob:; object-src 'none'; base-uri 'self'; form-action 'none'">
<meta name="viewport" content="width=${W}, height=${H}">
<title>${esc(plan.title || "Cutout strobe edit")}</title>
<link rel="stylesheet" href="cs/cs-kit.css">
<style>
html,body{margin:0;padding:0;background:#000}
#main{--cs-w:${W}px;--cs-h:${H}px}
${zStyle}
</style></head><body>
<div id="main" class="cs-stage" data-composition-id="main" data-start="0" data-duration="${D}" data-fps="${FPS}" data-width="${W}" data-height="${H}">
<div id="cs-frame" class="cs-frame">
${body}
</div>
${audioTag}
<script src="assets/gsap.min.js"></script>
<script src="cs/cs-kit.js"></script>
<script>
window.CS_CONFIG = ${JSON.stringify(cfg)};
(function () {
  var tl = CS.build(window.CS_CONFIG);
  window.__timelines = window.__timelines || {};
  window.__timelines["main"] = tl;
})();
</script>
</div>
</body></html>
`;
writeFileSync(join(project, "index.html"), html);

// ---------------------------------------------------------------- DESIGN.md
const walls = sections.filter(s => s.type === "wall");
const pictures = walls.reduce((t, s) => t + (s.changes || 0), 0);
const design = `${GENERATED.replace("<!--", "<!-- regenerated on every build;")}
# ${plan.title || "Cutout strobe edit"}: cutout strobe

## Style Prompt

A performer holds still in front while the world behind strobes. In every wall the shot's subject
is cut out and kept on top, and a window cut into the shot behind (a slit, blinds, a disc, an X, a
panel) shows a montage of the other shots, blurred to texture, one picture a frame. The next shot
steps in over the current one as white shapes: a bar, a column, a disc, the next subject's
silhouette. One white frame with a thirteen-frame decay marks the backbeat. The picture is full
while the bass is in and breaks into white shapes while it rests.

## Colors

- All colour comes from the footage (${esc(gradeName)} grade): cool shadows, crushed blacks.
- White (#ffffff) is the only added colour: the flash, the step shapes, the silhouettes${glowColor ? `, and the ${glowColor} halo round the subject` : ""}.
- Montage pictures sit dark and close to grey, so the subject is the brightest sharp thing on screen.

## Typography

- None. The style has no type.

## Motion

- ${FPS} fps, ${W}x${H}. Every event is a whole frame; nothing is tweened at run time.
- ${sections.length} shots: ${walls.length} walls and ${sections.length - walls.length} plain shots, ${items.filter(o => o.type === "step").length} steps, ${flashFrames.length} flashes, ${sections.filter(s => s.enter === "whip").length} whips, over ${r3(D)} s.
- ${pictures} montage changes behind the subjects (${r1(pictures / Math.max(1e-3, walls.reduce((t, s) => t + s.frames, 0) / FPS))} a second inside the walls).
- Windows: ${walls.map(s => s.window.shape).join(", ")}.
- A flash is one white frame, then ${DECAY_FRAMES} frames of decay. A whip is two frames. A step shows white for one frame of every ${[...new Set(items.filter(o => o.type === "step").map(o => o.each))].join(" or ") || 3}.

## What NOT to Do

- Do not add type, captions, lower thirds, stickers, or a logo.
- Do not strobe the subject. The subject holds; the world behind it changes.
- Do not show a montage picture sharp or at full brightness behind the subject.
- Do not put a step where the bass is in, or a flash where the track has no hit.
- Do not crossfade or dissolve between shots. A shot enters through a step, a whip, or a flash.
`;
writeFileSync(join(project, "DESIGN.md"), design);

// ---------------------------------------------------------------- report
console.log(`\n${"frames".padStart(9)} ${"time".padStart(7)}  ${"bass".padStart(4)}  item`);
for (const { o, share, notes } of report) {
  const what = o.type === "step"
    ? `step ${o.shape}: ${o.count} x ${o.each} f${o.lead ? ` after ${o.lead} f` : ""}, white on ${(o.hits || []).join(", ")}`
    : `${o.type} ${o.clip.name} @ ${r3(o.in)} s${o.type === "wall" ? `, ${o.window.shape}${o.window.shape !== "none" ? ` (${o.pictures} stills, ${o.changes} changes)` : ""}${o.matte ? `, subject ${Math.round((o.cover?.[1] ?? 0) * 100)}% of frame` : ", NO MATTE"}` : ""}${o.enter !== "cut" ? `, enters by ${o.enter}${o.enter === "whip" ? ` (${o.whip})` : ""}` : ""}${o.flash.length ? `, flash on ${o.flash.map(f => o.a + f).join(", ")}` : ""}`;
  console.log(`${`${o.a}-${o.b}`.padStart(9)} ${sec(o.a).toFixed(3).padStart(7)}  ${(share == null ? "-" : `${Math.round(share * 100)}%`).padStart(4)}  ${what}${notes.length ? `  [${notes.join("; ")}]` : ""}`);
}
if (an) console.log(`\ntrack: bass in ${Math.round(an.wallShare * 100)}% of the film${an.cycle ? `, a ${r3(an.cycle)} s cycle (${r1(an.cycle * FPS)} frames)` : ""}, ${Math.round(an.bassShare * 100)}% of the energy below 120 Hz`);
console.log(`audio: ${mixInfo}`);
console.log(`wrote index.html, DESIGN.md, cs/cues.json (${sets.length} frame sets, ${cues.length} sound cues)`);
done();
