#!/usr/bin/env node
// Build a "negative strobe" edit as a HyperFrames composition from a plan file.
//
// Usage: node .claude/skills/negative-strobe/scripts/build-strobe.mjs <project-dir>
//          [--plan ns-plan.json] [--no-audio] [--probe]
//
// The output is a black-and-white film where every picture change is a hard, whole-frame switch:
// clips are cut into pieces of one to a few frames, each piece is graded to paper white and ink
// black, and neighbouring pieces flip between positive and negative. Nothing eases and nothing
// fades. Every piece is a still baked by ffmpeg, so a one-frame flash is exactly one frame.
//
// Writes <project>/index.html, the kit and font in <project>/ns/, the graded stills in
// <project>/ns/media/, the premixed soundtrack in <project>/ns/audio/mix.wav (with stems), the
// state and cue sheet <project>/ns/cues.json, and DESIGN.md. A hand-written index.html or
// DESIGN.md is archived under <project>/archive/ first. Media work is cached in ns/cache/.
// --probe writes three sheets per clip to ns/probe/ and stops: <clip>-frame.png (the source frame
// with a grid and the crop, for `focus`), <clip>.png (the grade at three pivots, for `pivot` and
// `bias`), and <clip>-strip.png (every third frame from the in point, for `at`).
// See ../SKILL.md and ../references/plan-format.md.

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, renameSync, cpSync, statSync, readdirSync, rmSync } from "node:fs";
import { join, resolve, dirname, relative, isAbsolute, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";

const SKILL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT_ROOT = resolve(SKILL, "../../..");
const GENERATED = "<!-- generated by negative-strobe/build-strobe.mjs -->";

const args = process.argv.slice(2);
if (!args.length || args.includes("--help")) {
  console.log("Usage: node build-strobe.mjs <project-dir> [--plan ns-plan.json] [--no-audio] [--probe]");
  process.exit(args.length ? 0 : 1);
}
const project = resolve(args[0]);
const planPath = resolve(project, args.includes("--plan") ? args[args.indexOf("--plan") + 1] : "ns-plan.json");
const noAudio = args.includes("--no-audio");
const probe = args.includes("--probe");

const errors = [], warnings = [];
const fail = m => errors.push(m);
const warn = m => warnings.push(m);
function done() {
  for (const w of warnings.splice(0)) console.warn(`warn: ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`error: ${e}`);
    process.exit(1);
  }
}
if (!existsSync(planPath)) {
  console.error(`No plan at ${relative(process.cwd(), planPath)}. Start from .claude/skills/negative-strobe/templates/ns-plan.example.json.`);
  process.exit(1);
}
let plan;
try { plan = JSON.parse(readFileSync(planPath, "utf8")); } catch (e) { console.error(`${planPath}: ${e.message}`); process.exit(1); }

// ---------------------------------------------------------------- helpers
const r3 = n => Math.round(n * 1000) / 1000;
const r6 = n => Math.round(n * 1e6) / 1e6;
const esc = s => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const isInt = n => Number.isInteger(n);
const even = n => 2 * Math.round(n / 2);
const hash = (...parts) => createHash("sha1").update(parts.map(p => typeof p === "string" ? p : JSON.stringify(p)).join("|")).digest("hex").slice(0, 12);
function projectFile(p, where) {
  if (typeof p !== "string" || !p) { fail(`${where}: expected a file path inside the project.`); return null; }
  if (/^[a-z]+:/i.test(p)) { fail(`${where}: ${p} is a URL; download it into the project first.`); return null; }
  const abs = resolve(project, p);
  if (relative(project, abs).startsWith("..") || isAbsolute(relative(project, abs))) { fail(`${where}: ${p} is outside the project; copy or link it into assets/.`); return null; }
  if (!existsSync(abs)) { fail(`${where}: missing ${p}.`); return null; }
  return abs;
}
function run(cmd, argv, what, opts = {}) {
  const r = spawnSync(cmd, argv, { encoding: opts.binary ? null : "utf8", maxBuffer: 1 << 28, ...opts });
  if (r.status !== 0) {
    const err = (opts.binary ? String(r.stderr || "") : r.stderr || r.stdout || String(r.error || "")).slice(-900);
    fail(`${what} failed: ${err}`);
    done();
  }
  return r;
}
const probeDur = f => Number(spawnSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f], { encoding: "utf8" }).stdout.trim()) || 0;
const cycle = (arr, n) => Array.from({ length: n }, (_, k) => arr[k % arr.length]);
const pick = (v, k, fallback) => Array.isArray(v) ? (v[Math.min(k, v.length - 1)] ?? fallback) : (v ?? fallback);

// ---------------------------------------------------------------- canvas and look
const FPS = Number(plan.fps) || 24;
if (![24, 25, 30].includes(FPS)) fail(`fps must be 24, 25, or 30 (got ${plan.fps}). The style is measured at 24.`);
const FORMATS = { portrait: [1080, 1920], landscape: [1920, 1080], square: [1080, 1080] };
const FORMAT = plan.format || "portrait";
if (!FORMATS[FORMAT]) fail(`format must be one of ${Object.keys(FORMATS).join(", ")}.`);
const [W, H] = FORMATS[FORMAT] || FORMATS.portrait;
const sec = fr => r6(fr / FPS);

// The grade maps luma through a smooth step centred on the clip's pivot. `band` is the width of
// the step as a share of the tonal range: everything below it is ink, everything above is paper.
//   stamp: a near threshold, two tones (a stencil or a photocopy)
//   ink:   the reference's exaggerated S-curve, blown highlights and crushed shadows
//   soft:  a plain black-and-white frame, the breath between hard ones
const look = plan.look || {};
const BANDS = { stamp: 0.06, ink: 0.3, soft: 0.8, ...(look.bands || {}) };
for (const [k, v] of Object.entries(BANDS)) if (!(v > 0 && v <= 1)) fail(`look.bands.${k} must be between 0 and 1.`);
const DEFAULT_GRADE = look.grade ?? "ink";
if (!BANDS[DEFAULT_GRADE]) fail(`look.grade must be one of ${Object.keys(BANDS).join(", ")}.`);
const GRAIN = Number(look.grain ?? 9);
const SEED = Number(look.seed ?? 7);
const BLUR = Number(look.blur ?? 16);
if (look.paper || look.ink || look.tint) warn("look.paper / look.ink / look.tint are ignored: the style is neutral black and white.");

// Pattern letters, one per piece.
const TOKENS = {
  P: { neg: false }, N: { neg: true },
  G: { grade: "soft", neg: false }, g: { grade: "soft", neg: true },
  T: { grade: "stamp", neg: false }, t: { grade: "stamp", neg: true },
  K: { blank: "black" }, W: { blank: "white" },
};
function tokensOf(pattern, where, allowed = "PNGgTtKW") {
  const s = String(pattern ?? "");
  if (!s.length) { fail(`${where}.pattern is empty.`); return ["P"]; }
  const bad = [...s].filter(ch => !allowed.includes(ch));
  if (bad.length) { fail(`${where}.pattern "${s}": unknown letter ${[...new Set(bad)].join(", ")} (use ${[...allowed].join(" ")}).`); return ["P"]; }
  return [...s];
}

// ---------------------------------------------------------------- beat grid
// music.grid { bpm, downbeat } with the downbeat in file seconds. Reel time t plays file time
// music.start + t. Grid units are in beats.
const music = plan.music || {};
const M0 = Number(music.start) || 0;
const GRID = music.grid ? { beat: 60 / Number(music.grid.bpm), down: Number(music.grid.downbeat) || 0, bar: Number(music.grid.beats) || 4 } : null;
if (GRID && !(GRID.beat > 0)) fail("music.grid needs bpm (and downbeat, in file seconds).");
const UNITS = { "16th": 1 / 4, "8th": 1 / 2, beat: 1, bar: GRID?.bar ?? 4 };
const gridK = (t, unit) => (M0 + t - GRID.down) / (GRID.beat * unit);
const gridT = (k, unit) => GRID.down + k * GRID.beat * unit - M0;
const gridNear = (t, unit) => gridT(Math.round(gridK(t, unit)), unit);
const gridNext = (t, unit) => gridT(Math.ceil(gridK(t, unit) - 1e-6), unit);

// ---------------------------------------------------------------- clips
const clips = {};
if (!plan.clips || typeof plan.clips !== "object" || !Object.keys(plan.clips).length) fail("clips must name at least one source.");
for (const [name, c] of Object.entries(plan.clips || {})) {
  const where = `clips.${name}`;
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) fail(`${where}: clip names are lowercase letters, digits, and dashes.`);
  const o = { name, where, src: c.src, abs: projectFile(c.src, `${where}.src`), in: Number(c.in) || 0, zoom: Number(c.zoom) || 1, focus: c.focus || [0.5, 0.5], pivot: c.pivot ?? "auto", bias: Number(c.bias) || 0, crop: c.crop || null, grade: c.grade ?? null, offs: new Set() };
  if (o.grade && !BANDS[o.grade]) fail(`${where}.grade must be one of ${Object.keys(BANDS).join(", ")}.`);
  if (o.zoom < 1) fail(`${where}.zoom must be 1 or more.`);
  if (!Array.isArray(o.focus) || o.focus.length !== 2 || o.focus.some(v => !(v >= 0 && v <= 1))) fail(`${where}.focus must be [x, y], each 0-1 (the part of the frame the crop keeps).`);
  if (o.crop && (!Array.isArray(o.crop) || o.crop.length !== 4 || o.crop.some(v => !(Number(v) >= 0 && Number(v) <= 1)))) fail(`${where}.crop must be [x, y, w, h] fractions of the source frame.`);
  if (o.pivot !== "auto" && !(Number(o.pivot) > 0 && Number(o.pivot) < 1)) fail(`${where}.pivot must be "auto" or a number between 0 and 1.`);
  clips[name] = o;
}
if (!Array.isArray(plan.timeline) || !plan.timeline.length) fail("timeline must be a non-empty array.");
done();

// ---------------------------------------------------------------- timeline -> pieces (all in frames)
// A piece is one state of the picture: a still of one source frame in one grade and polarity, a
// black or white frame, or a type card. Each clip keeps a cursor, so the next time it is used the
// action has moved on.
const pieces = [], items = [];
const clipCursor = {};
let cursor = 0;
function clipRun({ name, tokens, dur, step, grade, at, punch, shift, blur, where, item, group }) {
  const c = clips[name];
  if (!c) { fail(`${where}: no clip named "${name}" (clips: ${Object.keys(clips).join(", ")}).`); return; }
  grade ??= c.grade ?? DEFAULT_GRADE;
  if (!BANDS[grade]) { fail(`${where}.grade must be one of ${Object.keys(BANDS).join(", ")}.`); return; }
  if (!isInt(step) || step < 0) { fail(`${where}.step must be a whole number of frames, 0 or more.`); return; }
  if (at != null) {
    if (!isInt(at) || at < 0) { fail(`${where}.at must be a whole number of frames after the clip's in point.`); return; }
    clipCursor[name] = at;
  }
  const off0 = clipCursor[name] ?? 0;
  let j = 0;
  tokens.forEach((tk, k) => {
    const T = TOKENS[tk], frames = dur[k];
    if (!isInt(frames) || frames < 1) { fail(`${where}: every piece lasts a whole number of frames, 1 or more.`); return; }
    if (T.blank) {
      pieces.push({ kind: T.blank, frame: cursor, frames, item, group, token: tk });
    } else {
      const sh = shift ? pick(shift, j, [0, 0]) : [0, 0];
      const need = 1 + 2 * Math.max(Math.abs(sh[0]), Math.abs(sh[1])) / 100;
      const scale = Math.max(typeof punch === "number" ? 1 + punch * j : Number(pick(punch, j, 1)), need);
      const off = off0 + j * step;
      c.offs.add(off);
      pieces.push({ kind: "still", frame: cursor, frames, clip: name, off, grade: T.grade || grade, neg: !!T.neg, token: tk, scale: r3(scale), shift: sh, blur: Number(Array.isArray(blur) ? (blur[j] ?? 0) : (blur ?? 0)), item, group });
      j++;
    }
    cursor += frames;
  });
  if (j && step > 0) clipCursor[name] = off0 + j * step;
}
plan.timeline.forEach((it, i) => {
  const where = `timeline[${i}]`;
  const item = { n: i + 1, where, start: cursor, label: it.label ?? null, sound: it.sound !== false, cue: it.cue ?? null, rise: !!it.rise, first: pieces.length };
  const eachOf = (n, d = 1) => { const e = it.each ?? d; return Array.from({ length: n }, (_, k) => Number(pick(e, k, d))); };
  const blurOf = () => it.blurIn ? Array.from({ length: Number(it.blurIn) }, (_, k) => r3(BLUR * (Number(it.blurIn) - k) / Number(it.blurIn))) : it.blur;
  if (it.black != null || it.white != null) {
    const kind = it.black != null ? "black" : "white";
    const n = Number(it[kind]);
    if (!isInt(n) || n < 1) fail(`${where}.${kind} must be a whole number of frames.`);
    item.kind = kind;
    pieces.push({ kind, frame: cursor, frames: n || 1, item: i, mute: !!it.mute, token: kind === "black" ? "K" : "W" });
    cursor += n || 1;
  } else if (it.card != null) {
    item.kind = "card";
    let toks = tokensOf(it.pattern ?? "P", where, "PNKW");
    const e = Number(pick(it.each, 0, 1));
    if (it.frames != null) toks = cycle(toks, Math.ceil(Number(it.frames) / e));
    const dur = eachOf(toks.length);
    if (it.frames != null) dur[dur.length - 1] -= dur.reduce((a, b) => a + b, 0) - Number(it.frames);
    toks.forEach((tk, k) => {
      const T = TOKENS[tk];
      if (!isInt(dur[k]) || dur[k] < 1) { fail(`${where}: every piece lasts a whole number of frames, 1 or more.`); return; }
      pieces.push(T.blank ? { kind: T.blank, frame: cursor, frames: dur[k], item: i, token: tk } : { kind: "card", frame: cursor, frames: dur[k], text: String(it.card), sub: it.sub ?? null, size: it.size ?? null, neg: !!T.neg, token: tk, item: i });
      cursor += dur[k];
    });
  } else if (it.burst) {
    // The tutorial's unit: every clip gives `pieces` one-frame pieces, `step` source frames apart,
    // flipping polarity piece by piece.
    if (!Array.isArray(it.burst) || !it.burst.length) fail(`${where}.burst: expected a list of clip names.`);
    item.kind = "burst";
    item.groups = [];
    const refs = (it.burst || []).map(r => typeof r === "string" ? { clip: r } : r);
    const pat = tokensOf(it.pattern ?? "PN", where);
    let bounds = null;
    if (it.on === "grid") {
      // One clip per grid step: each group starts on the whole frame nearest its step.
      if (!GRID) fail(`${where}.on "grid" needs music.grid { bpm, downbeat }.`);
      else {
        const unit = 1 / (Number(it.div) || 4);
        let t0 = gridNear(sec(cursor), unit);
        if (Math.abs(t0 - sec(cursor)) * FPS > 0.75) { warn(`${where}: the burst starts at frame ${cursor}, ${r3((sec(cursor) - t0) * 1000)} ms off the grid. End the item before it with "to" so it lands on a step.`); t0 = sec(cursor); }
        bounds = refs.map((_, k) => Math.round((t0 + k * GRID.beat * unit) * FPS));
        bounds.push(Math.round((t0 + refs.length * GRID.beat * unit) * FPS));
        bounds[0] = cursor;
        for (let k = 1; k < bounds.length; k++) bounds[k] = Math.max(bounds[k], bounds[k - 1] + 1);
      }
    }
    refs.forEach((r, k) => {
      const rw = `${where}.burst[${k}]`;
      const n = bounds ? bounds[k + 1] - bounds[k] : Number(r.pieces ?? it.pieces ?? 3);
      if (!isInt(n) || n < 1) { fail(`${rw}.pieces must be a whole number, 1 or more.`); return; }
      const toks = cycle(r.pattern ? tokensOf(r.pattern, rw) : pat, n);
      item.groups.push({ frame: cursor, clip: r.clip });
      clipRun({ name: r.clip, tokens: toks, dur: bounds ? toks.map(() => 1) : eachOf(n), step: Number(r.step ?? it.step ?? 3), grade: r.grade ?? it.grade, at: r.at, punch: r.punch ?? it.punch, shift: r.shift ?? it.shift, blur: r.blur ?? it.blur, where: rw, item: i, group: k });
    });
  } else if (it.clip) {
    item.kind = "clip";
    let toks = tokensOf(it.pattern ?? "P", where);
    const e = Number(pick(it.each, 0, 1));
    if (it.frames != null) {
      if (!isInt(Number(it.frames)) || Number(it.frames) < 1) fail(`${where}.frames must be a whole number of frames.`);
      toks = cycle(toks, Math.ceil(Number(it.frames) / e));
    }
    const dur = eachOf(toks.length);
    if (it.frames != null) dur[dur.length - 1] -= dur.reduce((a, b) => a + b, 0) - Number(it.frames);
    // "to": the pattern keeps cycling until the next grid line, so what follows lands on the beat.
    // Whole pieces are added; frames left over go to the last one.
    if (it.to != null && GRID && UNITS[it.to]) {
      const pat = tokensOf(it.pattern ?? "P", where), end = cursor + dur.reduce((a, b) => a + b, 0);
      let extra = Math.round(gridNext(sec(end) - 0.5 / FPS, UNITS[it.to]) * FPS) - end;
      for (let k = toks.length; extra >= dur[dur.length - 1]; k++) { toks.push(pat[k % pat.length]); dur.push(dur[dur.length - 1]); extra -= dur[dur.length - 1]; }
      if (extra > 0) dur[dur.length - 1] += extra;
    }
    clipRun({ name: it.clip, tokens: toks, dur, step: Number(it.step ?? 3), grade: it.grade, at: it.at, punch: it.punch, shift: it.shift, blur: blurOf(), where, item: i, group: 0 });
  } else fail(`${where}: expected "clip", "burst", "card", "black", or "white".`);
  // "to" on a card, a blank, or a burst holds its last piece until the next grid line. (A clip
  // item has already cycled its pattern up to the line.)
  if (it.to != null && pieces.length > item.first) {
    if (!GRID) fail(`${where}.to needs music.grid { bpm, downbeat }.`);
    else if (!UNITS[it.to]) fail(`${where}.to must be one of ${Object.keys(UNITS).join(", ")}.`);
    else {
      const target = Math.round(gridNext(sec(cursor) - 0.5 / FPS, UNITS[it.to]) * FPS);
      if (target > cursor) { pieces[pieces.length - 1].frames += target - cursor; cursor = target; }
    }
  }
  item.end = cursor;
  item.last = pieces.length;
  items.push(item);
});
const TOTAL = cursor;
const D = sec(TOTAL);
done();
if (TOTAL < FPS) warn(`The film is ${r3(D)} s: that is a transition, not a reel. Cut the render into another edit, or add holds around the burst (see SKILL.md).`);
const stills = pieces.filter(p => p.kind === "still");
if (stills.length > 400) warn(`${stills.length} stills: long real-time runs ("step": 1) are heavy. Hold frames with "each" or freeze with "step": 0 where the action allows.`);

// ---------------------------------------------------------------- media prep
const nsDir = join(project, "ns");
const mediaDir = join(nsDir, "media");
const cacheDir = join(nsDir, "cache");
mkdirSync(mediaDir, { recursive: true });
mkdirSync(cacheDir, { recursive: true });
const manifestPath = join(cacheDir, "manifest.json");
const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, "utf8")) : {};
const used = new Set();
const saveManifest = () => writeFileSync(manifestPath, JSON.stringify(manifest, null, 1) + "\n");
const stamp = f => { const st = statSync(f); return `${st.size}:${Math.round(st.mtimeMs)}`; };
const rel = f => relative(project, f);
const cached = (key, out) => { used.add(rel(out)); return manifest[rel(out)] === key && existsSync(out); };
const remember = (key, out) => { manifest[rel(out)] = key; };

// Source frame rate, so a piece's time snaps to a whole source frame; the seek lands a quarter
// frame early so the wanted frame is the first one decoded.
const fpsCache = {}, durCache = {};
function srcFps(abs) {
  if (fpsCache[abs]) return fpsCache[abs];
  const r = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=r_frame_rate", "-of", "csv=p=0", abs], { encoding: "utf8" }).stdout.trim();
  const [a, b] = r.split("/").map(Number);
  return (fpsCache[abs] = a && b ? a / b : FPS);
}
const srcDur = abs => (durCache[abs] ??= probeDur(abs));
const snap = (abs, t) => { const f = srcFps(abs); return Math.round(t * f) / f; };
const seekAt = (abs, t) => Math.max(0, t - 0.25 / srcFps(abs));
const timeOf = (c, off) => snap(c.abs, c.in + off / FPS);

// Every clip is cropped to the canvas around its focus point (and zoomed), then made grey. A
// piece's punch and shift are part of the same crop, so a stepped zoom is graded after it is
// scaled and keeps its hard edges.
function base(c, scale = 1, shift = [0, 0]) {
  const cw = even(W * c.zoom * scale), ch = even(H * c.zoom * scale);
  const x = shift[0] ? `'clip((iw-${W})*${c.focus[0]}-(${r3(W * shift[0] / 100)}),0,iw-${W})'` : `(iw-${W})*${c.focus[0]}`;
  const y = shift[1] ? `'clip((ih-${H})*${c.focus[1]}-(${r3(H * shift[1] / 100)}),0,ih-${H})'` : `(ih-${H})*${c.focus[1]}`;
  return [
    c.crop ? `crop=w=iw*${c.crop[2]}:h=ih*${c.crop[3]}:x=iw*${c.crop[0]}:y=ih*${c.crop[1]}` : null,
    `scale=${cw}:${ch}:force_original_aspect_ratio=increase:flags=lanczos`,
    `crop=${W}:${H}:${x}:${y}`,
    "format=gray",
  ].filter(Boolean).join(",");
}
// The pivot is the luma that lands on mid grey. "auto" is Otsu's threshold over the frames the
// plan uses: the split that best separates the dark shape from the light ground.
function otsu(hist) {
  const total = hist.reduce((a, b) => a + b, 0);
  let sum = 0;
  for (let i = 0; i < 256; i++) sum += i * hist[i];
  let wB = 0, sumB = 0, best = -1, thr = 127;
  for (let i = 0; i < 256; i++) {
    wB += hist[i];
    if (!wB) continue;
    const wF = total - wB;
    if (!wF) break;
    sumB += i * hist[i];
    const mB = sumB / wB, mF = (sum - sumB) / wF;
    const v = wB * wF * (mB - mF) * (mB - mF);
    if (v > best) { best = v; thr = i; }
  }
  return thr / 255;
}
function pivotOf(c) {
  if (c.pivotValue != null) return c.pivotValue;
  let p;
  if (c.pivot !== "auto") p = Number(c.pivot);
  else {
    const offs = [...c.offs].sort((a, b) => a - b);
    const sample = offs.length ? [...new Set([offs[0], offs[offs.length >> 1], offs[offs.length - 1]])] : [0];
    const key = hash(c.abs, stamp(c.abs), base(c), sample.map(o => r6(timeOf(c, o))), "otsu1");
    const slot = `pivot:${c.name}`;
    used.add(slot);
    if (manifest[slot]?.key === key) p = manifest[slot].v;
    else {
      const hist = new Array(256).fill(0);
      for (const o of sample) {
        const r = spawnSync("ffmpeg", ["-v", "error", "-ss", String(r6(seekAt(c.abs, timeOf(c, o)))), "-i", c.abs, "-frames:v", "1", "-vf", `${base(c)},scale=96:-2`, "-f", "rawvideo", "-"], { maxBuffer: 1 << 22 });
        for (const v of r.stdout || []) hist[v]++;
      }
      if (!hist.some(Boolean)) { fail(`${c.where}: cannot read a frame of ${c.src} at ${r3(timeOf(c, sample[0]))} s.`); done(); }
      p = r3(otsu(hist));
      manifest[slot] = { key, v: p };
    }
  }
  c.auto = p;
  return (c.pivotValue = Math.min(0.97, Math.max(0.03, r3(p + c.bias))));
}
// The grade: an optional blur (before the curve, so a blurred frame still has hard edges), grain
// (so the edge of a shape breaks into specks, like a photocopy), then the smooth step.
const curve = (pivot, band, neg) => `lut=y='${neg ? "255-" : ""}255*pow(st(0,clip((val/255-(${r6(pivot - band / 2)}))/${band},0,1)),2)*(3-2*ld(0))'`;
function gradeVf(c, grade, neg, blur, off, scale, shift) {
  return [
    base(c, scale, shift),
    blur > 0 ? `gblur=sigma=${blur}` : null,
    GRAIN > 0 ? `noise=c0s=${GRAIN}:c0f=u:c0_seed=${(SEED * 7919 + off * 104729 + 1) % 2147483647}` : null,
    curve(pivotOf(c), BANDS[grade], neg),
    "format=yuvj420p",
  ].filter(Boolean).join(",");
}
function still(p) {
  const c = clips[p.clip];
  const t = timeOf(c, p.off);
  if (t > srcDur(c.abs) - 1 / srcFps(c.abs) + 1e-6) {
    fail(`clip "${p.clip}": frame ${p.off} after its in point is ${r3(t)} s, past the end of ${c.src} (${r3(srcDur(c.abs))} s). Lower "in", "at", or "step".`);
    return null;
  }
  const tag = v => String(v).replace("-", "m").replace(".", "_");
  const out = join(mediaDir, `${p.clip}-${String(p.off).padStart(4, "0")}-${p.grade}${p.neg ? "n" : "p"}${p.blur ? `-b${tag(p.blur)}` : ""}${p.scale !== 1 ? `-z${tag(p.scale)}` : ""}${p.shift[0] || p.shift[1] ? `-x${tag(p.shift[0])}y${tag(p.shift[1])}` : ""}.jpg`);
  const vf = gradeVf(c, p.grade, p.neg, p.blur, p.off, p.scale, p.shift);
  const key = hash(c.abs, stamp(c.abs), r6(t), vf, "s1");
  if (!cached(key, out)) {
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, t))), "-i", c.abs, "-frames:v", "1", "-vf", vf, "-q:v", "2", out], `still ${basename(out)}`);
    remember(key, out);
  }
  // A still that is nearly all one tone has no shape to read: the pivot sits outside the subject.
  const slot = `tone:${rel(out)}`;
  used.add(slot);
  if (manifest[slot]?.key !== key) {
    const r = spawnSync("ffmpeg", ["-v", "error", "-i", out, "-vf", "scale=48:-2,format=gray", "-f", "rawvideo", "-"], { maxBuffer: 1 << 22 });
    let s = 0; for (const v of r.stdout || []) s += v;
    manifest[slot] = { key, v: r3(s / Math.max(1, (r.stdout || []).length) / 255) };
  }
  const paper = manifest[slot].v;
  if (p.grade !== "soft" && (paper < 0.04 || paper > 0.96)) (c.flat ||= new Set()).add(p.off);
  return out;
}

// Probe sheets for choosing the pivot and the in point. No stills are built.
if (probe) {
  const pdir = join(nsDir, "probe");
  mkdirSync(pdir, { recursive: true });
  for (const c of Object.values(clips)) {
    const p = pivotOf(c), t = timeOf(c, [...c.offs].sort((a, b) => a - b)[0] ?? 0);
    const tiles = [null, [p - 0.1, "ink"], [p, "ink"], [p + 0.1, "ink"], [p, "stamp"]];
    const graph = `[0:v]${base(c)},split=${tiles.length}${tiles.map((_, k) => `[s${k}]`).join("")};` +
      tiles.map((tl, k) => `[s${k}]${tl ? `${curve(tl[0], BANDS[tl[1]], false)},` : ""}scale=${even(W / 4)}:-2[t${k}]`).join(";") +
      `;${tiles.map((_, k) => `[t${k}]`).join("")}hstack=inputs=${tiles.length}[out]`;
    const sheet = join(pdir, `${c.name}.png`);
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, t))), "-i", c.abs, "-frames:v", "1", "-filter_complex", graph, "-map", "[out]", sheet], `probe ${c.name}`);
    const strip = join(pdir, `${c.name}-strip.png`);
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, timeOf(c, 0)))), "-i", c.abs, "-vf",
      `fps=${FPS},select='not(mod(n\\,3))',${base(c)},${curve(p, BANDS.ink, false)},scale=${even(W / 6)}:-2,tile=12x2`, "-frames:v", "1", strip], `strip ${c.name}`);
    // The whole source frame with a 10% grid (red at 50%) and the canvas crop boxed: read the
    // subject's position off it for "focus".
    const frame = join(pdir, `${c.name}-frame.png`);
    const pr = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height", "-of", "csv=p=0", c.abs], { encoding: "utf8" }).stdout.trim().split(",").map(Number);
    const sw = pr[0] * (c.crop ? c.crop[2] : 1), sh = pr[1] * (c.crop ? c.crop[3] : 1);
    const k = Math.max(W / sw, H / sh) * c.zoom, bw = W / k / sw, bh = H / k / sh;
    const bx = (1 - bw) * c.focus[0], by = (1 - bh) * c.focus[1];
    const fw = 960, fh = even(960 * sh / sw);
    run("ffmpeg", ["-v", "error", "-y", "-ss", String(r6(seekAt(c.abs, t))), "-i", c.abs, "-frames:v", "1", "-vf",
      `${c.crop ? `crop=w=iw*${c.crop[2]}:h=ih*${c.crop[3]}:x=iw*${c.crop[0]}:y=ih*${c.crop[1]},` : ""}scale=${fw}:${fh},drawgrid=w=${fw / 10}:h=${fh / 10}:t=1:c=white@0.5,drawgrid=w=${fw / 2}:h=${fh / 2}:t=2:c=red@0.8,drawbox=x=${Math.round(bx * fw)}:y=${Math.round(by * fh)}:w=${Math.round(bw * fw)}:h=${Math.round(bh * fh)}:t=4:c=yellow`, frame], `frame ${c.name}`);
    console.log(`probe: ${rel(frame)}: the source frame, grid lines every 10%, the crop in yellow (focus ${c.focus.join(", ")}, zoom ${c.zoom})`);
    console.log(`probe: ${rel(sheet)}: grey, ink at pivot ${r3(p - 0.1)}, ${r3(p)}${c.pivot === "auto" ? " (auto)" : ""}, ${r3(p + 0.1)}, stamp at ${r3(p)}`);
    console.log(`probe: ${rel(strip)}: every third frame from ${c.in} s ("at": 0, 3, 6, ... 69), in ink`);
  }
  saveManifest();
  done();
  process.exit(0);
}

console.log(`negative strobe: ${items.length} items, ${pieces.length} pieces, ${TOTAL} frames = ${r3(D)} s at ${FPS} fps (${W}x${H}). Baking stills...`);
for (const p of stills) p.file = still(p);
saveManifest();
for (const c of Object.values(clips)) {
  if (c.flat) warn(`clip "${c.name}": ${c.flat.size} of its ${c.offs.size} frames come out over 96% one tone at pivot ${c.pivotValue}${c.pivot === "auto" ? " (auto)" : ""}, so there is no shape to read. Run --probe and set clips.${c.name}.pivot or bias.`);
}
done();

// ---------------------------------------------------------------- compile the film
// One element per still, per card face, and one white frame. The timeline only switches them on
// and off, on whole frames. Zooms, shifts, blur, and the negative are all baked into the stills,
// so the page never transforms or filters the picture.
const sets = [];   // [frame, selector, props]
const nodes = [];
const src = f => rel(f).split("\\").join("/");
const cardSize = (text, size) => {
  if (size) return Number(size);
  const longest = Math.max(1, ...String(text).split("\n").map(l => l.length));
  return Math.round(Math.min(H * 0.16, (W * 0.84) / (0.74 * longest)));
};
const els = new Map();   // key -> { id, first }
for (const p of pieces) {
  if (p.kind === "black") continue;
  const key = p.kind === "still" ? `s:${p.file}` : p.kind === "card" ? `c:${p.neg}:${p.size}:${p.text}:${p.sub}` : "w";
  if (!els.has(key)) els.set(key, { id: `${p.kind[0]}${els.size + 1}`, first: p });
  p.id = els.get(key).id;
}
for (const el of els.values()) {
  const p = el.first, on = p.frame === 0 ? ' style="opacity:1"' : "";
  if (p.kind === "white") nodes.push(`<div id="${el.id}" class="ns-white"${on}></div>`);
  else if (p.kind === "card") {
    const fs = cardSize(p.text, p.size);
    nodes.push(`<div id="${el.id}" class="ns-card${p.neg ? " neg" : ""}"${on}><div class="ns-card-word" style="font-size:${fs}px">${esc(p.text.toUpperCase()).replace(/\n/g, "<br>")}</div>${p.sub ? `<div class="ns-card-sub" style="font-size:${Math.round(fs * 0.17)}px">${esc(String(p.sub).toUpperCase())}</div>` : ""}</div>`);
  } else nodes.push(`<img id="${el.id}" class="ns-still" src="${src(p.file)}" decoding="sync" alt=""${on}>`);
}
pieces.forEach((p, i) => {
  if (p.kind === "black") return;
  const prev = pieces[i - 1], next = pieces[i + 1];
  // A piece that follows itself (the same still held again) needs no switch.
  if (p.frame > 0 && prev?.id !== p.id) sets.push([p.frame, `#${p.id}`, { opacity: 1 }]);
  if (p.frame + p.frames < TOTAL && next?.id !== p.id) sets.push([p.frame + p.frames, `#${p.id}`, { opacity: 0 }]);
});

// ---------------------------------------------------------------- sound cues
// hit:  the first frame of a burst, and any picture that returns from a blank frame
// tick: every other clip change
// flip: a polarity flip inside a clip, when both pieces last two frames or more
// buzz: a bed under every run of one-frame pieces, cut hard at both ends
// rise: ends on the first frame of an item marked "rise"
const cues = [];
const cue = (fr, kind, why, extra = {}) => cues.push({ frame: fr, at: sec(fr), kind, why, ...extra });
const isBlank = p => !p || p.kind === "black" || p.kind === "white";
items.forEach(it => {
  if (!it.sound) return;
  const own = pieces.slice(it.first, it.last);
  const firstPic = own.find(p => !isBlank(p));
  if (!firstPic) return;
  const tag = `item ${it.n}${it.label ? ` (${it.label})` : ""}`;
  const afterBlank = isBlank(pieces[pieces.indexOf(firstPic) - 1]);
  if (it.rise) cue(firstPic.frame, "rise", `${tag} rise`, { align: "end" });
  if (it.kind === "burst") {
    it.groups.forEach((g, k) => cue(g.frame, k === 0 ? (it.cue ?? "hit") : "tick", `${tag} ${k === 0 ? "start" : "clip"} ${g.clip}`));
  } else {
    cue(firstPic.frame, it.cue ?? (it.kind === "card" || afterBlank ? "hit" : "tick"), `${tag} ${it.kind === "card" ? "card" : firstPic.clip}`);
    own.forEach((p, k) => {
      const q = own[k - 1];
      if (!q || isBlank(p) || p === firstPic) return;
      if (p.frames >= 2 && q.frames >= 2 && (isBlank(q) || q.neg !== p.neg || q.grade !== p.grade)) cue(p.frame, isBlank(q) ? "hit" : "flip", `${tag} ${isBlank(q) ? "return" : "flip"}`);
    });
  }
});
// Runs of one-frame pieces: six frames or more get the bed.
for (let i = 0; i < pieces.length;) {
  let j = i;
  while (j < pieces.length && pieces[j].frames === 1 && !isBlank(pieces[j]) && items[pieces[j].item].sound) j++;
  if (j - i >= 6) cue(pieces[i].frame, "buzz", `strobe run of ${j - i} frames`, { span: sec(j - i) });
  i = Math.max(j, i + 1);
}
cues.sort((a, b) => a.frame - b.frame);

// ---------------------------------------------------------------- audio
// An effect's level is its loudest 10 ms against the bed's loudest 10 ms, in dB. The bed is the
// sound of this style; the effects only mark the picture.
const SFX_KINDS = { hit: -10, tick: -14, flip: -16, buzz: -22, rise: -18 };
let audioTag = "", mixInfo = "silent (no music or sfx in the plan)";
const audioDir = join(nsDir, "audio");
mkdirSync(join(audioDir, "stems"), { recursive: true });
const measure = f => {
  const e = spawnSync("ffmpeg", ["-hide_banner", "-nostats", "-i", f, "-af", "ebur128=peak=true", "-f", "null", "-"], { encoding: "utf8" }).stderr;
  const num = re => Number(((e.match(re) || []).pop() || "").match(/-?[\d.]+/)?.[0]);
  return { I: num(/I:\s+-?[\d.]+ LUFS/g), TP: num(/Peak:\s+-?[\d.]+ dBFS/g) };
};
function analyze(file, span = []) {
  const r = spawnSync("ffmpeg", ["-v", "error", ...span, "-i", file, "-ac", "1", "-ar", "22050", "-f", "f32le", "-"], { maxBuffer: 1 << 29 });
  if (r.status !== 0) { fail(`ffmpeg could not decode ${rel(file)}`); return null; }
  const b = r.stdout, x = new Float32Array(b.buffer.slice(b.byteOffset, b.byteOffset + b.length - (b.length % 4)));
  const hop = 220, n = Math.floor(x.length / hop), e = new Float64Array(n);
  let amp = 1e-6;
  for (let i = 0; i < n; i++) { let s = 0; for (let j = 0; j < hop; j++) { const v = x[i * hop + j]; s += v * v; if (Math.abs(v) > amp) amp = Math.abs(v); } e[i] = Math.sqrt(s / hop); }
  let pk = 0; for (let i = 1; i < n; i++) if (e[i] > e[pk]) pk = i;
  let on = 0; while (on < pk && e[on] < e[pk] * 0.1) on++;
  return { len: x.length / 22050, peak: pk / 100, onset: on / 100, amp, loud: e[pk] || 1e-6 };
}
const mutes = pieces.filter(p => p.kind === "black" && p.mute).map(p => ({ a: sec(p.frame), b: sec(p.frame + p.frames) }));
const placed = [];
if (!noAudio && (music.file || plan.sfx)) {
  const musicAbs = music.file ? projectFile(music.file, "music.file") : null;
  done();
  const bedLoud = musicAbs ? (analyze(musicAbs, ["-ss", String(M0), "-t", String(D)])?.loud ?? 0.5) * Number(music.gain ?? 1) : 0.5;
  const files = {};
  for (const [k, v] of Object.entries(plan.sfx || {})) {
    if (!(k in SFX_KINDS)) { warn(`sfx.${k} is not a cue kind (${Object.keys(SFX_KINDS).join(", ")}); ignored.`); continue; }
    const spec = typeof v === "string" ? { file: v } : v;
    const abs = projectFile(spec.file, `sfx.${k}`);
    if (!abs) continue;
    const a = analyze(abs);
    if (!a) continue;
    const level = Number(spec.level ?? SFX_KINDS[k]);
    files[k] = { abs, level, gain: (bedLoud * Math.pow(10, level / 20) / a.loud) * Number(spec.gain ?? 1), trim: Number(spec.trim) || 0, cut: spec.len != null ? Number(spec.len) : null, ...a };
  }
  done();
  const missing = [...new Set(cues.map(c => c.kind))].filter(k => !files[k]);
  if (missing.length) warn(`No sfx for ${missing.join(", ")}; those cues are silent. Add them to plan.sfx (see references/sound-design.md).`);
  const inputs = [], chains = [], sfxL = [], bedL = [];
  const add = f => { inputs.push("-i", f); return inputs.length / 2 - 1; };
  cues.forEach((c, i) => {
    const f = files[c.kind];
    if (!f) return;
    let from, start, len, fadeIn = 0, fade;
    if (c.align === "end") {
      // The file's tail ends exactly on the cue: a rise into the first frame of a burst.
      len = Math.min(f.cut ?? f.len, f.len - f.trim, c.at);
      from = f.len - len;
      start = c.at - len;
      fadeIn = Math.min(0.2, len / 2);
      fade = 0.008;
    } else if (c.span) {
      // A bed for a strobe run: it starts with the first flash and stops dead with the last.
      from = Math.max(f.trim, f.onset - 0.004);
      start = c.at;
      len = Math.min(c.span, f.len - from);
      fade = 0.006;
    } else {
      // The file's onset lands on the cue's frame: the sound starts with the picture change.
      from = Math.max(f.trim, f.onset - 0.004);
      start = Math.max(0, c.at - (f.onset - from));
      len = Math.min(f.cut ?? Infinity, f.len - from);
      fade = Math.min(0.12, len * 0.4);
    }
    len = Math.max(0.02, Math.min(len, D - start));
    const k = add(f.abs);
    chains.push(`[${k}:a]atrim=start=${r3(from)}:duration=${r3(len)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${(f.gain * (c.gain ?? 1)).toFixed(3)}${fadeIn ? `,afade=t=in:d=${r3(fadeIn)}` : ""},afade=t=out:st=${r3(Math.max(0, len - fade))}:d=${r3(fade)},adelay=${Math.round(start * 1000)}:all=1[c${i}]`);
    sfxL.push(`[c${i}]`);
    placed.push({ ...c, start: r3(start), from: r3(from), len: r3(len), file: rel(f.abs) });
  });
  if (musicAbs) {
    // The track plays from music.start. It is silent across every black marked "mute" (the
    // picture and the sound stop together), and it stops dead on the last frame unless
    // music.fade asks for a fade.
    const mg = Number(music.gain ?? 1), mDur = probeDur(musicAbs);
    const endFade = r3(Math.min((Number(music.fade) || 0) / FPS, D / 4)) || 0.008;
    if (M0 + D > mDur + 0.01) fail(`music: ${r3(D)} s from ${M0} s runs past the end of the track (${r3(mDur)} s).`);
    let spans = [{ a: 0, b: D, fin: 0.008, fout: endFade }];
    for (const m of mutes) {
      spans = spans.flatMap(sp => {
        if (m.b <= sp.a || m.a >= sp.b) return [sp];
        const out = [];
        if (m.a > sp.a) out.push({ ...sp, b: m.a, fout: 0.008 });
        if (m.b < sp.b) out.push({ ...sp, a: m.b, fin: 0.004 });
        return out;
      });
    }
    spans.forEach((sp, i) => {
      const k = add(musicAbs), tag = `m${i + 1}`, len = sp.b - sp.a;
      chains.push(`[${k}:a]atrim=start=${r6(M0 + sp.a)}:duration=${r6(len)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${mg.toFixed(3)},afade=t=in:d=${sp.fin},afade=t=out:st=${r6(Math.max(0, len - sp.fout))}:d=${sp.fout},adelay=${Math.round(sp.a * 1000)}:all=1[${tag}]`);
      bedL.push(`[${tag}]`);
    });
    placed.push({ kind: "music", file: rel(musicAbs), start: 0, from: M0, mutes, grid: music.grid ?? null });
  }
  done();
  if (sfxL.length || bedL.length) {
    const raw = join(audioDir, "mix-raw.wav"), out = join(audioDir, "mix.wav");
    const bus = (ls, tag) => `${ls.join("")}amix=inputs=${ls.length}:normalize=0:duration=longest,apad=whole_dur=${D},atrim=0:${D}[${tag}]`;
    const graph = [...chains], layers = [];
    if (bedL.length) { graph.push(bus(bedL, "bedbus")); layers.push("bed"); }
    if (sfxL.length) { graph.push(bus(sfxL, "sfxbus")); layers.push("sfx"); }
    layers.forEach(L => graph.push(`[${L}bus]asplit=2[${L}m][${L}]`));
    graph.push(`${layers.map(L => `[${L}m]`).join("")}amix=inputs=${layers.length}:normalize=0:duration=longest,atrim=0:${D}[mix]`);
    const stemMaps = layers.flatMap(L => ["-map", `[${L}]`, "-ar", "48000", "-c:a", "pcm_s16le", join(audioDir, "stems", `${L}.wav`)]);
    run("ffmpeg", ["-v", "error", "-y", ...inputs, "-filter_complex", graph.join(";"), "-map", "[mix]", "-ar", "48000", "-c:a", "pcm_s16le", raw, ...stemMaps], "ffmpeg mix");
    // -14 LUFS through a limiter at 4x the sample rate (catches inter-sample peaks), ceiling
    // -5 dBFS so the renderer's AAC encode stays under -1 dBTP. Repeated until within 0.25 LU.
    // The mix opens over 20 ms (half a frame): a bed that starts at full level on sample 0 makes
    // the encoder overshoot by 4-5 dB on its first block.
    const m0 = measure(raw);
    let gainDb = Number.isFinite(m0.I) ? -14 - m0.I : 0, got = null;
    for (let pass = 0; pass < 3; pass++) {
      const af = `volume=${gainDb.toFixed(2)}dB,afade=t=in:d=0.02,aresample=192000,alimiter=limit=0.56:attack=1:release=50:level=false,aresample=48000`;
      run("ffmpeg", ["-v", "error", "-y", "-i", raw, "-af", af, "-ar", "48000", "-c:a", "pcm_s16le", out], "loudness pass");
      got = measure(out);
      if (!Number.isFinite(got.I) || Math.abs(got.I + 14) < 0.25) break;
      gainDb += -14 - got.I;
    }
    if (got && got.TP > -4) warn(`mix.wav peaks at ${got.TP} dBTP; after the AAC encode it may pass -1 dBTP.`);
    audioTag = `<audio id="ns-mix" src="ns/audio/mix.wav" data-start="0" data-duration="${D}" data-track-index="0" data-volume="1"></audio>`;
    // How far the effects sit under the bed. They mark the picture; they must not lead the mix.
    let under = "";
    if (bedL.length && sfxL.length) {
      const gap = r3(measure(join(audioDir, "stems", "bed.wav")).I - measure(join(audioDir, "stems", "sfx.wav")).I);
      under = `, sfx ${gap} LU under the bed`;
      if (gap < 6) warn(`The effects sit only ${gap} LU under the bed. Lower their "level" (or raise music.gain): the track carries this style.`);
    }
    mixInfo = `ns/audio/mix.wav (${placed.filter(p => p.kind !== "music").length} sfx cues${musicAbs ? " + music" : ""}${under}, ${m0.I} LUFS -> ${got?.I} LUFS, ${got?.TP} dBTP)`;
  }
}

// ---------------------------------------------------------------- pace and grid report
// A state change is any frame where the picture is replaced. A flip is a change of polarity on
// the same clip: the largest change a frame can make without moving a single edge.
const changes = pieces.slice(1).map(p => p.frame);
const flips = pieces.filter((p, i) => i && p.kind === "still" && pieces[i - 1].kind === "still" && pieces[i - 1].clip === p.clip && pieces[i - 1].neg !== p.neg).length;
let peak = 0;
for (const f of changes) peak = Math.max(peak, changes.filter(g => g >= f && g < f + FPS).length);
const oneFrame = pieces.filter(p => p.frames === 1).length;
const longest = Math.max(...pieces.map(p => p.frames));
if (GRID) {
  // Bursts and hits should sit on the grid. A whole frame is 1000/fps ms, so half a frame is the
  // best a cut can do; more than a frame off reads as late.
  for (const c of cues.filter(c => c.kind === "hit")) {
    const off = (c.at - gridNear(c.at, 1 / 4)) * 1000;
    if (Math.abs(off) > 1000 / FPS) warn(`hit at frame ${c.frame} (${c.why}) is ${r3(off)} ms off the nearest sixteenth. Use "to" on the item before it.`);
  }
}

writeFileSync(join(nsDir, "cues.json"), JSON.stringify({
  fps: FPS, frames: TOTAL, duration: D, width: W, height: H,
  states: pieces.map(p => ({ frame: p.frame, frames: p.frames, kind: p.kind, token: p.token, item: p.item + 1, ...(p.kind === "still" ? { clip: p.clip, off: p.off, grade: p.grade, neg: p.neg, file: src(p.file), scale: p.scale } : {}), ...(p.kind === "card" ? { neg: p.neg } : {}) })),
  items: items.map(it => ({ n: it.n, kind: it.kind, start: it.start, end: it.end, label: it.label })),
  pace: { changes: changes.length, perSecond: r3(changes.length / D), peakPerSecond: peak, flips, oneFramePieces: oneFrame, longestHold: longest },
  cues: placed.length ? placed : cues,
}, null, 2) + "\n");

// ---------------------------------------------------------------- kit, fonts, gsap
cpSync(join(SKILL, "assets", "fonts"), join(nsDir, "fonts"), { recursive: true });
copyFileSync(join(SKILL, "assets", "ns-kit.css"), join(nsDir, "ns-kit.css"));
copyFileSync(join(SKILL, "assets", "ns-kit.js"), join(nsDir, "ns-kit.js"));
const gsapLocal = join(project, "assets", "gsap.min.js");
if (!existsSync(gsapLocal)) {
  const g = join(KIT_ROOT, "node_modules/gsap/dist/gsap.min.js");
  if (!existsSync(g)) { fail("assets/gsap.min.js is missing and node_modules/gsap is not installed (run npm ci in the kit root)."); done(); }
  mkdirSync(dirname(gsapLocal), { recursive: true });
  copyFileSync(g, gsapLocal);
}
// Drop generated stills the plan no longer uses.
for (const f of readdirSync(mediaDir)) {
  const p = join(mediaDir, f);
  if (!used.has(rel(p))) { rmSync(p, { recursive: true, force: true }); delete manifest[rel(p)]; }
}
for (const k of Object.keys(manifest)) if (/^(pivot|tone):/.test(k) && !used.has(k)) delete manifest[k];
saveManifest();

// ---------------------------------------------------------------- index.html
const stampNow = new Date().toISOString().replace(/[:.]/g, "-");
function archive(file) {
  const p = join(project, file);
  if (!existsSync(p)) return;
  const text = readFileSync(p, "utf8");
  if (text.includes("generated by negative-strobe")) return;
  mkdirSync(join(project, "archive"), { recursive: true });
  renameSync(p, join(project, "archive", `${stampNow}-${file}`));
  console.log(`Archived the previous ${file} to archive/${stampNow}-${file}`);
}
archive("index.html");
archive("DESIGN.md");

const cfg = { fps: FPS, duration: D, root: "main", sets };
const html = `<!doctype html>
${GENERATED}
<html lang="en"><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' data:; img-src 'self' data: blob:; font-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self' data: blob:; object-src 'none'; base-uri 'self'; form-action 'none'">
<meta name="viewport" content="width=${W}, height=${H}">
<title>${esc(plan.title || "Negative strobe edit")}</title>
<link rel="stylesheet" href="ns/ns-kit.css">
<style>
@font-face{font-family:"NS Archivo";src:url("ns/fonts/Archivo-Latin-VF.ttf") format("truetype");font-weight:100 900;font-stretch:62% 125%;font-display:block}
html,body{margin:0;padding:0;background:#000}
#main{--ns-w:${W}px;--ns-h:${H}px}
</style></head><body>
<div id="main" class="ns-film" data-composition-id="main" data-start="0" data-duration="${D}" data-fps="${FPS}" data-width="${W}" data-height="${H}">
<div id="ns-stage" class="ns-stage">
${nodes.join("\n")}
</div>
${audioTag}
<script src="assets/gsap.min.js"></script>
<script src="ns/ns-kit.js"></script>
<script>
window.NS_CONFIG = ${JSON.stringify(cfg)};
(function () {
  var tl = NS.build(window.NS_CONFIG);
  window.__timelines = window.__timelines || {};
  window.__timelines["main"] = tl;
})();
</script>
</div>
</body></html>
`;
writeFileSync(join(project, "index.html"), html);

// ---------------------------------------------------------------- DESIGN.md
const hasCard = pieces.some(p => p.kind === "card");
const design = `${GENERATED.replace("<!--", "<!-- regenerated on every build;")}
# ${plan.title || "Negative strobe edit"}: negative strobe

## Style Prompt

A black-and-white strobe edit at ${W}x${H}. Every frame is two tones: paper white and ink black,
with the highlights blown out and the shadows crushed until the subject is a shape. Clips are cut
into pieces of one to a few frames, and neighbouring pieces flip between positive and negative, so
the picture changes as much as a frame can while every edge stays where it was. Nothing eases and
nothing fades. Cold, loud, and anonymous: a photocopy that moves.

## Colors

- #000000 and #ffffff only. The footage is neutral grey before the curve; there is no tint.
- Default grade "${DEFAULT_GRADE}" (band ${BANDS[DEFAULT_GRADE]}), grain ${GRAIN}.

## Typography

- ${hasCard ? "Type cards only: Archivo width 125, weight 800, upper case, black on white or white on black." : "None. The marks on screen are the ones in the footage."}

## Motion

- ${FPS} fps. Every change is a whole-frame switch; there are no tweens.
- ${pieces.length} pieces over ${r3(D)} s: ${r3(changes.length / D)} changes per second, ${peak} in the busiest second, ${flips} polarity flips, longest hold ${longest} frames.
- Camera moves are stepped: a scale or position jump per piece, never a glide.

## What NOT to Do

- Do not add colour, a tint, or a gradient.
- Do not ease, fade, crossfade, or blur between pieces.
- Do not add captions, lower thirds, or stickers.
- Do not let a strobe run pass about one second without a hold or a black frame.
- Do not post it without a flashing-images warning.
`;
writeFileSync(join(project, "DESIGN.md"), design);

// ---------------------------------------------------------------- report
console.log(`\n${"frame".padStart(6)} ${"time".padStart(7)}  item`);
for (const it of items) {
  const own = pieces.slice(it.first, it.last);
  const pat = own.map(p => p.token + (p.frames > 1 ? p.frames : "")).join(it.kind === "burst" ? "" : " ");
  const what = it.kind === "burst" ? `burst ${it.groups.map(g => g.clip).join(" ")}` : it.kind === "clip" ? `${own.find(p => p.clip)?.clip ?? ""} @${own.find(p => p.clip)?.off ?? 0}` : it.kind;
  console.log(`${String(it.start).padStart(6)} ${sec(it.start).toFixed(3).padStart(7)}  ${it.n}. ${it.end - it.start}f ${what}  [${pat}]${it.label ? `  ${it.label}` : ""}`);
}
console.log(`\npivots: ${Object.values(clips).filter(c => c.pivotValue != null).map(c => `${c.name} ${c.pivotValue}${c.pivot === "auto" ? ` (auto ${c.auto}${c.bias ? `, bias ${c.bias}` : ""})` : ""}`).join(", ")}`);
console.log(`pace: ${changes.length} changes in ${r3(D)} s (${r3(changes.length / D)}/s, ${peak} in the busiest second), ${flips} polarity flips, ${oneFrame} one-frame pieces, longest hold ${longest} frames`);
if (GRID) console.log(`grid: ${r3(60 / GRID.beat)} BPM, a sixteenth is ${r3(GRID.beat / 4 * FPS)} frames; hits at ${cues.filter(c => c.kind === "hit").map(c => `${c.frame} (${r3((c.at - gridNear(c.at, 1 / 4)) * 1000)} ms)`).join(", ")}`);
console.log(`audio: ${mixInfo}`);
console.log(`wrote index.html, DESIGN.md, ns/cues.json (${new Set(stills.map(p => p.file)).size} stills, ${sets.length} frame sets, ${cues.length} sound cues)`);
if (peak > 3) console.log(`note: this is flashing imagery (${peak} changes in one second). Post it with a flashing-images warning.`);
done();
