#!/usr/bin/env node
// Build an app launch reel (chaptered product motion reel) as a HyperFrames composition from a
// plan file.
//
// Usage: node .claude/skills/app-launch-reel/scripts/build-reel.mjs <project-dir> [--plan alr-plan.json] [--no-audio]
//
// Writes <project>/index.html, the runtime kit and fonts in <project>/alr/, the premixed
// soundtrack in <project>/alr/audio/mix.wav, the cue sheet in <project>/alr/cues.json, and
// DESIGN.md. A hand-written index.html or DESIGN.md is archived under <project>/archive/ first.
// Every scene cut and animation event sits on the plan's beat grid, and the sound effects are
// cut from the same event times. See ../SKILL.md and ../references/plan-format.md.

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, renameSync, cpSync, statSync } from "node:fs";
import { join, resolve, dirname, relative, isAbsolute, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const SKILL = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT_ROOT = resolve(SKILL, "../../..");
const GENERATED = "<!-- generated by app-launch-reel/build-reel.mjs -->";

const args = process.argv.slice(2);
if (!args.length || args.includes("--help")) {
  console.log("Usage: node build-reel.mjs <project-dir> [--plan alr-plan.json] [--no-audio]");
  process.exit(args.length ? 0 : 1);
}
const project = resolve(args[0]);
const planPath = resolve(project, args.includes("--plan") ? args[args.indexOf("--plan") + 1] : "alr-plan.json");
const noAudio = args.includes("--no-audio");

const errors = [], warnings = [];
const fail = m => errors.push(m);
const warn = m => warnings.push(m);
function done() {
  for (const w of warnings.splice(0)) console.warn(`warn: ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`error: ${e}`);
    process.exit(1);
  }
}
if (!existsSync(planPath)) {
  console.error(`No plan at ${relative(process.cwd(), planPath)}. Start from .claude/skills/app-launch-reel/templates/alr-plan.example.json.`);
  process.exit(1);
}
let plan;
try { plan = JSON.parse(readFileSync(planPath, "utf8")); } catch (e) { console.error(`${planPath}: ${e.message}`); process.exit(1); }

// ---------------------------------------------------------------- helpers
const r3 = n => Math.round(n * 1000) / 1000;
const esc = s => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const slug = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const HEX = /^#[0-9a-fA-F]{6}$/;
const color = (v, where, fallback) => {
  if (v == null) return fallback;
  if (!HEX.test(v)) { fail(`${where}: colours must be #rrggbb (got ${JSON.stringify(v)}).`); return fallback; }
  return v;
};
// A project file referenced by the plan: must exist and stay inside the project.
function projectFile(p, where) {
  if (typeof p !== "string" || !p) { fail(`${where}: expected a file path inside the project.`); return null; }
  if (/^[a-z]+:/i.test(p)) { fail(`${where}: ${p} is a URL; download it into the project first.`); return null; }
  const abs = resolve(project, p);
  if (relative(project, abs).startsWith("..") || isAbsolute(relative(project, abs))) { fail(`${where}: ${p} is outside the project.`); return null; }
  if (!existsSync(abs)) { fail(`${where}: missing ${p}.`); return null; }
  return abs;
}

const FORMAT = plan.format === "portrait" ? "portrait" : "landscape";
if (plan.format && !["portrait", "landscape"].includes(plan.format)) fail(`format must be "landscape" or "portrait".`);
const W = FORMAT === "portrait" ? 1080 : 1920, H = FORMAT === "portrait" ? 1920 : 1080;
const FPS = Number(plan.fps) || 30;
const music = plan.music || {};
const BPM = Number(music.bpm) || 120;
if (BPM < 80 || BPM > 170) fail(`music.bpm ${BPM} is outside 80-170; this style is cut on a 100-140 BPM grid.`);
const BEAT = 60 / BPM, S16 = BEAT / 4;
const snap16 = t => Math.ceil(t / S16 - 1e-6) * S16;

const brand = plan.brand || {};
// The HUD: the brand and chapter labels on top, the timecode and progress bar below. `hud: false`
// removes it; `hud: { top: false }` or `{ bottom: false }` removes one row.
const HUD = plan.hud === false ? { top: false, bottom: false } : { top: plan.hud?.top !== false, bottom: plan.hud?.bottom !== false };
if (!brand.name) fail("brand.name is required.");
const pal = plan.palette || {};
// palette.mono: a black-and-white brand. The mid tone becomes graphite, accents and UI states turn
// black, white, or grey (the kit's .alr-mono rules), and confetti is greyscale. Motion is unchanged.
const MONO = pal.mono === true;
const DEF = MONO
  ? { ink: "#0a0a0c", glow: "#3a3a40", brand: "#48484c", brand2: "#1c1c1e", paper: "#f5f5f7", haze: "#e5e5ea", violet: "#2c2c2e", violetEdge: "#0a0a0c", night: "#0a0a0c", black: "#000000", soft: "#a1a1a6", accent: "#ffffff", success: "#ffffff" }
  : { ink: "#050811", glow: "#0e54c4", brand: "#1a76fc", brand2: "#434dd0", paper: "#f9f9fb", haze: "#dcdcf7", violet: "#2f248d", violetEdge: "#090a2c", night: "#0d0d0e", black: "#040606", soft: "#83afff", accent: "#ffc9a8", success: "#34c759" };
const P = Object.fromEntries(Object.keys(DEF).map(k => [k, color(pal[k], `palette.${k}`, DEF[k])]));
const TONE_BASE = { ink: P.ink, brand: P.brand, paper: P.paper, violet: P.violet, night: P.night, black: P.black };
const TONE_LUM = { ink: "dark", brand: "mid", paper: "light", violet: "mid", night: "dark", black: "dark" };
const DEFAULT_TONE = { identity: "ink", statement: "brand", product: "paper", scan: "ink", widget: "violet", stack: "paper", lines: "brand", manifesto: "black", endcard: "brand", modules: "paper", metric: "brand", dashboard: "ink", chat: "paper", matrix: "ink", burst: "brand" };
const DEFAULT_EXIT = { identity: "iris", statement: "pixel", product: "whip", scan: "whip", widget: "whip", stack: "whip", lines: "focus", manifesto: "iris", endcard: null, modules: "whip", metric: "whip", dashboard: "whip", chat: "whip", matrix: "whip", burst: "iris" };
const TRANS_DUR = { whip: 0.34, pixel: 0.36, iris: 0.3, focus: 0.26, cut: 0 };
const TYPES = Object.keys(DEFAULT_TONE);

// ---------------------------------------------------------------- icons (24x24 line icons)
const ICONS = {
  home: "M3 11l9-7 9 7v9a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1z",
  bolt: "M13 2L4 14h7l-1 8 9-12h-7z",
  play: "M3 5h18v14H3z M10 9l5 3-5 3z",
  cloud: "M7 18h10a4 4 0 0 0 .5-7.97A6 6 0 0 0 6 9a4.5 4.5 0 0 0 1 9z",
  music: "M9 18V5l11-2v13 M9 18a3 3 0 1 1-6 0 3 3 0 0 1 6 0z M20 16a3 3 0 1 1-6 0 3 3 0 0 1 6 0z",
  dumbbell: "M6 7v10 M18 7v10 M3 10v4 M21 10v4 M6 12h12",
  wifi: "M2 9a15 15 0 0 1 20 0 M5 12.5a10 10 0 0 1 14 0 M8.5 16a5 5 0 0 1 7 0 M12 19.5h.01",
  card: "M3 6h18v12H3z M3 10h18",
  cart: "M3 4h2l2.5 11h11L21 7H6.2 M9 20h.01 M18 20h.01",
  pen: "M4 20l4-1 11-11-3-3L5 16z",
  bell: "M6 16V11a6 6 0 1 1 12 0v5l2 2H4z M10 21h4",
  doc: "M6 3h9l4 4v14H6z M14 3v5h5",
  lock: "M6 11h12v10H6z M8 11V7a4 4 0 1 1 8 0v4",
  offline: "M2 9a15 15 0 0 1 6-3.5 M22 9a15 15 0 0 0-9-4 M5 12.5a10 10 0 0 1 4-2.3 M19 12.5a10 10 0 0 0-3-2 M8.5 16a5 5 0 0 1 7 0 M3 3l18 18",
  block: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M5.6 5.6l12.8 12.8",
  globe: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M3 12h18 M12 3c3 3.5 3 14.5 0 18 M12 3c-3 3.5-3 14.5 0 18",
  check: "M5 12.5l4.5 4.5L19 7",
  star: "M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z",
  pin: "M12 21s-7-6.2-7-11.5A7 7 0 0 1 19 9.5C19 14.8 12 21 12 21z M12 7a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5z",
  chart: "M4 20V10 M10 20V4 M16 20v-8 M22 20H2",
  spark: "M12 3v4 M12 17v4 M3 12h4 M17 12h4 M6 6l2.5 2.5 M15.5 15.5L18 18 M6 18l2.5-2.5 M15.5 8.5L18 6",
  mic: "M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3z M5.5 11a6.5 6.5 0 0 0 13 0 M12 17.5V21",
  users: "M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z M2.5 21v-.5a6.5 6.5 0 0 1 13 0v.5 M16 3.6a4 4 0 0 1 0 7.3 M21.5 21v-.5a6.5 6.5 0 0 0-3.5-5.8",
  book: "M3 5.5C6 4 9 4 12 5.5V20c-3-1.5-6-1.5-9 0z M21 5.5C18 4 15 4 12 5.5V20c3-1.5 6-1.5 9 0z",
  shield: "M12 3l8 3v6c0 4.8-3.4 7.9-8 9-4.6-1.1-8-4.2-8-9V6z M8.5 12l2.5 2.5 4.5-5",
  calendar: "M4 6h16v14H4z M4 10h16 M8 3v5 M16 3v5",
  clock: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 7v5l3.5 2",
  grid: "M4 4h7v7H4z M13 4h7v7h-7z M4 13h7v7H4z M13 13h7v7h-7z",
  upload: "M12 16V4 M7 9l5-5 5 5 M4 15v5h16v-5",
  question: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M9.6 9.4a2.5 2.5 0 1 1 3.4 2.4c-.6.3-1 .8-1 1.5v.6 M12 17h.01",
  wallet: "M3 7h16a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H3z M3 7l12-4v4 M16 13.5h.01",
  cap: "M2 9l10-5 10 5-10 5z M6 11v5c3.5 2.5 8.5 2.5 12 0v-5 M22 9v6",
};
const icon = (name, where) => {
  if (name == null) return "";
  if (!ICONS[name]) { fail(`${where}: unknown icon "${name}". Use one of: ${Object.keys(ICONS).join(", ")}.`); return ""; }
  return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]}"/></svg>`;
};

// Brand marks: stroked paths in a 100x100 box, drawn on in the identity scene.
const MARKS = {
  check: { stroke: ["M24 14h52a10 10 0 0 1 10 10v52a10 10 0 0 1-10 10H24a10 10 0 0 1-10-10V24a10 10 0 0 1 10-10z", "M31 51l13 13 26-28"], fill: [] },
  ring: { stroke: ["M50 12a38 38 0 1 0 0.01 0z", "M50 34a16 16 0 1 0 0.01 0z"], fill: [] },
  bars: { stroke: ["M20 76V52", "M40 76V36", "M60 76V24", "M80 76V44"], fill: [] },
  spark: { stroke: ["M50 10c3 22 18 37 40 40-22 3-37 18-40 40-3-22-18-37-40-40 22-3 37-18 40-40z"], fill: [] },
};
// A raster mark (the brand's own logo file) is revealed rather than drawn. PNG size is read from
// the IHDR chunk so the mark box keeps the logo's aspect ratio.
const IMG_EXT = /\.(png|webp|jpe?g)$/i;
function imageAspect(abs) {
  const b = readFileSync(abs);
  if (b.length > 24 && b.toString("ascii", 1, 4) === "PNG") return b.readUInt32BE(16) / b.readUInt32BE(20);
  return null;
}
function loadImageMark(spec) {
  const img = projectFile(spec.image, "brand.mark.image");
  if (spec.imageOnLight) projectFile(spec.imageOnLight, "brand.mark.imageOnLight");
  if (!img) return MARKS.check;
  if (!IMG_EXT.test(spec.image)) fail("brand.mark.image must be a .png, .webp, or .jpg file.");
  const aspect = Number(spec.aspect) || imageAspect(img) || 1;
  return { stroke: [], fill: [], image: spec.image, imageOnLight: spec.imageOnLight || null, aspect };
}
function loadMark() {
  const m = brand.mark || "check";
  if (m && typeof m === "object") return loadImageMark(m);
  if (IMG_EXT.test(m)) return loadImageMark({ image: m });
  if (MARKS[m]) return MARKS[m];
  const abs = projectFile(m, "brand.mark");
  if (!abs) return MARKS.check;
  const svg = readFileSync(abs, "utf8");
  const vb = (svg.match(/viewBox="([^"]+)"/) || [])[1];
  const nums = vb ? vb.trim().split(/[\s,]+/).map(Number) : null;
  const d = [...svg.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map(x => x[1]);
  if (!d.length || d.some(x => !/^[MmLlHhVvCcSsQqTtAaZz0-9.,\s+-eE]+$/.test(x))) { fail(`brand.mark ${m}: needs <path d="..."> elements with plain path data.`); return MARKS.check; }
  if (!nums || nums.length !== 4 || nums.some(n => !Number.isFinite(n))) { fail(`brand.mark ${m}: needs a numeric viewBox.`); return MARKS.check; }
  return { stroke: d, fill: [], viewBox: nums.join(" ") };
}
const MARK = loadMark();
// Stroke width is 7 units in a 100-unit box; custom viewBoxes are scaled to match.
const markStroke = MARK.viewBox ? r3(7 * Number(MARK.viewBox.split(" ")[2]) / 100) : 7;
const markSvg = (cls = "", onLight = false) => MARK.image
  ? `<img class="alr-mark-img ${cls}" src="${esc(onLight && MARK.imageOnLight ? MARK.imageOnLight : MARK.image)}" alt="">`
  : `<svg viewBox="${MARK.viewBox || "0 0 100 100"}" aria-hidden="true" class="${cls}" style="stroke-width:${markStroke}">${MARK.stroke.map(d => `<path class="stroke" d="${d}"/>`).join("")}${MARK.fill.map(d => `<path class="fill" d="${d}"/>`).join("")}</svg>`;
// The mark box: square for stroke marks, the logo's own aspect ratio for an image mark.
const markBox = (cls, size, inner = "", onLight = false) => `<div class="alr-mark ${cls}${MARK.image ? " is-img" : ""}" style="height:${size}px;width:${MARK.image ? r3(size * MARK.aspect) : size}px">${markSvg("", onLight)}${inner}</div>`;
const badgeHtml = () => brand.badge ? `<span class="alr-badge"><span>${esc(brand.badge)}</span></span>` : "";

// ---------------------------------------------------------------- text
// "*word*" marks emphasis; a line wrapped in "~...~" is a secondary (soft) line.
function wordsHtml(text, opts = {}) {
  const out = [];
  let inEm = false, count = 0;
  const tokens = String(text).split(/\s+/).filter(Boolean);
  const parts = [];
  for (let tok of tokens) {
    let open = false, close = false;
    if (tok.startsWith("*")) { open = true; tok = tok.slice(1); }
    if (tok.endsWith("*")) { close = true; tok = tok.slice(0, -1); }
    if (open) inEm = true;
    parts.push({ w: tok, em: inEm });
    if (close) inEm = false;
  }
  let i = 0;
  while (i < parts.length) {
    if (parts[i].em) {
      const run = [];
      while (i < parts.length && parts[i].em) run.push(parts[i++]);
      out.push(`<span class="alr-em${opts.emClass ?? " tint"}">${run.map(p => { count++; return `<span class="alr-w"><span class="alr-wi">${esc(p.w)}</span></span>`; }).join(" ")}${opts.underline ? UNDERLINE : ""}</span>`);
    } else {
      count++;
      out.push(`<span class="alr-w"><span class="alr-wi">${esc(parts[i++].w)}</span></span>`);
    }
  }
  return { html: out.join(" "), count };
}
function linesHtml(lines, cls, opts = {}) {
  let count = 0;
  const html = (Array.isArray(lines) ? lines : [lines]).map((ln, i, all) => {
    let s = String(ln), soft = false;
    if (/^~.*~$/.test(s)) { soft = true; s = s.slice(1, -1); }
    const underline = opts.underline && i === all.map(x => /\*/.test(x)).lastIndexOf(true);
    const w = wordsHtml(s, { underline, emClass: opts.emClass });
    count += w.count;
    return `<div class="alr-line${soft ? " soft" : ""} ${cls}">${w.html}</div>`;
  }).join("");
  return { html, count };
}
const charsHtml = s => [...String(s)].map(ch => ch === " " ? `<span class="alr-w"><span class="alr-wi">&nbsp;</span></span>` : `<span class="alr-w"><span class="alr-wi">${esc(ch)}</span></span>`).join("");
const UNDERLINE = `<svg class="alr-anno underline" viewBox="0 0 200 24" preserveAspectRatio="none" style="left:-3%;width:106%;top:92%;height:0.28em"><path vector-effect="non-scaling-stroke" d="M4 15 C 40 8, 82 18, 122 11 S 178 8, 196 12"/></svg>`;
const CIRCLE = `<svg class="alr-anno circle" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M64 9 C 32 3, 7 22, 8 52 C 9 82, 38 96, 64 91 C 91 86, 99 55, 91 31 C 85 14, 66 6, 42 11"/></svg>`;

// ---------------------------------------------------------------- scenes and grid
const scenesIn = Array.isArray(plan.scenes) ? plan.scenes : [];
if (!scenesIn.length) fail("plan.scenes is empty.");
done();
const scenes = [];
let beatAt = 0, lastChapter = null;
scenesIn.forEach((s, i) => {
  const where = `scenes[${i}] (${s.type})`;
  if (!TYPES.includes(s.type)) { fail(`${where}: type must be one of ${TYPES.join(", ")}.`); return; }
  const beats = Number(s.beats);
  if (!(beats > 0) || Math.abs(beats * 2 - Math.round(beats * 2)) > 1e-9) fail(`${where}: beats must be a positive whole or half number.`);
  // A burst flips its background on every word; it enters on its first tone and leaves on its last.
  const burstTones = s.type === "burst" ? (Array.isArray(s.tones) && s.tones.length ? s.tones : ["brand", "paper", "ink"]) : null;
  const tone = burstTones ? burstTones[0] : s.tone || DEFAULT_TONE[s.type];
  if (!TONE_BASE[tone]) fail(`${where}: tone must be one of ${Object.keys(TONE_BASE).join(", ")}.`);
  (burstTones || []).forEach(t => { if (!TONE_BASE[t]) fail(`${where}: tones must be from ${Object.keys(TONE_BASE).join(", ")}.`); });
  const chapter = s.type === "identity" ? (s.chapter || "Identity") : (s.chapter || lastChapter || s.type);
  lastChapter = chapter;
  const id = slug(s.id || `${String(i + 1).padStart(2, "0")}-${s.type}`);
  let lumOut = TONE_LUM[tone];
  if (burstTones) {
    const n = (s.words || []).length || 1;
    lumOut = TONE_LUM[burstTones[(n - 1) % burstTones.length]];
  }
  scenes.push({ ...s, i, id, where, beats, tone, lum: TONE_LUM[tone], lumOut, burstTones, chapter, start: r3(beatAt * BEAT), end: r3((beatAt + beats) * BEAT) });
  beatAt += beats;
});
done();
const D = r3(beatAt * BEAT);
scenes.forEach((s, i) => {
  const next = scenes[i + 1];
  const type = s.exit === undefined ? DEFAULT_EXIT[s.type] : s.exit;
  if (next && type && !TRANS_DUR.hasOwnProperty(type)) fail(`${s.where}: exit must be whip, pixel, iris, focus, or cut.`);
  s.exitType = next ? (type || "cut") : null;
  if (next && s.lumOut === next.lum && !(s.type === "stack" && s.flip !== false)) warn(`${s.where} and the next scene are both ${s.lum}; this style flips luminance on every cut (dark -> mid -> light).`);
});
if (scenes[0].type !== "identity") warn("The reel usually opens on an identity scene (logo build and hit).");
if (scenes[scenes.length - 1].type !== "endcard") warn("The reel usually closes on an endcard (lockup, tagline, URL).");
done();

// Transition windows. The cut is the scene boundary; whips straddle it, wipes land on it.
for (let i = 0; i < scenes.length - 1; i++) {
  const s = scenes[i], n = scenes[i + 1], type = s.exitType, dur = TRANS_DUR[type];
  s.exit = { type, at: s.end, dur };
  if (type === "iris") {
    s.exit.origin = s.type === "identity" ? ".alr-mark" : s.type === "manifesto" ? ".alr-title .alr-line:last-child" : s.type === "burst" ? ".alr-burst-layer:last-child .alr-burst-word" : s.type === "modules" ? ".alr-mcard .alr-mark" : null;
    n.irised = true;
  }
  if (type === "pixel") s.exit.fill = n.tone;
  s.clipEnd = s.end + (type === "whip" ? dur / 2 + 0.02 : 0.001);
  n.clipStart = n.start - (type === "whip" ? dur / 2 + 0.02 : type === "iris" ? dur + 0.02 : 0);
}
scenes.forEach(s => { s.clipStart ??= s.start; s.clipEnd ??= s.end; });

// ---------------------------------------------------------------- audio cues
const cues = [];
const cue = (kind, at, o = {}) => { if (at >= -0.001 && at < D) cues.push({ kind, at: r3(at), align: o.align || "onset", gain: o.gain ?? 1, dur: o.dur, lead: o.lead, label: o.label }); };
const whooshFor = s => {
  const x = s.exit;
  if (!x || x.type === "cut") return;
  const peak = x.type === "whip" ? x.at - 1 / FPS : x.type === "pixel" ? x.at - x.dur / 2 : x.at - 0.06;
  cue("whoosh", peak, { align: "peak", label: `${x.type} ${s.id} -> next` });
};

// ---------------------------------------------------------------- scene builders
const sceneHtml = [];
const cfgScenes = [];
const hudChapters = [];
const chapterNames = [];
scenes.forEach(s => { if (s.type !== "endcard" && !chapterNames.includes(s.chapter)) chapterNames.push(s.chapter); });
const totalChapters = chapterNames.length + (scenes.some(s => s.type === "endcard") ? 1 : 0);
const chapterLabel = s => `${String(chapterNames.indexOf(s.chapter) + 1).padStart(2, "0")} / ${String(totalChapters).padStart(2, "0")} — ${s.chapter}`;

function copyBlock(cp, where, extra = "") {
  if (!cp) return { html: "", count: 0 };
  if (!cp.title) fail(`${where}: copy needs a title (array of lines).`);
  const t = linesHtml(cp.title || [], "alr-h2");
  return {
    count: t.count,
    html: `<div class="alr-copy ${extra}">${cp.eyebrow ? `<div class="alr-eyebrow">${esc(cp.eyebrow)}</div>` : ""}<div class="alr-title">${t.html}</div>${cp.sub ? `<div class="alr-sub">${esc(cp.sub)}</div>` : ""}</div>`,
  };
}
// Copy words stagger on sixteenths; in a two-beat feature frame they move at double speed.
const copyTimes = (t, count, beats) => { const st = beats <= 2 ? S16 / 2 : S16; return { eyebrow: r3(t - 0.06), words: r3(t), stagger: r3(st), sub: r3(t + count * st + 0.08) }; };
const money = (v, cur, dec = 2) => `${cur}${Number(v).toFixed(dec).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;
function rowHtml(r, where, cur, cls = "alr-row-card", dec = 2) {
  if (!r || !r.title) fail(`${where}: rows need a title.`);
  const c = color(r.color, `${where}.color`, P.brand);
  const val = typeof r.value === "number" ? money(r.value, cur, dec) : esc(r.value ?? "");
  const metaColor = color(r.metaColor, `${where}.metaColor`, "#8a8d98");
  return `<div class="${cls}"><div class="alr-row-icon" style="background:color-mix(in srgb, ${c} 16%, transparent);color:${c}">${icon(r.icon || "star", where)}</div><div class="alr-row-text"><div class="alr-row-title">${esc(r.title)}</div><div class="alr-row-meta" style="color:${metaColor}"><i></i>${esc(r.meta || "")}</div></div><div class="alr-row-value">${val}</div></div>`;
}
// A burst carries its tones on its word layers; a scene-level tone would override theirs.
const toneClass = s => s.type === "burst" ? "alr-burst-scene" : `tone-${s.tone} alr-${s.lum === "light" ? "light" : s.lum === "mid" ? "mid" : "dark"}`;
function overlays(s) {
  const x = s.exit;
  if (!x) return "";
  if (x.type === "pixel") {
    const n = 8, cw = W / n;
    return `<div class="alr-pixel">${Array.from({ length: n }, (_, i) => `<i class="fill-${x.fill}" style="background-position:${-r3(i * cw)}px 0"></i>`).join("")}</div>`;
  }
  if (x.type === "iris") {
    const nb = TONE_BASE[scenes[s.i + 1].tone];
    return `<div class="alr-iris" style="background:${nb};opacity:.22"></div><div class="alr-iris" style="background:${nb};opacity:.45"></div>`;
  }
  return "";
}

const B = {};
B.identity = s => {
  const hit = r3(s.start + (Number(s.hitBeat) || 2) * BEAT);
  if (hit >= s.end - 0.5) fail(`${s.where}: the hit (beat ${s.hitBeat || 2}) needs at least a beat of lockup after it; give the scene more beats.`);
  s.ev = { draw: [r3(s.start + 0.1), r3(hit - 0.08)], hit, lock: r3(hit + 0.35) };
  s.hit = hit;
  cue("riser", hit, { align: "peak", label: "riser into the hit" });
  cue("impact", hit, { align: "peak", label: "opening hit" });
  cue("pop", s.ev.lock + 0.08, { gain: 0.5, label: "wordmark" });
  return `<div class="alr-bg"></div><div class="alr-dots"></div>
    <div class="alr-center"><div class="alr-lockup">${markBox("alr-mark-glow", FORMAT === "portrait" ? 150 : 210, `<div class="alr-ring"></div><div class="alr-ring"></div>`)}<div class="alr-wordmark">${charsHtml(brand.name)}${badgeHtml()}</div></div></div>`;
};
B.statement = s => {
  const t = linesHtml(s.title || [], "alr-h1", { underline: true, emClass: "" });
  if (!s.title) fail(`${s.where}: title is required.`);
  const w0 = r3(s.start + 0.06);
  const lastLand = w0 + (t.count - 1) * S16 + 0.2;
  const exitStart = s.exit ? s.exit.at - s.exit.dur : s.end;
  let u0 = lastLand, c0 = u0 + 0.24;
  if (c0 + 0.32 > exitStart + 0.08) { c0 = exitStart + 0.08 - 0.32; u0 = Math.min(u0, c0 - 0.16); }
  s.ev = { eyebrow: r3(s.start + 0.02), words: w0, stagger: r3(S16), underline: [r3(u0), r3(u0 + 0.28)], circle: [r3(c0), r3(c0 + 0.34)] };
  if (u0 < w0 + (t.count - 1) * S16) warn(`${s.where}: ${t.count} words is a lot for ${s.beats} beats; the underline starts before the last word lands.`);
  const tick = (s.ticker || []).map(n => `<span>${esc(n)}${String(n) === String(s.circle) ? CIRCLE : ""}</span>`).join("");
  if (s.circle != null && !(s.ticker || []).map(String).includes(String(s.circle))) warn(`${s.where}: circle "${s.circle}" is not in the ticker.`);
  // One ticker word (a brand name) is a readable watermark: centred, whole, and drifting less.
  const single = (s.ticker || []).length === 1;
  return `<div class="alr-bg"></div>${tick ? `<div class="alr-ticker${single ? " single" : ""}">${tick}</div>` : ""}
    <div class="alr-center">${s.eyebrow ? `<div class="alr-eyebrow">${esc(s.eyebrow)}</div>` : ""}<div class="alr-title">${t.html}</div></div>`;
};
B.product = s => {
  const app = s.app || {};
  const cur = app.currency ?? "$";
  const copies = (Array.isArray(s.copy) ? s.copy : [s.copy]).filter(Boolean);
  if (!copies.length) fail(`${s.where}: copy is required.`);
  const blocks = copies.map((c, i) => copyBlock(c, `${s.where}.copy[${i}]`));
  // Final slot layout: the starting rows with any added rows spliced in.
  const base = (app.rows || []).map(r => ({ ...r, isNew: false }));
  const steps = (s.steps || []).map((st, i) => ({ ...st, k: i })).sort((a, b) => a.at - b.at);
  const slots = base.slice();
  steps.filter(st => st.do === "add").forEach(st => {
    if (!st.row) fail(`${s.where}: an add step needs a row.`);
    const idx = Math.max(0, Math.min(slots.length, Number(st.index) || 0));
    st._index = idx;
    slots.splice(idx, 0, { ...(st.row || {}), isNew: true });
  });
  if (slots.length > 5) warn(`${s.where}: ${slots.length} rows do not all fit on the phone; keep it to 5.`);
  const phone0 = r3(s.start + 0.1);
  const ev = { phone: phone0, header: r3(phone0 + 0.32), hero: r3(phone0 + 0.4), rows: [], copy: copyTimes(r3(s.start + 0.42), blocks[0]?.count || 0, s.beats), steps: [], pitch: 96 };
  let rowT = snap16(phone0 + 0.5 - s.start) + s.start;
  slots.forEach((r, i) => { ev.rows[i] = r.isNew ? null : r3(rowT); if (!r.isNew) { cue("pop", rowT, { gain: 0.55, label: `row ${r.title}` }); rowT += S16; } });
  let total = typeof app.hero?.value === "number" ? app.hero.value : base.reduce((a, r) => a + (typeof r.value === "number" ? r.value : 0), 0);
  const keys = [{ t: 0, v: total }];
  let copyIdx = 0;
  // Phone steps must not overlap each other (a swap of the copy can run alongside).
  let phoneBusy = -1;
  const busyUntil = (a, b, what, copyOnly) => {
    if (copyOnly) return;
    if (a < phoneBusy - 1e-6) warn(`${s.where}: the ${what} step starts at ${r3(a)} s while the previous phone step runs until ${r3(phoneBusy)} s.`);
    phoneBusy = Math.max(phoneBusy, b);
  };
  steps.forEach(st => {
    const A = r3(s.start + Number(st.at) * BEAT);
    if (!(A > s.start) || A >= s.end) fail(`${s.where}: step at beat ${st.at} is outside the scene.`);
    if (st.do === "add") {
      const f = (st.fields || [st.row?.title || "", typeof st.row?.value === "number" ? Number(st.row.value).toFixed(2) : String(st.row?.value || "")]).map(String);
      // Typing is fast (a demo, not a tutorial): the whole add lands in about 1.4 s.
      const t0a = A + 0.2, t1a = t0a + Math.min(0.28, 0.022 * f[0].length);
      const t0b = t1a + 0.05, t1b = t0b + Math.min(0.2, 0.04 * (f[1] || "").length);
      const chip = r3(s.start + snap16(t1b + 0.03 - s.start));
      const save = r3(chip + S16);
      const sheetDown = r3(save + 0.12), insert = r3(sheetDown + 0.2);
      busyUntil(A, insert + 0.3, "add");
      const e = { type: "add", index: st._index, sheetUp: A, fields: [{ text: f[0], t0: r3(t0a), t1: r3(t1a) }, { text: f[1] || "", t0: r3(t0b), t1: r3(t1b) }], chip, save, sheetDown, insert };
      ev.steps.push(e);
      cue("whoosh", A + 0.12, { align: "peak", gain: 0.3, label: "sheet up" });
      cue("type", t0a, { dur: r3(t1a - t0a + 0.05), gain: 0.8, label: "typing name" });
      cue("type", t0b, { dur: r3(t1b - t0b + 0.05), gain: 0.8, label: "typing amount" });
      cue("tap", chip, { label: "chip" });
      cue("tap", save, { label: "save" });
      cue("pop", insert, { label: "new row" });
      // `delta` moves the hero counter explicitly (a count, not a price); otherwise the row's value.
      const dAdd = st.delta != null ? Number(st.delta) : typeof st.row?.value === "number" ? st.row.value : 0;
      if (dAdd) { total += dAdd; keys.push({ t: r3(insert + 0.05), v: r3(total) }); }
      st._html = { sheet: { title: st.sheetTitle || "New subscription", labels: st.labels || ["Name", "Amount"], chips: st.chips || ["Monthly", "Yearly", "Weekly"], button: st.button || "Save" } };
    } else if (st.do === "swap") {
      if (!blocks[copyIdx + 1]) { fail(`${s.where}: a swap step needs a second copy block.`); return; }
      const inn = r3(A + 0.22);
      busyUntil(A, inn + 0.3, "swap", true);
      ev.steps.push({ type: "swap", from: copyIdx, to: copyIdx + 1, out: A, in: inn, sub: r3(inn + blocks[copyIdx + 1].count * S16 + 0.1) });
      copyIdx++;
    } else if (st.do === "complete") {
      const slotIdx = slots.findIndex(r => r.title === st.row);
      if (slotIdx < 0) { fail(`${s.where}: complete step row "${st.row}" is not in the list.`); return; }
      const e = { type: "complete", slot: slotIdx, tap: A, swipe: r3(A + 0.3), success: r3(A + 0.42), collapse: r3(A + 0.52), toast: r3(A + 0.6), seed: 11 + st.k };
      busyUntil(A, e.collapse + 0.4, "complete");
      if (e.toast + 0.4 > s.end - (s.exit?.dur || 0) / 2) warn(`${s.where}: the complete step at beat ${st.at} ends after the exit starts; move it earlier.`);
      ev.steps.push(e);
      cue("tap", A, { label: "swipe" });
      cue("whoosh", e.swipe + 0.08, { align: "peak", gain: 0.3, label: "swipe away" });
      cue("success", e.success, { label: "completed" });
      if (st.toast) cue("pop", e.toast, { gain: 0.6, label: "toast" });
      const v = slots[slotIdx].value;
      const dDone = st.delta != null ? Number(st.delta) : typeof v === "number" ? -v : 0;
      if (dDone) { total += dDone; keys.push({ t: r3(e.success), v: r3(total) }); }
      slots[slotIdx].label = st.label || "Done";
      st._toast = st.toast;
    } else fail(`${s.where}: step "do" must be add, swap, or complete.`);
  });
  ev.counter = { keys, fmt: { prefix: cur, decimals: app.decimals ?? 2 } };
  s.ev = ev;
  const listH = slots.length * 96;
  const complete = steps.find(st => st.do === "complete");
  const add = steps.find(st => st.do === "add");
  const confettiColors = MONO ? ["#0b0b0f", "#48484c", "#8e8e93", "#c7c7cc", "#0b0b0f", "#636366"] : [P.brand, P.success, P.accent, P.soft, "#ffd166", P.brand2];
  const slotHtml = slots.map((r, i) => `<div class="alr-slot" data-slot="${i}" style="top:${i * 96}px"><div class="alr-row${r.isNew ? " is-new" : ""}"><div class="alr-row-paid">${esc(r.label || complete?.label || "Done")}</div>${rowHtml(r, `${s.where}.rows[${i}]`, cur, "alr-row-card", app.decimals ?? 2)}</div>${complete && slots.findIndex(x => x.title === complete.row) === i ? `<div class="alr-confetti">${Array.from({ length: 26 }, (_, k) => `<i style="background:${confettiColors[k % confettiColors.length]};${k % 3 === 0 ? "border-radius:50%;width:11px;height:11px" : ""}"></i>`).join("")}</div>` : ""}</div>`).join("");
  const sh = add?._html?.sheet;
  const sheet = sh ? `<div class="alr-sheet"><div class="alr-sheet-grab"></div><div class="alr-sheet-title">${esc(sh.title)}</div>${sh.labels.map(l => `<div class="alr-field"><div class="alr-field-label">${esc(l)}</div><div class="alr-field-value"></div></div>`).join("")}<div class="alr-chips">${sh.chips.map((c, i) => `<div class="alr-chip-opt">${esc(c)}${i === 0 ? `<div class="on">${esc(c)}</div>` : ""}</div>`).join("")}</div><div class="alr-button">${esc(sh.button)}<div class="alr-ripple"></div></div></div>` : "";
  const toast = complete?._toast ? `<div class="alr-toast"><i></i>${esc(complete._toast)}</div>` : "";
  return `<div class="alr-bg"></div><div class="alr-haze h1"></div><div class="alr-haze h2"></div>
    <div class="alr-split">${blocks.map((b, i) => b.html.replace('class="alr-copy "', `class="alr-copy alr-light" data-copy="${i}"`)).join("")}
    <div class="alr-stage"><div class="alr-hero-wrap"><div class="alr-phone"><div class="alr-screen"><div class="alr-island"></div><div class="alr-status">9:41</div>
      <div class="alr-app"><div class="alr-app-head"><div class="alr-app-title">${esc(app.title || brand.name)}</div><div class="alr-app-sub">${esc(app.subtitle || "")}</div></div>
      <div class="alr-hero"><div class="alr-hero-label">${esc(app.hero?.label || "Total")}</div><div class="alr-hero-value">${money(keys[0].v, cur, app.decimals ?? 2)}</div>${app.hero?.badge ? `<div class="alr-hero-badge">${esc(app.hero.badge)}</div>` : ""}</div>
      <div class="alr-list" style="height:${listH}px">${slotHtml}</div></div>${sheet}${toast}
    </div></div></div></div></div>`;
};
B.scan = s => {
  const cp = copyBlock(s.copy, `${s.where}.copy`);
  const doc = s.doc || {};
  const fields = doc.fields || [];
  const e0 = r3(s.start + 0.1);
  s.ev = { brackets: r3(s.start + 0.06), scan: [r3(s.start + 0.12), r3(s.start + 0.62)], boxes: fields.map((_, i) => r3(s.start + 0.3 + i * 0.14)), tags: (s.tags || []).map((_, i) => r3(s.start + 0.38 + i * 2 * S16)), copy: copyTimes(e0, cp.count, s.beats) };
  cue("scan", s.ev.scan[0], { label: "scan sweep" });
  s.ev.tags.forEach(t => cue("pop", t, { label: "detected tag" }));
  const docHtml = `<div class="alr-doc"><div class="alr-doc-head"><i></i>${esc(doc.vendor || "Invoice")}</div><div class="alr-doc-line" style="width:72%"></div><div class="alr-doc-line" style="width:48%"></div>${fields.map(f => `<div class="alr-doc-field"><div class="box"></div><small>${esc(f.label)}</small><b>${esc(f.value)}</b></div>`).join("")}<div class="alr-doc-line" style="width:80%"></div><div class="alr-doc-line" style="width:56%"></div></div>`;
  const tags = (s.tags || []).map((t, i) => `<div class="alr-tag${i ? " alt" : ""}" style="left:360px;top:${196 + i * 118}px">${esc(t[0])} <b>${esc(t[1])}</b></div>`).join("");
  return `<div class="alr-bg"></div><div class="alr-split">${cp.html}<div class="alr-stage"><div class="alr-hero-wrap"><div class="alr-scan">${docHtml}<div class="alr-brackets"><i></i><i></i><i></i><i></i></div><div class="alr-scanline"></div>${tags}</div></div></div></div>`;
};
B.widget = s => {
  const cp = copyBlock(s.copy, `${s.where}.copy`);
  const wd = s.widget || {};
  s.ev = { lift: r3(s.start + snap16(0.3)), copy: copyTimes(r3(s.start + 0.1), cp.count, s.beats) };
  cue("pop", s.ev.lift, { label: "widget lift" });
  const tiles = ["#ff9f43,#ff6b6b", "#48dbfb,#0abde3", "#feca57,#ff9f43", "#c8d6e5,#8395a7", "#1dd1a1,#10ac84", "#5f27cd,#341f97", "#ff6b81,#ee5253", "#54a0ff,#2e86de"];
  const tileHtml = tiles.map(g => `<i style="background:linear-gradient(145deg,${g})"></i>`).join("");
  const dock = ["#2ecc71,#27ae60", "#34c759,#1f9d45", "#4facfe,#00c6fb", "#f6f7f9,#d9dde4"].map(g => `<i style="background:linear-gradient(145deg,${g})"></i>`).join("");
  const rows = (wd.rows || []).map(r => `<div class="alr-widget-row"><div><i></i>${esc(r.title)}<small>${esc(r.meta || "")}</small></div><div>${esc(r.value || "")}</div></div>`).join("");
  return `<div class="alr-bg"></div><div class="alr-split">${cp.html}<div class="alr-stage"><div class="alr-hero-wrap"><div class="alr-device" style="position:relative;transform:rotate(4deg)"><div class="alr-phone gold"><div class="alr-screen"><div class="alr-home"></div><div class="alr-island"></div><div class="alr-status" style="color:#fff">9:41</div><div class="alr-tiles">${tileHtml}</div><div class="alr-dock">${dock}</div></div></div>
    <div class="alr-widget"><div class="alr-widget-title">${esc(wd.title || "Up next")}<span>${esc(wd.count || "")}</span></div>${rows}</div></div></div></div></div>`;
};
B.stack = s => {
  const t = linesHtml(s.title || [], "alr-h3");
  const cards = s.cards || [];
  if (cards.length > 4) warn(`${s.where}: more than 4 cards crowd the frame.`);
  const flip = s.flip === false ? null : Number(s.flip ?? 0.92);
  s.ev = { words: r3(s.start + 0.06), stagger: r3(s.beats <= 2 ? S16 / 2 : S16), cards: cards.map((_, i) => r3(s.start + 0.2 + i * S16)) };
  s.ev.cards.forEach(tc => cue("pop", tc, { gain: 0.45, label: "card" }));
  if (flip != null) {
    const f0 = r3(s.start + flip * BEAT);
    s.ev.flip = [f0, r3(f0 + 0.3)];
    if (s.ev.flip[1] > s.end - (s.exit?.dur || 0) / 2 - 0.05) warn(`${s.where}: the theme flip runs into the exit; lower flip or add beats.`);
    cue("tap", f0, { gain: 0.8, label: "theme toggle" });
    cue("whoosh", f0 + 0.15, { align: "peak", gain: 0.35, label: "theme wipe" });
  }
  const cur = s.currency ?? "$";
  // Without a flip, a stack on a dark or mid tone shows only its dark layer, unclipped.
  const solidDark = flip == null && s.lum !== "light";
  const layer = (dark, solid) => `<div class="alr-theme-${dark ? "dark alr-dark" : "light alr-light"}${solid ? " solid" : ""}"><div class="alr-center"><div class="alr-title">${t.html}</div><div class="alr-cards">${cards.map((c, i) => `<div class="alr-card-wrap">${rowHtml(c, `${s.where}.cards[${i}]`, cur, "alr-card", s.decimals ?? 2)}</div>`).join("")}</div></div></div>`;
  const bands = flip == null ? "" : [["#9a9aa2", 0.9, 0], ["#5b5b62", 0.9, -70], ["#2c2c31", 0.9, -140]].map(([c, a, dx]) => `<div class="alr-wipe-band" data-alpha="${a}" style="background:${c};margin-left:${dx}px;transform:skewX(${-r3(Math.atan((0.18 * W) / H) * 180 / Math.PI)}deg)"></div>`).join("") +
    [0.18, 0.35, 1].map((a, i) => `<div class="alr-knob" data-alpha="${a}" style="margin-left:${-32 - (2 - i) * 46}px"></div>`).join("");
  return `<div class="alr-bg"></div>${solidDark ? layer(true, true) : layer(false)}${flip == null ? "" : layer(true)}${bands}`;
};
B.lines = s => {
  const lines = s.lines || [];
  if (!lines.length) fail(`${s.where}: lines is required.`);
  s.ev = { eyebrow: r3(s.start + 0.04), lines: lines.map((_, i) => r3(s.start + 0.08 + i * S16)) };
  s.ev.lines.forEach(tl => cue("pop", tl, { gain: 0.3, label: "line" }));
  const eb = Array.isArray(s.eyebrow) ? s.eyebrow.map(esc).join("&nbsp;&nbsp;·&nbsp;&nbsp;") : esc(s.eyebrow || "");
  return `<div class="alr-bg"></div><div class="alr-center">${eb ? `<div class="alr-eyebrow">${eb}</div>` : ""}<div class="alr-lines">${lines.map(l => `<div class="alr-line alr-h3" style="font-size:${FORMAT === "portrait" ? 54 : 60}px;line-height:1.22">${wordsHtml(l).html}</div>`).join("")}</div></div>`;
};
B.manifesto = s => {
  const t = linesHtml(s.title || [], "alr-h1");
  const n = (s.title || []).length;
  // One line per beat on the drop; the sub and pills follow the last line.
  s.ev = { lines: Array.from({ length: n }, (_, i) => r3(s.start + i * BEAT)), sub: r3(s.start + (n - 0.75) * BEAT), pills: (s.pills || []).map((_, i) => r3(s.start + (n - 0.5) * BEAT + i * S16)) };
  if (n > 3) warn(`${s.where}: ${n} manifesto lines is a lot; keep it to two or three.`);
  s.ev.lines.forEach((tl, i) => cue("impact", tl, { align: "peak", gain: i ? 0.5 : 1, label: `manifesto line ${i + 1}` }));
  cue("riser", s.start, { align: "peak", gain: 0.8, lead: 2 * BEAT, label: "riser into the drop" });
  s.ev.pills.forEach(tp => cue("pop", tp, { label: "pill" }));
  s.drop = s.start;
  const sub = s.sub ? `<div class="alr-sub" style="font-size:40px;color:rgba(255,255,255,.72)">${wordsHtml(s.sub).html}</div>` : "";
  const pills = (s.pills || []).map((p, i) => `<div class="alr-pill">${icon(p.icon, `${s.where}.pills[${i}]`)}${esc(p.text)}</div>`).join("");
  return `<div class="alr-bg"></div><div class="alr-center" style="gap:18px"><div class="alr-title" style="margin-bottom:18px">${t.html}</div>${sub}${pills ? `<div class="alr-pills">${pills}</div>` : ""}</div>`;
};
B.endcard = s => {
  s.ev = { mark: r3(s.start - 0.04), word: r3(s.start + 0.22), tagline: r3(s.start + 0.44), url: r3(s.start + 0.62) };
  cue("shimmer", s.start, { label: "lockup" });
  cue("pop", s.ev.url, { gain: 0.6, label: "url" });
  const rings = [260, 400, 560, 740, 940].map(r => `<i style="left:${-r}px;top:${-r}px;width:${2 * r}px;height:${2 * r}px"></i>`).join("");
  const pills = [brand.url ? `<div class="alr-url">${icon("globe", "brand.url")}${esc(brand.url)}</div>` : "", brand.cta ? `<div class="alr-url alr-cta">${esc(brand.cta)}</div>` : ""].join("");
  return `<div class="alr-bg"></div><div class="alr-rings">${rings}</div>
    <div class="alr-center" style="gap:22px">${markBox("alr-endmark", 190)}<div class="alr-wordmark" style="font-size:118px">${charsHtml(brand.name)}${badgeHtml()}</div>${brand.tagline ? `<div class="alr-tagline">${esc(brand.tagline)}</div>` : ""}${pills ? `<div class="alr-endpills">${pills}</div>` : ""}</div>`;
};

// Five to six module tiles float in, then converge into one platform card: "it should feel
// like one". Tile anchors are frame coordinates (centre x, centre y, rotation).
const TILE_POS = {
  landscape: [[420, 470, -7], [1500, 455, 6], [370, 800, 5], [1560, 790, -6], [960, 905, 3], [960, 420, -2]],
  portrait: [[290, 760, -7], [760, 700, 5], [330, 1080, -4], [780, 1130, 6], [300, 1420, -3], [760, 1500, 4]],
};
B.modules = s => {
  const t = linesHtml(s.title || [], "alr-h2");
  const tiles = s.tiles || [];
  if (!tiles.length || tiles.length > 6) fail(`${s.where}: tiles needs 1 to 6 entries.`);
  const m = r3(s.start + Number(s.merge ?? 4) * BEAT);
  const exitStart = s.exit ? s.exit.at - (s.exit.type === "whip" ? s.exit.dur / 2 : s.exit.dur) : s.end;
  if (m + 1.0 > exitStart) warn(`${s.where}: the merge at beat ${s.merge ?? 4} leaves under a second for the card; lower merge or add beats.`);
  const card = s.card || {};
  const chips = card.chips || tiles.map(x => x.title);
  s.ev = { eyebrow: r3(s.start + 0.02), words: r3(s.start + 0.06), stagger: r3(S16), tiles: tiles.map((_, i) => r3(s.start + 0.3 + i * S16)), merge: m, card: r3(m + 0.42), chips: chips.map((_, i) => r3(m + 0.66 + i * S16 / 2)) };
  s.ev.tiles.forEach(tt => cue("pop", tt, { gain: 0.45, label: "tile" }));
  cue("whoosh", m + 0.38, { align: "peak", gain: 0.6, label: "tiles converge" });
  cue("impact", s.ev.card, { align: "peak", gain: 0.45, label: "one platform" });
  cue("pop", s.ev.chips[0], { gain: 0.45, label: "module chips" });
  const pos = TILE_POS[FORMAT];
  const cy = FORMAT === "portrait" ? 1120 : 680;
  const tileHtml = tiles.map((x, i) => {
    const [px, py, rot] = pos[i];
    const c = color(x.color, `${s.where}.tiles[${i}].color`, P.brand);
    return `<div class="alr-tile" data-rot="${rot}" style="left:${px}px;top:${py}px"><div class="alr-row-icon" style="background:color-mix(in srgb, ${c} 16%, transparent);color:${c}">${icon(x.icon || "grid", `${s.where}.tiles[${i}]`)}</div><div class="alr-row-text"><div class="alr-tile-title">${esc(x.title)}</div><div class="alr-tile-meta">${esc(x.meta || "")}</div></div></div>`;
  }).join("");
  const onLight = s.lum === "light";
  return `<div class="alr-bg"></div><div class="alr-haze h1"></div><div class="alr-haze h2"></div>
    <div class="alr-mod-head">${s.eyebrow ? `<div class="alr-eyebrow">${esc(s.eyebrow)}</div>` : ""}<div class="alr-title">${t.html}</div></div>
    ${tileHtml}
    <div class="alr-mcard" style="left:${W / 2}px;top:${cy}px"><div class="alr-mcard-in"><div class="alr-mcard-brand">${markBox("", 104, "", onLight)}<div class="alr-mcard-name">${esc(card.title || brand.name)}${card.title ? "" : badgeHtml()}</div></div>${card.sub ? `<div class="alr-mcard-sub">${esc(card.sub)}</div>` : ""}<div class="alr-mcard-chips">${chips.map(x => `<span>${esc(x)}</span>`).join("")}</div><div class="alr-ring"></div></div></div>`;
};

// A single number that counts up and lands: one stat per one-second frame.
B.metric = s => {
  const v = Number(s.value);
  if (!Number.isFinite(v)) fail(`${s.where}: value must be a number.`);
  const from = Number(s.from ?? 0);
  const t0 = r3(s.start + 0.06), land = r3(t0 + 0.62);
  const bars = Array.isArray(s.bars) ? s.bars.map(Number) : null;
  const progress = s.progress != null ? Number(s.progress) : s.suffix === "%" && !bars ? v / 100 : null;
  s.ev = {
    eyebrow: r3(s.start + 0.02), number: t0, land, label: r3(s.start + 0.2),
    counter: { keys: [{ t: 0, v: from }, { t: t0, v }], fmt: { decimals: s.decimals ?? 0 } },
    bars: bars ? bars.map((_, i) => r3(s.start + 0.16 + i * S16 / 2)) : null,
    progress: progress != null ? { at: r3(s.start + 0.14), dur: 0.62, p: Math.max(0, Math.min(1, progress)) } : null,
  };
  cue("pop", t0, { gain: 0.5, label: "number" });
  cue("tap", land, { gain: 0.45, label: "number lands" });
  const lab = s.label ? wordsHtml(s.label).html : "";
  const graph = bars ? `<div class="alr-metric-bars">${bars.map(h => `<i style="height:${r3(Math.max(0.06, Math.min(1, h)) * 100)}%"></i>`).join("")}</div>` : progress != null ? `<div class="alr-metric-track"><i></i></div>` : "";
  return `<div class="alr-bg"></div><div class="alr-center alr-metric">${s.eyebrow ? `<div class="alr-eyebrow">${esc(s.eyebrow)}</div>` : ""}<div class="alr-metric-num">${s.prefix ? `<span class="alr-metric-fix">${esc(s.prefix)}</span>` : ""}<span class="alr-metric-val">${money(from, "", s.decimals ?? 0)}</span>${s.suffix ? `<span class="alr-metric-fix">${esc(s.suffix)}</span>` : ""}</div>${lab ? `<div class="alr-metric-label">${lab}</div>` : ""}${graph}</div>`;
};

// A command-centre window: KPI tiles that count up and a bar chart that grows.
B.dashboard = s => {
  const cp = copyBlock(s.copy, `${s.where}.copy`);
  const w = s.window || {};
  const tiles = (w.tiles || []).slice(0, 4);
  if ((w.tiles || []).length > 4) warn(`${s.where}: only 4 KPI tiles fit.`);
  const chart = w.chart || null;
  const tileAt = i => r3(s.start + 0.34 + i * S16);
  s.ev = {
    copy: copyTimes(r3(s.start + 0.1), cp.count, s.beats), win: r3(s.start + 0.04), live: r3(s.start + 0.3),
    tiles: tiles.map((_, i) => tileAt(i)),
    counters: tiles.map((x, i) => ({ keys: [{ t: 0, v: Number(x.from ?? 0) }, { t: r3(tileAt(i) + 0.05), v: Number(x.value) }], fmt: { prefix: x.prefix || "", suffix: x.suffix || "", decimals: x.decimals ?? 0 } })),
    bars: chart ? (chart.bars || []).map((_, i) => r3(s.start + 0.62 + i * S16 / 2)) : [],
  };
  s.ev.tiles.forEach(tt => cue("pop", tt, { gain: 0.4, label: "kpi tile" }));
  if (s.ev.bars.length) cue("scan", s.ev.bars[0], { gain: 0.45, label: "chart grows" });
  const kpis = tiles.map(x => `<div class="alr-kpi"><small>${esc(x.label || "")}</small><div class="alr-kpi-v"><span class="v">${money(Number(x.from ?? 0), x.prefix || "", x.decimals ?? 0)}${esc(x.suffix || "")}</span></div>${x.delta ? `<em>${esc(x.delta)}</em>` : ""}</div>`).join("");
  const bars = chart ? `<div class="alr-chart"><div class="alr-chart-head"><span>${esc(chart.label || "")}</span><span>${esc(chart.note || "")}</span></div><div class="alr-bars">${(chart.bars || []).map((h, i, a) => `<i class="${i === a.length - 1 ? "hot" : ""}" style="height:${r3(Math.max(0.05, Math.min(1, Number(h))) * 100)}%"></i>`).join("")}</div></div>` : "";
  return `<div class="alr-bg"></div><div class="alr-split">${cp.html}<div class="alr-stage"><div class="alr-hero-wrap"><div class="alr-win"><div class="alr-win-head"><i></i><i></i><i></i><span>${esc(w.title || "Dashboard")}</span><b class="alr-live"><i></i>Live</b></div><div class="alr-kpis">${kpis}</div>${bars}</div></div></div></div>`;
};

// An AI conversation beside a video call card: the user types, the assistant answers, a figure
// draws, and feature chips pop. The avatar video plays through a top-level <video> (HyperFrames
// never nests media in a timed div) that the runtime lays over the card's slot.
const videos = [];
const FIGURES = {
  triangle: { view: "0 0 300 180", legs: "M24 22V158H276", right: "M24 136H46V158", hyp: "M24 22L276 158", label: { x: 162, y: 64, rot: 28.4 } },
};
B.chat = s => {
  const av = s.avatar || {};
  const items = s.messages || [];
  if (!items.length) fail(`${s.where}: messages is required.`);
  const ev = { card: r3(s.start + 0.02), items: [], chips: [], speak: [] };
  const words = t => String(t).split(/\s+/).filter(Boolean).length;
  items.forEach((m, i) => {
    const A = r3(s.start + Number(m.at ?? i * 2) * BEAT);
    if (!(A >= s.start) || A >= s.end) fail(`${s.where}.messages[${i}]: at is outside the scene.`);
    if (m.from === "user") {
      const t1 = r3(A + 0.12 + Math.min(0.8, 0.03 * String(m.text).length));
      ev.items.push({ kind: "user", pop: A, type: [r3(A + 0.12), t1] });
      cue("pop", A, { gain: 0.4, label: "user bubble" });
      cue("type", A + 0.12, { dur: r3(t1 - A - 0.12 + 0.05), gain: 0.75, label: "typing question" });
    } else if (m.from === "figure") {
      if (!FIGURES[m.kind || "triangle"]) fail(`${s.where}.messages[${i}]: figure kind must be ${Object.keys(FIGURES).join(", ")}.`);
      ev.items.push({ kind: "figure", pop: A, draw: [r3(A + 0.08), r3(A + 0.52)], hyp: [r3(A + 0.42), r3(A + 0.8)], label: r3(A + 0.78) });
      cue("pop", A, { gain: 0.45, label: "figure card" });
      cue("whoosh", A + 0.5, { align: "peak", gain: 0.2, label: "figure draws" });
      cue("pop", A + 0.78, { gain: 0.5, label: "figure label" });
    } else {
      ev.items.push({ kind: "ai", dots: r3(A - 0.42), pop: A });
      cue("pop", A, { gain: 0.55, label: "assistant bubble" });
      ev.speak.push([A, r3(A + Math.min(2.2, 0.4 + 0.24 * words(m.text)))]);
    }
  });
  const chips = s.chips || [];
  const chipsAt = r3(s.start + Number(s.chipsAt ?? (Number(items[items.length - 1].at ?? 0) + 1)) * BEAT);
  ev.chips = chips.map((_, i) => r3(chipsAt + i * S16));
  ev.chips.forEach((tc, i) => cue("pop", tc, { gain: i ? 0.3 : 0.4, label: "chip" }));
  // The video runs while the card is at rest: after the entrance, before the exit begins.
  const exitLead = s.exit ? (s.exit.type === "whip" ? s.exit.dur / 2 : s.exit.dur) : 0;
  if (av.video) {
    const abs = projectFile(av.video, `${s.where}.avatar.video`);
    if (abs) {
      const v0 = r3(s.start + 0.45), v1 = r3(s.end - exitLead - 0.06);
      const len = Number(spawnSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", abs], { encoding: "utf8" }).stdout) || 0;
      const dur = r3(Math.min(v1 - v0, len - 0.05));
      if (len && len < v1 - v0) warn(`${s.where}: the avatar clip is ${r3(len)} s; the card needs ${r3(v1 - v0)} s, so it holds its last frame.`);
      mkdirSync(join(project, "alr", "media"), { recursive: true });
      const still = (at, name) => spawnSync("ffmpeg", ["-v", "error", "-y", "-ss", String(Math.max(0, at)), "-i", abs, "-frames:v", "1", "-q:v", "2", join(project, "alr", "media", name)]);
      still(0, `${s.id}-a.jpg`);
      still(dur - 1 / FPS, `${s.id}-b.jpg`);
      ev.video = { start: v0, end: r3(v0 + dur), mid: r3(v0 + dur / 2) };
      videos.push({ id: s.id, src: av.video, start: v0, dur });
    }
  }
  s.ev = ev;
  const stills = ev.video ? `<img class="alr-still a" src="alr/media/${s.id}-a.jpg" alt=""><img class="alr-still b" src="alr/media/${s.id}-b.jpg" alt="">` : av.image ? `<img class="alr-still a" src="${esc(av.image)}" alt="">` : "";
  if (av.image) projectFile(av.image, `${s.where}.avatar.image`);
  const voice = `<div class="alr-voice">${Array.from({ length: 15 }, () => "<i></i>").join("")}</div>`;
  // The voice meter lives in the card header: the video is layered over the slot.
  const call = `<div class="alr-call"><div class="alr-call-head"><b>${esc(av.name || "Assistant")}</b>${voice}</div><div class="alr-call-slot">${stills}</div><div class="alr-call-foot"><span>${esc(av.meta || "")}</span><span>${esc(av.meta2 || "")}</span></div></div>`;
  const fig = m => {
    const F = FIGURES[m.kind || "triangle"];
    const [, , vw, vh] = F.view.split(" ").map(Number);
    return `<div class="alr-figure"><div class="alr-figure-in"><svg viewBox="${F.view}" preserveAspectRatio="none" aria-hidden="true"><path class="legs" d="${F.legs}"/><path class="right" d="${F.right}"/><path class="hyp" d="${F.hyp}"/></svg>${m.label ? `<div class="alr-figure-label" style="left:${r3(F.label.x / vw * 100)}%;top:${r3(F.label.y / vh * 100)}%;transform:translate(-50%,-50%) rotate(${F.label.rot}deg)"><span>${esc(m.label)}</span></div>` : ""}</div></div>`;
  };
  const one = m => m.from === "figure" ? fig(m).replace('<div class="alr-figure">', `<div class="alr-figure" data-item="${items.indexOf(m)}">`)
    : m.from === "user" ? `<div class="alr-msg-wrap user" data-item="${items.indexOf(m)}"><div class="alr-msg user"><small>${esc(m.label || "You")}</small><div class="alr-msg-text" data-text="${esc(m.text)}"></div></div></div>`
    : `<div class="alr-msg-wrap ai" data-item="${items.indexOf(m)}"><div class="alr-typing"><i></i><i></i><i></i></div><div class="alr-msg ai"><small>${esc(m.label || av.name || "Assistant")}</small><div class="alr-msg-text">${wordsHtml(m.text).html}</div></div></div>`;
  // An item with "beside": true shares a row with the item before it.
  const rows = [];
  items.forEach(m => { if (m.beside && rows.length) rows[rows.length - 1].push(m); else rows.push([m]); });
  const thread = rows.map(r => r.length > 1 ? `<div class="alr-thread-row">${r.map(one).join("")}</div>` : one(r[0])).join("");
  const chipHtml = chips.length ? `<div class="alr-chat-chips">${chips.map(c => `<div class="alr-pill">${c.icon ? icon(c.icon, `${s.where}.chips`) : ""}${esc(c.text ?? c)}</div>`).join("")}</div>` : "";
  return `<div class="alr-bg"></div><div class="alr-haze h1"></div><div class="alr-haze h2"></div>${call}<div class="alr-thread">${s.eyebrow ? `<div class="alr-chat-eyebrow alr-eyebrow">${esc(s.eyebrow)}</div>` : ""}${thread}${chipHtml}</div>`;
};

// A permission grid: roles by modules, filling in a diagonal wave.
B.matrix = s => {
  const cp = copyBlock(s.copy, `${s.where}.copy`);
  const tb = s.table || {};
  const cols = tb.cols || [], rows = tb.rows || [];
  if (!cols.length || !rows.length) fail(`${s.where}: table needs cols and rows.`);
  if (cols.length > 5 || rows.length > 5) warn(`${s.where}: keep the grid to 5 by 5.`);
  const cellAt = (i, j) => r3(s.start + 0.36 + (i + j) * S16 / 2);
  s.ev = {
    copy: copyTimes(r3(s.start + 0.1), cp.count, s.beats), win: r3(s.start + 0.04),
    rows: rows.map((_, i) => r3(s.start + 0.2 + i * S16 / 2)),
    cells: rows.map((_, i) => cols.map((_, j) => cellAt(i, j))),
    foot: r3(cellAt(rows.length - 1, cols.length - 1) + 0.16),
  };
  for (let d = 0; d < rows.length + cols.length - 1; d++) cue("tap", s.start + 0.36 + d * S16 / 2, { gain: d % 2 ? 0.22 : 0.32, label: "grid fills" });
  if (tb.footer) cue("pop", s.ev.foot, { gain: 0.45, label: "grid footer" });
  const cell = v => v === true || v === 1 ? `<b class="on"><svg viewBox="0 0 24 24"><path d="M6 12.5l4 4 8-9"/></svg></b>` : v === "view" || v === "v" ? `<b class="view"><i></i></b>` : `<b class="off"></b>`;
  const grid = `<div class="alr-grid" style="grid-template-columns:190px repeat(${cols.length}, 1fr)"><span></span>${cols.map(c => `<span class="alr-grid-col">${esc(c)}</span>`).join("")}${rows.map(r => `<span class="alr-grid-row">${esc(r.label)}</span>${cols.map((_, j) => `<span class="alr-grid-cell">${cell((r.cells || [])[j])}</span>`).join("")}`).join("")}</div>`;
  const legend = tb.legend !== false ? `<div class="alr-grid-legend"><span><b class="on"><svg viewBox="0 0 24 24"><path d="M6 12.5l4 4 8-9"/></svg></b>${esc(tb.fullLabel || "Full access")}</span><span><b class="view"><i></i></b>${esc(tb.viewLabel || "View only")}</span></div>` : "";
  return `<div class="alr-bg"></div><div class="alr-split">${cp.html}<div class="alr-stage"><div class="alr-hero-wrap"><div class="alr-win alr-matrix"><div class="alr-win-head"><i></i><i></i><i></i><span>${esc(tb.title || "Permissions")}</span>${tb.badge ? `<b class="alr-live alr-lock">${icon("lock", s.where)}${esc(tb.badge)}</b>` : ""}</div>${grid}${legend}${tb.footer ? `<div class="alr-grid-foot">${icon(tb.footerIcon || "shield", s.where)}${esc(tb.footer)}</div>` : ""}</div></div></div></div>`;
};

// One word per beat, and the background flips with every word: the kinetic close of a reel.
B.burst = s => {
  const words = s.words || [];
  if (!words.length) fail(`${s.where}: words is required.`);
  const each = Number(s.each ?? 1) * BEAT;
  if (Math.abs(words.length * each - (s.end - s.start)) > 1e-6) warn(`${s.where}: ${words.length} words of ${s.each ?? 1} beat(s) do not fill ${s.beats} beats.`);
  const tones = s.burstTones;
  s.ev = { words: words.map((_, i) => r3(s.start + i * each)), each: r3(each), tones: words.map((_, i) => tones[i % tones.length]) };
  s.ev.words.forEach((tw, i) => {
    cue("tap", tw, { gain: 0.9, label: `burst ${words[i]}` });
    if (i) cue("whoosh", tw - 0.02, { align: "peak", gain: 0.28, label: "burst flip" });
  });
  cue("impact", s.ev.words[words.length - 1], { align: "peak", gain: 0.55, label: "burst last word" });
  return words.map((w, i) => {
    const tone = s.ev.tones[i], lum = TONE_LUM[tone];
    return `<div class="alr-burst-layer tone-${tone} alr-${lum === "light" ? "light" : lum === "mid" ? "mid" : "dark"}" style="opacity:${i ? 0 : 1}"><div class="alr-bg"></div><div class="alr-center"><div class="alr-burst-word">${esc(w)}</div>${s.index !== false ? `<div class="alr-burst-idx">${String(i + 1).padStart(2, "0")} / ${String(words.length).padStart(2, "0")}</div>` : ""}</div></div>`;
  }).join("");
};

scenes.forEach((s, i) => {
  const body = B[s.type](s);
  whooshFor(s);
  sceneHtml.push(`<div id="s-${s.id}" class="alr-scene clip ${toneClass(s)}${s.irised ? " alr-irised" : ""}" data-start="${r3(s.clipStart)}" data-duration="${r3(s.clipEnd - s.clipStart)}" data-track-index="${1 + (i % 2)}" style="z-index:${i + 1}">
  <div class="alr-cam">${body}</div>${overlays(s)}
</div>`);
  // Media sits outside the timed scene, one layer above it and below the next scene.
  const v = videos.find(x => x.id === s.id);
  if (v) sceneHtml.push(`<div class="alr-vwrap" id="vw-${s.id}" style="z-index:${i + 1}"><video id="v-${s.id}" src="${esc(v.src)}" data-start="${v.start}" data-duration="${v.dur}" data-track-index="3" muted playsinline></video></div>`);
  cfgScenes.push({ id: s.id, type: s.type, start: s.start, end: s.end, tone: s.tone, exit: s.exit || null, ev: s.ev });
  if (s.type !== "endcard") hudChapters.push({ from: s.start, label: chapterLabel(s), light: s.lum === "light" });
  if (s.type === "stack" && s.ev.flip) hudChapters.push({ from: r3((s.ev.flip[0] + s.ev.flip[1]) / 2), label: chapterLabel(s), light: false });
  if (s.type === "burst") s.ev.words.slice(1).forEach((tw, k) => hudChapters.push({ from: tw, label: chapterLabel(s), light: TONE_LUM[s.ev.tones[k + 1]] === "light" }));
});
if (videos.length > 1) warn("Only one scene should carry video; each extra video shares track 3 and must not overlap.");
done();
const endcard = scenes.find(s => s.type === "endcard");
const cfg = {
  W, H, fps: FPS, D, beat: BEAT, s16: S16, bpm: BPM,
  hud: { showAt: 0.3, hideAt: endcard ? r3(endcard.start - 0.28) : D + 1, chapters: hudChapters },
  scenes: cfgScenes,
};

// ---------------------------------------------------------------- audio mix
const SFX_KINDS = ["whoosh", "pop", "tap", "type", "riser", "impact", "success", "scan", "shimmer"];
const GAIN = { whoosh: 0.85, pop: 0.6, tap: 0.6, type: 0.5, riser: 0.7, impact: 1.3, success: 0.6, scan: 0.55, shimmer: 1.0 };
const alrDir = join(project, "alr");
mkdirSync(join(alrDir, "audio"), { recursive: true });
let audioTag = "", mixInfo = "silent (no music or sfx in the plan)";
const hasAudio = !noAudio && (music.file || plan.sfx || plan.voice);
const measure = f => {
  const e = spawnSync("ffmpeg", ["-hide_banner", "-nostats", "-i", f, "-af", "ebur128=peak=true", "-f", "null", "-"], { encoding: "utf8" }).stderr;
  const num = re => Number(((e.match(re) || []).pop() || "").match(/-?[\d.]+/)?.[0]);
  return { I: num(/I:\s+-?[\d.]+ LUFS/g), TP: num(/Peak:\s+-?[\d.]+ dBFS/g) };
};

function analyze(file) {
  const r = spawnSync("ffmpeg", ["-v", "error", "-i", file, "-ac", "1", "-ar", "22050", "-f", "f32le", "-"], { maxBuffer: 1 << 29 });
  if (r.status !== 0) { fail(`ffmpeg could not decode ${relative(project, file)}`); return null; }
  const b = r.stdout, x = new Float32Array(b.buffer.slice(b.byteOffset, b.byteOffset + b.length - (b.length % 4)));
  const hop = 220, n = Math.floor(x.length / hop), e = new Float64Array(n);
  for (let i = 0; i < n; i++) { let s = 0; for (let j = 0; j < hop; j++) { const v = x[i * hop + j]; s += v * v; } e[i] = Math.sqrt(s / hop); }
  let pk = 0; for (let i = 1; i < n; i++) if (e[i] > e[pk]) pk = i;
  let on = 0; while (on < pk && e[on] < e[pk] * 0.1) on++;
  let end = n - 1; while (end > pk && e[end] < e[pk] * 0.05) end--;
  return { len: x.length / 22050, peak: pk / 100, onset: on / 100, end: (end + 1) / 100 };
}

if (hasAudio) {
  const sfxMap = plan.sfx || {};
  const files = {};
  for (const k of Object.keys(sfxMap)) {
    if (!SFX_KINDS.includes(k)) { warn(`sfx.${k} is not a cue kind (${SFX_KINDS.join(", ")}); ignored.`); continue; }
    const spec = typeof sfxMap[k] === "string" ? { file: sfxMap[k] } : sfxMap[k];
    const abs = projectFile(spec.file, `sfx.${k}`);
    if (!abs) continue;
    const a = analyze(abs);
    if (!a) continue;
    files[k] = { abs, gain: spec.gain ?? GAIN[k], trim: Number(spec.trim) || 0, ...a };
    if (spec.peak != null) files[k].peak = Number(spec.peak);
  }
  const musicAbs = music.file ? projectFile(music.file, "music.file") : null;
  done();
  const missing = [...new Set(cues.map(c => c.kind))].filter(k => !files[k]);
  if (missing.length) warn(`No sfx for ${missing.join(", ")}; those cues are silent. Add them to plan.sfx (see references/sound-design.md).`);

  const inputs = [], chains = [], labels = [];
  const add = f => { inputs.push("-i", f); return inputs.length / 2 - 1; };
  const placed = [];
  cues.forEach((c, i) => {
    const f = files[c.kind];
    if (!f) return;
    // File time `ref` lands on reel time c.at; nothing may start before the reel does.
    const ref = c.align === "peak" ? f.peak : Math.max(f.onset, f.trim);
    let from = Math.max(f.trim, ref - Math.min(c.at, c.lead ?? Infinity));
    if (c.kind === "type") from = Math.max(f.trim, f.onset);
    const start = c.at - (ref - from);
    let len = c.dur ? c.dur : Math.min(f.len - from, D - start);
    len = Math.max(0.02, Math.min(len, D - start));
    const fade = c.dur ? 0.04 : Math.min(0.25, len * 0.3);
    const k = add(f.abs);
    const g = f.gain * (c.gain ?? 1);
    chains.push(`[${k}:a]atrim=start=${r3(from)}:duration=${r3(len)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${g.toFixed(3)},afade=t=out:st=${r3(Math.max(0, len - fade))}:d=${r3(fade)},adelay=${Math.round(start * 1000)}:all=1[c${i}]`);
    labels.push(`[c${i}]`);
    placed.push({ ...c, start: r3(start), from: r3(from), len: r3(len), file: relative(project, f.abs) });
  });
  if (musicAbs) {
    const mStart = Number(music.start) || 0;
    // The bed sits under the sound design, then lifts at the drop: the reel is quiet-loud-quiet.
    const mg = music.gain ?? 0.5;
    const lift = music.lift ?? 3.2;
    const hitAt = scenes.find(s => s.hit != null)?.hit;
    const drop = scenes.find(s => s.drop != null)?.drop;
    const gap = music.gap === false ? 0 : Number(music.gap ?? BEAT / 2);
    // Under the lockup the bed dies away in about a bar so the shimmer rings out on its own.
    const fadeFrom = endcard ? r3(endcard.start + 0.1) : r3(D - 1.2);
    const fadeLen = r3(Math.min(Number(music.fade) || 1.3, D - fadeFrom));
    const seg = (a, b, tag, gain, fin, fout, finCurve) => {
      const k = add(musicAbs);
      const delay = Math.max(0, a);
      const src = mStart + a;
      const pre = src < 0 ? -src : 0;
      chains.push(`[${k}:a]atrim=start=${r3(Math.max(0, src))}:duration=${r3(b - a - pre)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${gain.toFixed(3)}${fin ? `,afade=t=in:d=${fin}${finCurve ? `:curve=${finCurve}` : ""}` : ""}${fout ? `,afade=t=out:st=${r3(b - a - pre - fout)}:d=${fout}` : ""},adelay=${Math.round((delay + pre) * 1000)}:all=1[${tag}]`);
      labels.push(`[${tag}]`);
    };
    // Before the opening hit the bed swells in under the riser, so the hit is the first loud moment.
    const swell = music.swell === false || hitAt == null ? 0 : r3(hitAt);
    if (drop != null && gap > 0) {
      seg(0, drop - gap, "m1", mg, swell, 0.015, "exp");
      seg(drop, D, "m2", mg * lift, 0.005, 0);
    } else seg(0, D, "m1", mg, swell, 0, "exp");
    // The bed fades under the lockup so the shimmer rings out alone.
    const last = labels.pop();
    chains.push(`${last}afade=t=out:st=${fadeFrom}:d=${fadeLen}:curve=qsin${last.replace("[", "[f")}`);
    labels.push(last.replace("[", "[f"));
    placed.push({ kind: "music", file: relative(project, musicAbs), start: 0, from: mStart, gapBefore: drop ?? null, gap, fadeFrom });
  }
  // Voiceover: each line is its own file, placed so its first syllable lands on a scene beat
  // (`scene` + `beat`) or an absolute time (`at`). Every line is levelled to `voice.level` LUFS,
  // and the bed and the effects duck under the voice through sidechain compressors.
  const voice = plan.voice || null, voLabels = [];
  if (voice) {
    const lines = (voice.lines || []).map((ln, i) => {
      const where = `voice.lines[${i}]`;
      let at = ln.at != null ? Number(ln.at) : null;
      if (ln.scene != null) {
        const sc = typeof ln.scene === "number" ? scenes[ln.scene - 1] : scenes.find(x => x.id === slug(ln.scene));
        if (!sc) { fail(`${where}: scene ${ln.scene} not found (use a 1-based number or a scene id).`); return null; }
        at = sc.start + Number(ln.beat || 0) * BEAT;
      }
      if (!(at >= 0) || at >= D) { fail(`${where}: the line starts outside the reel.`); return null; }
      const abs = projectFile(ln.file, `${where}.file`);
      if (!abs) return null;
      const a = analyze(abs), m = measure(abs);
      return a && { ...ln, where, abs, at: r3(at), onset: a.onset, len: a.len, end: a.end, I: m.I };
    }).filter(Boolean).sort((a, b) => a.at - b.at);
    done();
    const level = Number(voice.level ?? -12), vgain = Number(voice.gain ?? 1);
    lines.forEach((ln, i) => {
      // Trailing silence is trimmed: a line ends 0.15 s after its last audible frame.
      const from = Math.max(0, ln.onset - 0.04), start = ln.at - (ln.onset - from);
      const len = Math.max(0.05, Math.min(Math.min(ln.len, ln.end + 0.15) - from, D - start));
      const end = r3(ln.at + (ln.end - ln.onset));
      const next = lines[i + 1];
      if (next && end > next.at - 0.05) warn(`${ln.where} ("${ln.text || ln.file}") speaks until ${end} s and runs into the next line at ${next.at} s.`);
      if (end > D - 0.3) warn(`${ln.where} runs to ${r3(end)} s; end the voice before the last 0.3 s so the reel rings out.`);
      const gdb = Number.isFinite(ln.I) ? Math.max(-24, Math.min(24, level - ln.I)) : 0;
      const g = Math.pow(10, gdb / 20) * vgain * (ln.gain ?? 1);
      const k = add(ln.abs);
      chains.push(`[${k}:a]atrim=start=${r3(from)}:duration=${r3(len)},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,volume=${g.toFixed(3)},afade=t=in:d=0.02,afade=t=out:st=${r3(Math.max(0, len - 0.06))}:d=0.06,adelay=${Math.round(start * 1000)}:all=1[v${i}]`);
      voLabels.push(`[v${i}]`);
      placed.push({ kind: "voice", text: ln.text, file: relative(project, ln.abs), at: ln.at, start: r3(start), from: r3(from), len: r3(len) });
    });
  }
  if (labels.length || voLabels.length) {
    const raw = join(alrDir, "audio", "mix-raw.wav"), out = join(alrDir, "audio", "mix.wav");
    // The sfx, bed, and voice layers are mixed into buses. Under a voiceover, the bed and the
    // effects duck through sidechain compressors keyed by the voice. Each bus is also written
    // as a stem: the audit checks whoosh timing, the kick grid, and the voice on those.
    const isBed = l => /^\[f?m\d/.test(l);
    const bus = (ls, tag) => ls.length ? `${ls.join("")}amix=inputs=${ls.length}:normalize=0:duration=longest,apad=whole_dur=${D},atrim=0:${D}[${tag}]` : null;
    const graph = [...chains];
    const layers = [];
    const sfxL = labels.filter(l => !isBed(l)), bedL = labels.filter(isBed);
    if (sfxL.length) { graph.push(bus(sfxL, "sfxbus")); layers.push({ tag: "sfx", bus: "sfxbus" }); }
    if (bedL.length) { graph.push(bus(bedL, "bedbus")); layers.push({ tag: "bed", bus: "bedbus" }); }
    if (voLabels.length) {
      graph.push(bus(voLabels, "vobus"));
      const keys = layers.map((_, i) => `[vok${i}]`);
      graph.push(`[vobus]asplit=${keys.length + 1}${keys.join("")}[vodry]`);
      // Bed: about 10 dB of ducking under speech. Effects: a gentler 5-6 dB, so pops stay audible.
      const duckBed = Number(voice.duck ?? 6), duckSfx = Number(voice.duckSfx ?? 2);
      layers.forEach((L, i) => {
        graph.push(`[${L.bus}]${keys[i]}sidechaincompress=threshold=0.063:ratio=${L.tag === "bed" ? duckBed : duckSfx}:attack=15:release=${L.tag === "bed" ? 380 : 220}:makeup=1[${L.bus}d]`);
        L.bus = `${L.bus}d`;
      });
      layers.push({ tag: "voice", bus: "vodry" });
    }
    layers.forEach(L => graph.push(`[${L.bus}]asplit=2[${L.tag}m][${L.tag}]`));
    graph.push(`${layers.map(L => `[${L.tag}m]`).join("")}amix=inputs=${layers.length}:normalize=0:duration=longest,atrim=0:${D},afade=t=out:st=${r3(D - 0.04)}:d=0.04[mix]`);
    const fc = graph.join(";");
    mkdirSync(join(alrDir, "audio", "stems"), { recursive: true });
    const stemMaps = layers.flatMap(L => ["-map", `[${L.tag}]`, "-ar", "48000", "-c:a", "pcm_s16le", join(alrDir, "audio", "stems", `${L.tag}.wav`)]);
    let r = spawnSync("ffmpeg", ["-v", "error", "-y", ...inputs, "-filter_complex", fc, "-map", "[mix]", "-ar", "48000", "-c:a", "pcm_s16le", raw, ...stemMaps], { encoding: "utf8" });
    if (r.status !== 0) { fail(`ffmpeg mix failed: ${r.stderr.slice(-600)}`); done(); }
    // Loudness: a linear gain to -14 LUFS into a limiter that runs at 4x the sample rate, so it
    // catches inter-sample peaks. The -5 dBFS ceiling leaves room for the renderer's AAC encode,
    // which adds up to ~3 dB of overshoot on a dense drop. The limiter costs some loudness, so the
    // gain is corrected and the pass repeated until the result lands within 0.25 LU.
    const m0 = measure(raw);
    let gainDb = Number.isFinite(m0.I) ? -14 - m0.I : 0, got = null;
    for (let pass = 0; pass < 3; pass++) {
      const af = `volume=${gainDb.toFixed(2)}dB,aresample=192000,alimiter=limit=0.56:attack=1:release=50:level=false,aresample=48000`;
      r = spawnSync("ffmpeg", ["-v", "error", "-y", "-i", raw, "-af", af, "-ar", "48000", "-c:a", "pcm_s16le", out], { encoding: "utf8" });
      if (r.status !== 0) { fail(`ffmpeg loudness pass failed: ${r.stderr.slice(-600)}`); done(); }
      got = measure(out);
      if (!Number.isFinite(got.I) || Math.abs(got.I + 14) < 0.25) break;
      gainDb += -14 - got.I;
    }
    if (got && got.TP > -4) warn(`mix.wav peaks at ${got.TP} dBTP; after the AAC encode it may pass -1 dBTP. Lower the bed lift or the impact gain.`);
    audioTag = `<audio id="alr-mix" src="alr/audio/mix.wav" data-start="0" data-duration="${D}" data-track-index="0" data-volume="1"></audio>`;
    mixInfo = `alr/audio/mix.wav (${placed.filter(p => p.kind !== "music" && p.kind !== "voice").length} sfx cues${musicAbs ? " + music bed" : ""}${voLabels.length ? ` + ${voLabels.length} voice lines` : ""}, input ${m0.I} LUFS -> ${got?.I} LUFS, ${got?.TP} dBTP)`;
  }
  writeFileSync(join(alrDir, "cues.json"), JSON.stringify({ bpm: BPM, beat: BEAT, duration: D, cuts: scenes.slice(0, -1).map(s => ({ at: s.end, type: s.exitType, from: s.id })), cues: placed }, null, 2) + "\n");
} else {
  writeFileSync(join(alrDir, "cues.json"), JSON.stringify({ bpm: BPM, beat: BEAT, duration: D, cuts: scenes.slice(0, -1).map(s => ({ at: s.end, type: s.exitType, from: s.id })), cues }, null, 2) + "\n");
}

// ---------------------------------------------------------------- kit, fonts, gsap
cpSync(join(SKILL, "assets", "fonts"), join(alrDir, "fonts"), { recursive: true });
copyFileSync(join(SKILL, "assets", "alr-kit.css"), join(alrDir, "alr-kit.css"));
copyFileSync(join(SKILL, "assets", "alr-kit.js"), join(alrDir, "alr-kit.js"));
const gsapLocal = join(project, "assets", "gsap.min.js");
if (!existsSync(gsapLocal)) {
  const src = join(KIT_ROOT, "node_modules/gsap/dist/gsap.min.js");
  if (!existsSync(src)) { fail("assets/gsap.min.js is missing and node_modules/gsap is not installed (run npm ci in the kit root)."); done(); }
  mkdirSync(dirname(gsapLocal), { recursive: true });
  copyFileSync(src, gsapLocal);
}

// ---------------------------------------------------------------- index.html
const stamp = new Date().toISOString().replace(/[:.]/g, "-");
function archive(file) {
  const p = join(project, file);
  if (!existsSync(p)) return;
  const text = readFileSync(p, "utf8");
  if (text.includes(GENERATED) || text.includes("generated by app-launch-reel")) return;
  mkdirSync(join(project, "archive"), { recursive: true });
  renameSync(p, join(project, "archive", `${stamp}-${file}`));
  console.log(`Archived the previous ${file} to archive/${stamp}-${file}`);
}
archive("index.html");
archive("DESIGN.md");

const vars = `--alr-ink:${P.ink};--alr-glow:${P.glow};--alr-brand:${P.brand};--alr-brand-2:${P.brand2};--alr-paper:${P.paper};--alr-haze:${P.haze};--alr-violet:${P.violet};--alr-violet-edge:${P.violetEdge};--alr-night:${P.night};--alr-black:${P.black};--alr-soft:${P.soft};--alr-accent:${P.accent};--alr-success:${P.success};--alr-w:${W}px;--alr-h:${H}px`;
const filters = scenes.map(s => `<filter id="s-${s.id}-mb" x="-0.12" y="0" width="1.24" height="1" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="0 0"/></filter>`).join("");
const html = `<!doctype html>
${GENERATED}
<html lang="en"><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' data:; img-src 'self' data: blob:; font-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self' data: blob:; object-src 'none'; base-uri 'self'; form-action 'none'">
<meta name="viewport" content="width=${W}, height=${H}">
<title>${esc(plan.title || `${brand.name} launch reel`)}</title>
<link rel="stylesheet" href="alr/alr-kit.css">
<style>
@font-face{font-family:"ALR Inter";src:url("alr/fonts/Inter-Latin-VF.ttf") format("truetype");font-weight:100 900;font-display:block}
@font-face{font-family:"ALR Mono";src:url("alr/fonts/JetBrainsMono-Latin-VF.ttf") format("truetype");font-weight:100 800;font-display:block}
html,body{margin:0;padding:0;background:#000}
#main{position:relative;width:${W}px;height:${H}px;overflow:hidden;${vars}}
</style></head><body>
<div id="main" class="${FORMAT === "portrait" ? "alr-portrait" : "alr-landscape"}${MONO ? " alr-mono" : ""}" data-composition-id="main" data-start="0" data-duration="${D}" data-fps="${FPS}" data-width="${W}" data-height="${H}">
${sceneHtml.join("\n")}
<div id="alr-hud" class="alr-hud">${HUD.top ? `<div class="tl"><i></i>${esc(brand.name)}<b>/</b>${esc(brand.reel || "Motion reel")}</div><div class="tr"></div>` : ""}${HUD.bottom ? `<div class="bl">00:00:00:00</div><div class="br"><span></span></div>` : ""}</div>
<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>${filters}</defs></svg>
${audioTag}
<script src="assets/gsap.min.js"></script>
<script src="alr/alr-kit.js"></script>
<script>
window.ALR_CONFIG = ${JSON.stringify(cfg)};
(function () {
  var tl = ALR.build(window.ALR_CONFIG);
  window.__timelines = window.__timelines || {};
  window.__timelines["main"] = tl;
})();
</script>
</div>
</body></html>
`;
writeFileSync(join(project, "index.html"), html);

// ---------------------------------------------------------------- DESIGN.md
const design = `# ${brand.name} launch reel: DESIGN
${GENERATED.replace("<!--", "<!-- regenerated on every build;")}

## Style Prompt
A chaptered product motion reel in the app-launch-reel style: one idea per frame, the product
shown working, and every cut on a ${BPM} BPM grid. Backgrounds flip luminance at each cut
(dark, brand mid-tone, paper white), a mono HUD frames every chapter, and every visual event
has a sound. Confident, optimistic, premium-tech.

## Colors
- Ink ${P.ink} with a ${P.glow} glow: identity, scan, and feature frames.
- Brand ${P.brand} -> ${P.brand2}: statements, languages, and the end card.
- Paper ${P.paper} with a ${P.haze} haze: the product demo and light mode.
- Violet ${P.violet} -> ${P.violetEdge}: device and widget frames.
- Soft ${P.soft}: second lines on dark. Accent ${P.accent}: hand-drawn annotation only, once.
- Success ${P.success}: completed actions inside the app UI only.

## Typography
- Inter (variable, opsz 32) 750-800, tracking -0.04 to -0.05 em for headlines and the wordmark.
- Inter 600, 0.24 em spaced caps for eyebrows; Inter 450 for sub copy.
- JetBrains Mono 500, 0.16 em caps for the HUD.

## Motion
- Grid: beat ${r3(BEAT)} s, sixteenth ${r3(S16)} s. Cuts on beats; word and row staggers on sixteenths.
- Words rise through masks (power4.out, ~0.5 s); devices fly in with echo trails; nothing is ever frozen.
- Transitions: ${[...new Set(scenes.filter(s => s.exitType).map(s => s.exitType))].join(", ")}.

## What NOT to Do
- No two adjacent scenes with the same luminance.
- No more than one sentence per frame; no paragraphs.
- No off-grid cuts, no silent transitions, no fade-to-black between chapters.
- No real brand logos, app icons, or trademarks in the device UI.
`;
writeFileSync(join(project, "DESIGN.md"), design);

// ---------------------------------------------------------------- report
done();
console.log(`Built ${relative(process.cwd(), join(project, "index.html"))}: ${W}x${H} @ ${FPS} fps, ${D} s, ${BPM} BPM (beat ${r3(BEAT)} s).`);
console.log("Timeline:");
scenes.forEach(s => console.log(`  ${s.start.toFixed(3).padStart(7)}  ${s.type.padEnd(10)} ${String(s.beats).padStart(3)} beats  ${s.tone.padEnd(7)} ${s.lum.padEnd(6)} ${s.exitType ? `-> ${s.exitType} at ${s.end}` : "(end)"}`));
const idn = scenes.find(s => s.type === "identity");
if (idn) console.log(`Opening hit at ${idn.hit} s: cue the bed with beat-grid.mjs --hit ${idn.hit}.`);
const man = scenes.find(s => s.type === "manifesto");
if (man) console.log(`Manifesto drop at ${man.start} s (bed gap ${r3(music.gap === false ? 0 : Number(music.gap ?? BEAT / 2))} s before it).`);
console.log(`Audio: ${mixInfo}`);
console.log(`Cue sheet: alr/cues.json (${cues.length} cues).`);
